import type{PoolClient}from'pg';import type{Migration}from'./types';
/** BE-19G operational Vendor/Service cost only; no AP, purchase invoice, tax, GL, or payment. */
export const migration0201CreateVendorServiceCosts:Migration={id:'0201_create_vendor_service_costs',async up(c:PoolClient){await c.query(`CREATE TABLE vendor_service_costs(
 id UUID PRIMARY KEY,client_id UUID NOT NULL REFERENCES clients(id),building_id UUID NOT NULL REFERENCES buildings(id),vendor_id UUID NOT NULL REFERENCES vendors(id),context_type TEXT NOT NULL,vendor_work_id UUID REFERENCES vendor_works(id),work_order_id UUID REFERENCES work_orders(id),service_request_id UUID REFERENCES service_requests(id),cost_amount NUMERIC NOT NULL,cost_date DATE NOT NULL,cost_type TEXT NOT NULL,cost_category TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'DRAFT',reference TEXT,notes TEXT,created_by_user_id UUID NOT NULL REFERENCES users(id),finalized_at TIMESTAMPTZ,finalized_by_user_id UUID REFERENCES users(id),cancelled_at TIMESTAMPTZ,cancelled_by_user_id UUID REFERENCES users(id),created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
 CONSTRAINT vendor_service_costs_context_type_check CHECK(context_type IN('VENDOR_WORK','SERVICE_REQUEST')),
 CONSTRAINT vendor_service_costs_context_reference_check CHECK((vendor_work_id IS NOT NULL)::int+(service_request_id IS NOT NULL)::int=1),
 CONSTRAINT vendor_service_costs_type_reference_check CHECK((context_type='VENDOR_WORK' AND vendor_work_id IS NOT NULL AND work_order_id IS NOT NULL) OR(context_type='SERVICE_REQUEST' AND service_request_id IS NOT NULL AND work_order_id IS NULL)),
 CONSTRAINT vendor_service_costs_amount_check CHECK(cost_amount>0),CONSTRAINT vendor_service_costs_status_check CHECK(status IN('DRAFT','FINALIZED','CANCELLED')),
 CONSTRAINT vendor_service_costs_state_check CHECK((status='DRAFT' AND finalized_at IS NULL AND cancelled_at IS NULL)OR(status='FINALIZED' AND finalized_at IS NOT NULL AND finalized_by_user_id IS NOT NULL AND cancelled_at IS NULL)OR(status='CANCELLED' AND cancelled_at IS NOT NULL AND cancelled_by_user_id IS NOT NULL)))`);await c.query(`CREATE INDEX vendor_service_costs_vendor_idx ON vendor_service_costs(vendor_id,cost_date DESC);CREATE INDEX vendor_service_costs_building_idx ON vendor_service_costs(building_id,cost_date DESC);CREATE INDEX vendor_service_costs_work_order_idx ON vendor_service_costs(work_order_id,cost_date DESC);CREATE INDEX vendor_service_costs_status_idx ON vendor_service_costs(status,cost_date DESC)`);await c.query(`CREATE TABLE vendor_service_cost_history(id UUID PRIMARY KEY,vendor_service_cost_id UUID NOT NULL REFERENCES vendor_service_costs(id),action TEXT NOT NULL,cost_amount NUMERIC NOT NULL,cost_date DATE NOT NULL,cost_type TEXT NOT NULL,cost_category TEXT NOT NULL,status TEXT NOT NULL,reference TEXT,notes TEXT,changed_by_user_id UUID NOT NULL REFERENCES users(id),changed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),CONSTRAINT vendor_service_cost_history_action_check CHECK(action IN('CREATED','UPDATED','FINALIZED','CANCELLED')))`);await c.query('CREATE INDEX vendor_service_cost_history_cost_idx ON vendor_service_cost_history(vendor_service_cost_id,changed_at)')},async down(c:PoolClient){await c.query('DROP TABLE IF EXISTS vendor_service_cost_history');await c.query('DROP TABLE IF EXISTS vendor_service_costs')}};
