import { Router } from 'express';
import { createAreaRouter } from '../modules/areas/area.routes';
import { createBasicExpenseRouter } from '../modules/basic-expenses/basic-expense.routes';
import { createBasicFinancialReportingRouter } from '../modules/basic-financial-reporting/basic-financial-reporting.routes';
import { createOperationalFinanceRouter } from '../modules/operational-finance/operational-finance.routes';
import { createContractorContextRouter } from '../modules/contractor-contexts/contractor-context.routes';
import { createPermitApplicationRouter } from '../modules/permit-applications/permit-application.routes';
import { createPermitApprovalRouter } from '../modules/permit-approvals/permit-approval.routes';
import { createPermitEquipmentRouter } from '../modules/permit-equipment/permit-equipment.routes';
import { createPermitEvidenceRouter } from '../modules/permit-evidence/permit-evidence.routes';
import { createPermitSafetyRequirementRouter } from '../modules/permit-safety-requirements/permit-safety-requirement.routes';
import { createPermitValidityRouter } from '../modules/permit-validities/permit-validity.routes';
import { createPermitWorkerRouter } from '../modules/permit-workers/permit-worker.routes';
import { createPermitWorkContextRouter } from '../modules/permit-work-contexts/permit-work-context.routes';
import { createPermitWorkLifecycleRouter } from '../modules/permit-work-lifecycle/permit-work-lifecycle.routes';
import { createIncidentRouter } from '../modules/incidents/incident.routes';
import { createOperationalIncidentRouter } from '../modules/operational-incidents/operational-incident.routes';
import { createAssetFailureRouter } from '../modules/asset-failures/asset-failure.routes';
import { createFindingEscalationRouter } from '../modules/finding-escalations/finding-escalation.routes';
import { createImmediateActionRouter } from '../modules/immediate-actions/immediate-action.routes';
import { createInvestigationReadinessRouter } from '../modules/investigation-readiness/investigation-readiness.routes';
import { createCorrectiveActionRouter } from '../modules/corrective-actions/corrective-action.routes';
import { createCorrectiveActionResponsibilityRouter } from '../modules/corrective-action-responsibilities/corrective-action-responsibility.routes';
import { createCorrectiveActionVerificationRouter } from '../modules/corrective-action-verifications/corrective-action-verification.routes';
import { createDocumentRouter } from '../modules/documents/document.routes';
import { createDocumentVersionRouter } from '../modules/document-versions/document-version.routes';
import { createDocumentExpiryRouter } from '../modules/document-expiry/document-expiry.routes';
import { createDocumentApprovalRouter } from '../modules/document-approvals/document-approval.routes';
import { createWorkCompletionDocumentRouter } from '../modules/work-completion-documents/work-completion-document.routes';
import { createBastDocumentRouter } from '../modules/bast-documents/bast-document.routes';
import { createHandoverDocumentRouter } from '../modules/handover-documents/handover-document.routes';
import { createAcceptanceSignOffRouter } from '../modules/acceptance-sign-offs/acceptance-sign-off.routes';
import { createSupportingDocumentRouter } from '../modules/supporting-documents/supporting-document.routes';
import { createIncidentClosureRouter } from '../modules/incident-closure/incident-closure.routes';
import { createPermitRouter } from '../modules/permits/permit.routes';
import { createAssetCategoryRouter } from '../modules/asset-categories/asset-category.routes';
import { createAssetCertificationRouter } from '../modules/asset-certifications/asset-certification.routes';
import { createAssetHistoryRouter } from '../modules/asset-history/asset-history.routes';
import { createAssetIdentifierRouter } from '../modules/asset-identifiers/asset-identifier.routes';
import { createAssetTypeRouter } from '../modules/asset-types/asset-type.routes';
import { createAssetWarrantyRouter } from '../modules/asset-warranties/asset-warranty.routes';
import { createAssetRouter } from '../modules/assets/asset.routes';
import { createAuditRouter } from '../modules/audit/audit.routes';
import { createAuthRouter } from '../modules/auth/auth.routes';
import { createCleaningAreaRouter } from '../modules/cleaning-areas/cleaning-area.routes';
import { createCleaningScheduleBindingRouter } from '../modules/cleaning-schedule-bindings/cleaning-schedule-binding.routes';
import { createCleaningAssignmentRouter } from '../modules/cleaning-assignments/cleaning-assignment.routes';
import { createDailyCleaningRouter } from '../modules/daily-cleaning/daily-cleaning.routes';
import { createInventoryItemRouter } from '../modules/inventory-items/inventory-item.routes';
import { createInvoicePaymentStatusRouter } from '../modules/invoice-payment-status/invoice-payment-status.routes';
import { createInventoryWarehouseRouter } from '../modules/inventory-warehouses/inventory-warehouse.routes';
import { createInventoryStockBalanceRouter } from '../modules/inventory-stock-balances/inventory-stock-balance.routes';
import { createInventoryStockMovementRouter } from '../modules/inventory-stock-movements/inventory-stock-movement.routes';
import { createInventoryStockTransferRouter } from '../modules/inventory-stock-transfers/inventory-stock-transfer.routes';
import { createInventoryStockAdjustmentRouter } from '../modules/inventory-stock-adjustments/inventory-stock-adjustment.routes';
import { createInventoryMinimumStockRouter } from '../modules/inventory-minimum-stocks/inventory-minimum-stock.routes';
import { createInventoryAssetSparePartRouter } from '../modules/inventory-asset-spare-parts/inventory-asset-spare-part.routes';
import { createInventoryWorkOrderMaterialUsageRouter } from '../modules/inventory-work-order-material-usages/inventory-wo-material-usage.routes';
import { createInventoryHkConsumableBindingRouter } from '../modules/inventory-housekeeping-consumable-bindings/inventory-hk-consumable-binding.routes';
import { createInventoryMaterialReservationRouter } from '../modules/inventory-material-reservations/inventory-material-reservation.routes';
import { createPurchaseRequestRouter } from '../modules/purchase-requests/purchase-request.routes';
import { createMaterialRequestRouter } from '../modules/material-requests/material-request.routes';
import { createServiceRequestRouter } from '../modules/service-requests/service-request.routes';
import { createServiceChargeReadinessRouter } from '../modules/service-charge-readiness/service-charge-readiness.routes';
import { createProcurementApprovalRouter } from '../modules/procurement-approvals/procurement-approval.routes';
import { createVendorSelectionRouter } from '../modules/vendor-selection-readiness/vendor-selection.routes';
import { createPOReadinessRouter } from '../modules/purchase-order-readiness/purchase-order-readiness.routes';
import { createRfqRouter } from '../modules/rfqs/rfq.routes';
import { createRfqVendorInvitationRouter } from '../modules/rfq-vendor-invitations/rfq-vendor-invitation.routes';
import { createVendorQuotationRouter } from '../modules/vendor-quotations/vendor-quotation.routes';
import { createRfqComparisonRouter } from '../modules/rfq-comparisons/rfq-comparison.routes';
import { createRfqRecommendationRouter } from '../modules/rfq-recommendations/rfq-recommendation.routes';
import { createRfqPoConversionRouter } from '../modules/rfq-po-conversions/rfq-po-conversion.routes';
import { createPriceCatalogEntryRouter } from '../modules/price-catalog-entries/price-catalog-entry.routes';
import { createServiceCatalogRouter } from '../modules/service-catalog/service-catalog.routes';
import { createEsgMetricDefinitionRouter } from '../modules/esg-metric-definitions/esg-metric-definition.routes';
import { createEsgWasteRecordRouter } from '../modules/esg-waste-records/esg-waste-record.routes';
import { createEsgMetricValueRouter } from '../modules/esg-metric-values/esg-metric-value.routes';
import { createEsgReadModelsRouter } from '../modules/esg-read-models/esg-read-models.routes';
import { createPurchaseOrderRouter } from '../modules/purchase-orders/purchase-order.routes';
import { createWorkContractRouter } from '../modules/work-contracts/work-contract.routes';
import { createPaymentReceiptRouter } from '../modules/payment-receipts/payment-receipt.routes';
import { createReceivingRouter } from '../modules/receivings/receiving.routes';
import { createWOProcurementBindingRouter } from '../modules/work-order-procurement-bindings/work-order-procurement-binding.routes';
import { createUtilityMeterRouter } from '../modules/utility-meters/utility-meter.routes';
import { createUtilityTypeConfigurationRouter } from '../modules/utility-type-configurations/utility-type-configuration.routes';
import { createUtilityMeterHierarchyRouter } from '../modules/utility-meter-hierarchies/utility-meter-hierarchy.routes';
import { createUtilityMeterTenantRouter } from '../modules/utility-meter-tenants/utility-meter-tenant.routes';
import { createUtilityMeterReadingRouter } from '../modules/utility-meter-readings/utility-meter-reading.routes';
import { createUtilityMeterReadingEvidenceRouter } from '../modules/utility-meter-reading-evidence/utility-meter-reading-evidence.routes';
import { createUtilityMeterConsumptionRouter } from '../modules/utility-meter-consumptions/utility-meter-consumption.routes';
import { createUtilityUsageHistoryRouter } from '../modules/utility-usage-history/utility-usage-history.routes';
import { createUtilityCalculationRouter } from '../modules/utility-calculations/utility-calculation.routes';
import { createUtilityTariffRouter } from '../modules/utility-tariffs/utility-tariff.routes';
import { createBuildingUtilityReconciliationRouter } from '../modules/building-utility-reconciliations/building-utility-reconciliation.routes';
import { createUtilityReadingDueRouter } from '../modules/utility-reading-dues/utility-reading-due.routes';
import { createUtilityOcrCandidateRouter } from '../modules/utility-ocr-candidates/utility-ocr-candidate.routes';
import { createUtilityOperationalExceptionRouter } from '../modules/utility-operational-exceptions/utility-operational-exception.routes';
import { createUtilityAbnormalConsumptionRouter } from '../modules/utility-abnormal-consumptions/utility-abnormal-consumption.routes';
import { createUtilityVerificationRouter } from '../modules/utility-verification/utility-verification.routes';
import { createUtilityAggregationRouter } from '../modules/utility-aggregations/utility-aggregation.routes';
import { createUtilityBillRouter } from '../modules/utility-bills/utility-bill.routes';
import { createToiletInspectionRouter } from '../modules/toilet-inspections/toilet-inspection.routes';
import { createPublicAreaInspectionRouter } from '../modules/public-area-inspections/public-area-inspection.routes';
import { createSupervisorInspectionRouter } from '../modules/supervisor-inspections/supervisor-inspection.routes';
import { createHousekeepingFindingRouter } from '../modules/housekeeping-findings/housekeeping-finding.routes';
import { createHousekeepingEvidenceRouter } from '../modules/housekeeping-evidence/housekeeping-evidence.routes';
import { createConsumableReadinessRouter } from '../modules/consumable-readiness/consumable-readiness.routes';
import { createQualityAuditRouter } from '../modules/quality-audits/quality-audit.routes';
import { createHousekeepingComplaintRouter } from '../modules/housekeeping-complaints/housekeeping-complaint.routes';
import { createHousekeepingReportRouter } from '../modules/housekeeping-reports/housekeeping-report.routes';
import { createBuildingAssignmentRouter } from '../modules/building-assignments/building-assignment.routes';
import { createEngineeringDailyOperationsRouter } from '../modules/engineering-daily-operations/engineering-daily-operations.routes';
import { createInspectionBindingRouter } from '../modules/inspection-bindings/inspection-binding.routes';
import { createMeterReadingBindingRouter } from '../modules/meter-reading-bindings/meter-reading-binding.routes';
import { createLogSheetBindingRouter } from '../modules/log-sheet-bindings/log-sheet-binding.routes';
import { createEngineeringChecklistBindingRouter } from '../modules/engineering-checklist-bindings/engineering-checklist-binding.routes';
import { createBreakdownBindingRouter } from '../modules/breakdown-bindings/breakdown-binding.routes';
import { createMaintenanceBindingRouter } from '../modules/maintenance-bindings/maintenance-binding.routes';
import { createEngineeringFindingRouter } from '../modules/engineering-findings/engineering-finding.routes';
import { createEngineeringReportRouter } from '../modules/engineering-reports/engineering-report.routes';
import { createShiftHandoverRouter } from '../modules/shift-handovers/shift-handover.routes';
import { createSecurityPostRouter } from '../modules/security-posts/security-post.routes';
import { createPatrolRouteRouter } from '../modules/patrol-routes/patrol-route.routes';
import { createPatrolScheduleBindingRouter } from '../modules/patrol-schedule-bindings/patrol-schedule-binding.routes';
import { createPatrolExecutionRouter } from '../modules/patrol-executions/patrol-execution.routes';
import { createPatrolChecklistBindingRouter } from '../modules/patrol-checklist-bindings/patrol-checklist-binding.routes';
import { createSecurityDailyActivityRouter } from '../modules/security-daily-activity/security-daily-activity.routes';
import { createSecurityShiftHandoverBindingRouter } from '../modules/security-shift-handovers/security-shift-handover.routes';
import { createSecurityFindingRouter } from '../modules/security-findings/security-finding.routes';
import { createSecurityIncidentReadinessRouter } from '../modules/security-incident-readiness/security-incident-readiness.routes';
import { createSecurityVisitorBindingRouter } from '../modules/security-visitor-bindings/security-visitor-binding.routes';
import { createSecurityKeyRouter } from '../modules/security-keys/security-key.routes';
import { createSecurityLostFoundRouter } from '../modules/security-lost-found/security-lost-found.routes';
import { createSecurityReportRouter } from '../modules/security-reports/security-report.routes';
import { createSecurityLogbookRouter } from '../modules/security-logbook/security-logbook.routes';
import { createSecurityPatrolKpiRouter } from '../modules/security-patrol-kpi/security-patrol-kpi.routes';
import { createSecurityFindingIncidentKpiRouter } from '../modules/security-finding-incident-kpi/security-finding-incident-kpi.routes';
import { createWorkforceKpiRouter } from '../modules/workforce-kpi/workforce-kpi.routes';
import { createAttendanceRouter } from '../modules/attendance/attendance.routes';
import { createVendorTenantKpiRouter } from '../modules/vendor-tenant-kpi/vendor-tenant-kpi.routes';
import { createUtilityKpiRouter } from '../modules/utility-kpi/utility-kpi.routes';
import { createReportingExportRouter } from '../modules/reporting-export/reporting-export.routes';
import { createReportingArchiveRouter } from '../modules/reporting-archives/reporting-archive.routes';
import { createManagementReadScopeRouter } from '../modules/management-read-scope/management-read-scope.routes';
import { createManagementDailyOperationsRouter } from '../modules/management-daily-operations/management-daily-operations.routes';
import { createManagementWorkOrderSummaryRouter } from '../modules/management-work-order-summary/management-work-order-summary.routes';
import { createManagementPendingApprovalRouter } from '../modules/management-pending-approval/management-pending-approval.routes';
import { createManagementCriticalFindingsRouter } from '../modules/management-critical-findings/management-critical-findings.routes';
import { createManagementWorkforceSummaryRouter } from '../modules/management-workforce-summary/management-workforce-summary.routes';
import { createManagementVendorSummaryRouter } from '../modules/management-vendor-summary/management-vendor-summary.routes';
import { createManagementTenantServiceSummaryRouter } from '../modules/management-tenant-service-summary/management-tenant-service-summary.routes';
import { createManagementAssetRegistryComplianceRouter } from '../modules/management-asset-registry-compliance/management-asset-registry-compliance.routes';
import { createManagementAssetReliabilityWorkRouter } from '../modules/management-asset-reliability-work/management-asset-reliability-work.routes';
import { createManagementUtilitySummaryRouter } from '../modules/management-utility-summary/management-utility-summary.routes';
import { createManagementFinancialSummaryRouter } from '../modules/management-financial-summary/management-financial-summary.routes';
import { createManagementBuildingOperationalFinanceRouter } from '../modules/management-building-operational-finance/management-building-operational-finance.routes';
import { createManagementOperationalFinanceRouter } from '../modules/management-operational-finance/management-operational-finance.routes';
import { createManagementOperationalKpiRouter } from '../modules/management-operational-kpi/management-operational-kpi.routes';
import { createManagementBuildingPerformanceRouter } from '../modules/management-building-performance/management-building-performance.routes';
import { createManagementPortfolioOverviewRouter } from '../modules/management-portfolio-overview/management-portfolio-overview.routes';
import { createManagementOperationsCommandCenterRouter } from '../modules/management-operations-command-center/management-operations-command-center.routes';
import { createVisitorRouter } from '../modules/visitors/visitor.routes';
import { createVisitorInvitationRouter } from '../modules/visitor-invitations/visitor-invitation.routes';
import { createExpectedVisitorRouter } from '../modules/expected-visitors/expected-visitor.routes';
import { createWalkInVisitRouter } from '../modules/walk-in-visits/walk-in-visit.routes';
import { createVisitorPhotoRouter } from '../modules/visitor-photos/visitor-photo.routes';
import { createHostConfirmationRouter } from '../modules/host-confirmations/host-confirmation.routes';
import { createVisitCheckInRouter } from '../modules/visit-check-ins/visit-check-in.routes';
import { createVisitorPassRouter } from '../modules/visitor-passes/visitor-pass.routes';
import { createContractorVisitorRouter } from '../modules/contractor-visitors/contractor-visitor.routes';
import { createDeliveryCourierRouter } from '../modules/delivery-couriers/delivery-courier.routes';
import { createFrontDeskLogRouter } from '../modules/front-desk-log/front-desk-log.routes';
import { createEngineeringOverviewRouter } from '../modules/engineering-overview/engineering-overview.routes';
import { createBuildingConfigurationRouter } from '../modules/building-configurations/building-configuration.routes';
import { createBuildingRouter } from '../modules/buildings/building.routes';
import { createCampusRouter } from '../modules/campuses/campus.routes';
import { createClientConfigurationRouter } from '../modules/client-configurations/client-configuration.routes';
import { createClientRouter } from '../modules/clients/client.routes';
import { createSlaDefinitionRouter } from '../modules/sla-definitions';
import { createEvidenceRetentionPolicyRouter } from '../modules/evidence-retention-policies';
import { createAppliedSlaRouter } from '../modules/applied-slas';
import { createSlaEscalationPolicyRouter } from '../modules/sla-escalation-policies';
import { createSlaEscalationActionRouter } from '../modules/sla-escalation-actions';
import { createDepartmentRouter } from '../modules/departments/department.routes';
import { createEntitlementRouter } from '../modules/entitlements/entitlement.routes';
import { createEquipmentProfileRouter } from '../modules/equipment-profiles/equipment-profile.routes';
import { createExternalWorkforceRouter } from '../modules/external-workforce/external-workforce.routes';
import { createFloorRouter } from '../modules/floors/floor.routes';
// CR-BE-FX-01 PART 02 — governed FX Rate lifecycle and Client FX Policy.
import { createFxRateRouter } from '../modules/fx-rates/fx-rate.routes';
import { createFindingAssignmentRouter } from '../modules/finding-assignments/finding-assignment.routes';
import { createFindingClosureRouter } from '../modules/finding-closure/finding-closure.routes';
import { createFindingClassificationRouter } from '../modules/finding-classifications/finding-classification.routes';
import { createFindingHistoryRouter } from '../modules/finding-history/finding-history.routes';
import { createFindingReviewRouter } from '../modules/finding-reviews/finding-review.routes';
import { createFindingReworkRouter } from '../modules/finding-rework/finding-rework.routes';
import { createFindingSeverityRouter } from '../modules/finding-severities/finding-severity.routes';
import { createFindingRouter } from '../modules/findings/finding.routes';
import { createFormTemplateRouter } from '../modules/form-templates/form-template.routes';
import { createFormSectionRouter } from '../modules/form-sections/form-section.routes';
import { createFormTemplateVersionRouter } from '../modules/form-template-versions/form-template-version.routes';
import { createFormInstanceRouter } from '../modules/form-instances/form-instance.routes';
import { createFormConditionRouter } from '../modules/form-conditions/form-condition.routes';
import { createChecklistTemplateRouter } from '../modules/checklist-templates/checklist-template.routes';
import { createChecklistExecutionRouter } from '../modules/checklist-executions/checklist-execution.routes';
import { createUomRouter } from '../modules/uoms/uom.routes';
import { createEvidenceRequirementRouter } from '../modules/evidence-requirements/evidence-requirement.routes';
import { createEvidenceFileRouter } from '../modules/evidence/evidence-file.routes';
import { createEvidenceRouter } from '../modules/evidence/evidence.routes';
import { createReviewRouter } from '../modules/reviews/review.routes';
import { createScheduleRouter } from '../modules/schedules/schedule.routes';
import { createRecurrenceRouter } from '../modules/schedules/recurrence.routes';
import { createTaskRouter } from '../modules/tasks/task.routes';
import { createTaskAssignmentRouter } from '../modules/task-assignments/task-assignment.routes';
import { createTaskExecutionRouter } from '../modules/task-execution/task-execution.routes';
import { createOperationalEventRouter } from '../modules/operational-events/operational-event.routes';
import { createMobileAssignmentRouter } from '../modules/mobile-assignments/mobile-assignment.routes';
import { createMobileChecklistRouter } from '../modules/mobile-checklist/mobile-checklist.routes';
import { createMobileFormInstanceRouter } from '../modules/mobile-form-instances/mobile-form-instance.routes';
import { createMobileEvidenceRouter } from '../modules/evidence/mobile-evidence.routes';
import { createMobileQrResolutionRouter } from '../modules/mobile-qr-resolution/mobile-qr.routes';
import { createMobileSyncRouter } from '../modules/mobile-sync/mobile-sync.routes';
import { createMobileVerificationRouter } from '../modules/mobile-verification/mobile-verification.routes';
import { createPushTokenRouter } from '../modules/push-tokens/push-token.routes';
import { createAppVersionRouter } from '../modules/app-versions/app-version.routes';
import { createMobileDiagnosticsRouter } from '../modules/mobile-diagnostics/mobile-diagnostics.routes';
import { createMobileCurrentShiftRouter } from '../modules/mobile-current-shift/mobile-current-shift.routes';
import { createMobileMyTeamRouter } from '../modules/mobile-my-team/mobile-my-team.routes';
import { createNotificationRouter } from '../modules/notifications/notification.routes';
import { createNotificationTemplateRouter } from '../modules/notification-templates/notification-template.routes';
import { createNotificationSubscriptionRouter } from '../modules/notification-subscriptions/notification-subscription.routes';
import { createNotificationReminderRouter } from '../modules/notification-reminders/notification-reminder.routes';
import { createNotificationEscalationRouter } from '../modules/notification-escalations/notification-escalation.routes';
import { createSecureLinkRouter } from '../modules/notification-secure-links/secure-link.routes';
import { createNotificationHistoryRouter } from '../modules/notification-history/notification-history.routes';
import { createIntegrationWebhookEndpointRouter } from '../modules/integration-webhook-endpoints/integration-webhook-endpoint.routes';
import { createIntegrationWebhookDeliveryRouter } from '../modules/integration-webhook-deliveries/integration-webhook-delivery.routes';
import { createFunctionalLocationRouter } from '../modules/functional-locations/functional-location.routes';
import { createFeatureEntitlementConfigurationRouter } from '../modules/feature-entitlement-configurations/feature-entitlement-configuration.routes';
import { createInvitationRouter } from '../modules/invitations/invitation.routes';
import { createLicenseRouter } from '../modules/licenses/license.routes';
import { createModuleConfigurationRouter } from '../modules/module-configurations/module-configuration.routes';
import { createNavigationRegistryRouter } from '../modules/navigation-registry/navigation-registry.routes';
import { createWorkspaceRegistryRouter } from '../modules/workspace-registry/workspace-registry.routes';
import { createDashboardConfigurationRouter } from '../modules/dashboard-configurations/dashboard-configuration.routes';
import { createFormAdministrationRouter } from '../modules/form-administration/form-administration.routes';
import { createChecklistAdministrationRouter } from '../modules/checklist-administration/checklist-administration.routes';
import { createOperationalSettingRouter } from '../modules/operational-settings/operational-setting.routes';
import { createOrganizationPresentationRouter } from '../modules/organization-presentation/organization-presentation.routes';
import { createCmsContentRouter } from '../modules/cms-content/cms-content.routes';
import { createBrandingRouter } from '../modules/branding/branding.routes';
import { createConfigurationVersionRouter } from '../modules/configuration-versions/configuration-version.routes';
import { createConfigurationPreviewRouter } from '../modules/configuration-preview/configuration-preview.routes';
import { createConfigurationAuditRouter } from '../modules/configuration-audit/configuration-audit.routes';
import { createModuleRouter } from '../modules/modules/module.routes';
import { createOrganizationRouter } from '../modules/organizations/organization.routes';
import { createPermissionRouter } from '../modules/permissions/permission.routes';
import { createPositionRouter } from '../modules/positions/position.routes';
import { createPropertyRouter } from '../modules/properties/property.routes';
import { createRoleRouter } from '../modules/roles/role.routes';
import { createRoomRouter } from '../modules/rooms/room.routes';
import { createRoomTypeRouter } from '../modules/room-types/room-type.routes';
import { createShiftRouter } from '../modules/shifts/shift.routes';
import { createSourceFormRouter } from '../modules/source-forms/source-form.routes';
import { createSpaceRouter } from '../modules/spaces/space.routes';
import { createSkillRouter } from '../modules/skills/skill.routes';
import { createStructureContextRouter } from '../modules/structure-context/structure-context.routes';
import { createWorkforceBuildingAssignmentRouter } from '../modules/workforce-building-assignments/workforce-building-assignment.routes';
import { createWorkforceReportingLineRouter } from '../modules/workforce-reporting-lines/workforce-reporting-line.routes';
import { createWorkforceReportingRouter } from '../modules/workforce-reporting/workforce-reporting.routes';
import { createWorkforceShiftRouter } from '../modules/workforce-shifts/workforce-shift.routes';
import { createWorkforceSkillRouter } from '../modules/workforce-skills/workforce-skill.routes';
import { createTeamRouter } from '../modules/teams/team.routes';
import { createSubscriptionRouter } from '../modules/subscriptions/subscription.routes';
import { createUserRouter } from '../modules/users/user.routes';
import { createVendorBuildingRouter } from '../modules/vendor-buildings/vendor-building.routes';
import { createVendorCapabilityRouter } from '../modules/vendor-capabilities/vendor-capability.routes';
import { createVendorComplianceDocumentRouter } from '../modules/vendor-compliance-documents/vendor-compliance-document.routes';
import { createVendorLicenseRouter } from '../modules/vendor-licenses/vendor-license.routes';
import { createVendorWorkforceRouter } from '../modules/vendor-workforce/vendor-workforce.routes';
import { createVendorAssignmentRouter } from '../modules/vendor-assignments/vendor-assignment.routes';
import { createVendorChecklistBindingRouter } from '../modules/vendor-checklist-bindings/vendor-checklist-binding.routes';
import { createWorkPermitReadinessRouter } from '../modules/work-permit-readiness/work-permit-readiness.routes';
import { createVendorWorkEvidenceRouter } from '../modules/vendor-work-evidence/vendor-work-evidence.routes';
import { createVendorCompletionReportRouter } from '../modules/vendor-completion-reports/vendor-completion-report.routes';
import { createVendorServiceReportRouter } from '../modules/vendor-service-reports/vendor-service-report.routes';
import { createVendorServiceCostRouter } from '../modules/vendor-service-costs/vendor-service-cost.routes';
import { createVendorInvoiceRouter } from '../modules/vendor-invoices/vendor-invoice.routes';
import { createVendorBastRouter } from '../modules/vendor-bast-bindings/vendor-bast-binding.routes';
import { createVendorVerificationRouter } from '../modules/vendor-verification/vendor-verification.routes';
import { createVendorReworkRouter } from '../modules/vendor-rework/vendor-rework.routes';
import { createVendorWorkHistoryRouter } from '../modules/vendor-work-history/vendor-work-history.routes';
import { createVendorWorkRouter } from '../modules/vendor-work/vendor-work.routes';
import { createVendorCategoryRouter } from '../modules/vendor-categories/vendor-category.routes';
import { createVendorPicRouter } from '../modules/vendor-pics/vendor-pic.routes';
import { createVendorRouter } from '../modules/vendors/vendor.routes';
import { createTenantCompanyRouter } from '../modules/tenant-companies/tenant-company.routes';
import { createTenantInvoiceRouter } from '../modules/tenant-invoices/tenant-invoice.routes';
import { createTenantPicRouter } from '../modules/tenant-pics/tenant-pic.routes';
import { createTenantSpaceRouter } from '../modules/tenant-spaces/tenant-space.routes';
import { createTenantBuildingContextRouter } from '../modules/tenant-building-contexts/tenant-building-context.routes';
import { createTenantServiceRequestRouter } from '../modules/tenant-service-requests/tenant-service-request.routes';
import { createTenantComplaintRouter } from '../modules/tenant-complaints/tenant-complaint.routes';
import { createTenantUtilityRequestRouter } from '../modules/tenant-utility-requests/tenant-utility-request.routes';
import { createTenantApprovalRouter } from '../modules/tenant-approvals/tenant-approval.routes';
import { createTenantContractorRouter } from '../modules/tenant-contractors/tenant-contractor.routes';
import { createTenantDocumentRouter } from '../modules/tenant-documents/tenant-document.routes';
import { createTenantCommunicationRouter } from '../modules/tenant-communications/tenant-communication.routes';
import { createTenantChargeRouter } from '../modules/tenant-charges/tenant-charge.routes';
import { createWorkforceRouter } from '../modules/workforce/workforce.routes';
import { createWorkRequestRouter } from '../modules/work-requests/work-request.routes';
import { createWorkOrderRouter } from '../modules/work-orders/work-order.routes';
import { createWorkOrderAssignmentRouter } from '../modules/work-order-assignments/work-order-assignment.routes';
import { createWorkOrderActionRouter } from '../modules/work-order-actions/work-order-action.routes';
import { createWorkOrderEvidenceRouter } from '../modules/work-order-evidence/work-order-evidence.routes';
import { createWorkOrderVerificationRouter } from '../modules/work-order-verification/work-order-verification.routes';
import { createWorkOrderHistoryRouter } from '../modules/work-order-history/work-order-history.routes';
import { createHealthRouter } from './health.routes';

export function createApiRouter(): Router {
  const router = Router();
  router.use(createSlaDefinitionRouter());
  router.use(createAppliedSlaRouter());
  router.use(createSlaEscalationPolicyRouter());
  router.use(createSlaEscalationActionRouter());
  router.use(createHealthRouter());
  router.use(createUserRouter());
  router.use(createAuthRouter());
  router.use(createRoleRouter());
  router.use(createPermissionRouter());
  router.use(createClientRouter());
  router.use(createClientConfigurationRouter());
  router.use(createOrganizationRouter());
  router.use(createDepartmentRouter());
  router.use(createTeamRouter());
  router.use(createPositionRouter());
  router.use(createWorkforceRouter());
  router.use(createWorkforceReportingRouter());
  router.use(createSkillRouter());
  router.use(createWorkforceSkillRouter());
  router.use(createShiftRouter());
  router.use(createWorkforceShiftRouter());
  router.use(createWorkforceReportingLineRouter());
  router.use(createWorkforceBuildingAssignmentRouter());
  router.use(createExternalWorkforceRouter());
  router.use(createSubscriptionRouter());
  router.use(createLicenseRouter());
  router.use(createModuleRouter());
  router.use(createModuleConfigurationRouter());
  router.use(createFeatureEntitlementConfigurationRouter());
  router.use(createNavigationRegistryRouter());
  router.use(createWorkspaceRegistryRouter());
  router.use(createDashboardConfigurationRouter());
  router.use(createFormAdministrationRouter());
  router.use(createChecklistAdministrationRouter());
  router.use(createOperationalSettingRouter());
  router.use(createOrganizationPresentationRouter());
  router.use(createCmsContentRouter());
  router.use(createBrandingRouter());
  router.use(createConfigurationVersionRouter());
  router.use(createConfigurationPreviewRouter());
  router.use(createConfigurationAuditRouter());
  router.use(createEntitlementRouter());
  router.use(createPropertyRouter());
  router.use(createBuildingRouter());
  router.use(createBuildingConfigurationRouter());
  router.use(createCampusRouter());
  router.use(createFloorRouter());
  router.use(createAreaRouter());
  router.use(createRoomRouter());
  router.use(createRoomTypeRouter());
  router.use(createSpaceRouter());
  router.use(createFunctionalLocationRouter());
  router.use(createAssetRouter());
  router.use(createAssetCategoryRouter());
  router.use(createAssetTypeRouter());
  router.use(createEquipmentProfileRouter());
  router.use(createAssetWarrantyRouter());
  router.use(createAssetCertificationRouter());
  router.use(createAssetIdentifierRouter());
  router.use(createAssetHistoryRouter());
  router.use(createStructureContextRouter());
  router.use(createSourceFormRouter());
  router.use(createFormTemplateRouter());
  router.use(createFormSectionRouter());
  router.use(createFormTemplateVersionRouter());
  router.use(createFormInstanceRouter());
  router.use(createFormConditionRouter());
  router.use(createChecklistTemplateRouter());
  router.use(createChecklistExecutionRouter());
  router.use(createUomRouter());
  router.use(createEvidenceRequirementRouter());
  router.use(createEvidenceFileRouter());
  router.use(createEvidenceRouter());
  router.use(createEvidenceRetentionPolicyRouter());
  router.use(createReviewRouter());
  router.use(createScheduleRouter());
  router.use(createRecurrenceRouter());
  router.use(createTaskRouter());
  router.use(createTaskAssignmentRouter());
  router.use(createTaskExecutionRouter());
  router.use(createOperationalEventRouter());
  router.use(createMobileAssignmentRouter());
  router.use(createMobileChecklistRouter());
  router.use(createMobileFormInstanceRouter());
  router.use(createMobileEvidenceRouter());
  router.use(createMobileQrResolutionRouter());
  router.use(createMobileSyncRouter());
  router.use(createMobileVerificationRouter());
  router.use(createPushTokenRouter());
  router.use(createAppVersionRouter());
  router.use(createMobileDiagnosticsRouter());
  router.use(createMobileCurrentShiftRouter());
  router.use(createMobileMyTeamRouter());
  router.use(createNotificationRouter());
  router.use(createNotificationTemplateRouter());
  router.use(createNotificationSubscriptionRouter());
  router.use(createIntegrationWebhookEndpointRouter());
  router.use(createIntegrationWebhookDeliveryRouter());
  router.use(createNotificationReminderRouter());
  router.use(createNotificationEscalationRouter());
  router.use(createSecureLinkRouter());
  router.use(createNotificationHistoryRouter());
  router.use(createVendorRouter());
  router.use(createTenantCompanyRouter());
  router.use(createTenantPicRouter());
  router.use(createTenantSpaceRouter());
  router.use(createTenantBuildingContextRouter());
  router.use(createTenantServiceRequestRouter());
  router.use(createTenantComplaintRouter());
  router.use(createTenantUtilityRequestRouter());
  router.use(createTenantApprovalRouter());
  router.use(createTenantContractorRouter());
  router.use(createTenantDocumentRouter());
  router.use(createTenantCommunicationRouter());
  router.use(createTenantChargeRouter());
  router.use(createVendorCategoryRouter());
  router.use(createVendorPicRouter());
  router.use(createVendorBuildingRouter());
  router.use(createVendorCapabilityRouter());
  router.use(createVendorWorkforceRouter());
  router.use(createVendorComplianceDocumentRouter());
  router.use(createVendorLicenseRouter());
  router.use(createVendorAssignmentRouter());
  router.use(createVendorWorkRouter());
  router.use(createVendorChecklistBindingRouter());
  router.use(createWorkPermitReadinessRouter());
  router.use(createVendorWorkEvidenceRouter());
  router.use(createVendorCompletionReportRouter());
  router.use(createVendorServiceReportRouter());
  router.use(createVendorBastRouter());
  router.use(createVendorVerificationRouter());
  router.use(createVendorReworkRouter());
  router.use(createVendorWorkHistoryRouter());
  router.use(createBuildingAssignmentRouter());
  router.use(createEngineeringDailyOperationsRouter());
  router.use(createInspectionBindingRouter());
  router.use(createMeterReadingBindingRouter());
  router.use(createLogSheetBindingRouter());
  router.use(createEngineeringChecklistBindingRouter());
  router.use(createBreakdownBindingRouter());
  router.use(createMaintenanceBindingRouter());
  router.use(createEngineeringFindingRouter());
  router.use(createEngineeringReportRouter());
  router.use(createShiftHandoverRouter());
  router.use(createSecurityPostRouter());
  router.use(createPatrolRouteRouter());
  router.use(createPatrolScheduleBindingRouter());
  router.use(createPatrolExecutionRouter());
  router.use(createPatrolChecklistBindingRouter());
  router.use(createSecurityDailyActivityRouter());
  router.use(createSecurityShiftHandoverBindingRouter());
  router.use(createSecurityFindingRouter());
  router.use(createSecurityIncidentReadinessRouter());
  router.use(createSecurityVisitorBindingRouter());
  router.use(createSecurityKeyRouter());
  router.use(createSecurityLostFoundRouter());
  router.use(createSecurityReportRouter());
  // CR-BE-MOB-05 PART 03 — Security operational logbook.
  router.use(createSecurityLogbookRouter());
  router.use(createSecurityPatrolKpiRouter());
  router.use(createSecurityFindingIncidentKpiRouter());
  router.use(createWorkforceKpiRouter());
  // CR-BE-MOB-05 PART 02 — Workforce attendance self-service (clock-in/out).
  router.use(createAttendanceRouter());
  router.use(createVendorTenantKpiRouter());
  router.use(createUtilityKpiRouter());
  router.use(createReportingExportRouter());
  router.use(createReportingArchiveRouter());
  router.use(createManagementReadScopeRouter());
  router.use(createManagementDailyOperationsRouter());
  router.use(createManagementWorkOrderSummaryRouter());
  router.use(createManagementPendingApprovalRouter());
  router.use(createManagementCriticalFindingsRouter());
  router.use(createManagementWorkforceSummaryRouter());
  router.use(createManagementVendorSummaryRouter());
  router.use(createManagementTenantServiceSummaryRouter());
  router.use(createManagementAssetRegistryComplianceRouter());
  router.use(createManagementAssetReliabilityWorkRouter());
  router.use(createManagementUtilitySummaryRouter());
  router.use(createManagementFinancialSummaryRouter());
  router.use(createManagementBuildingOperationalFinanceRouter());
  router.use(createManagementOperationalFinanceRouter());
  router.use(createManagementOperationalKpiRouter());
  router.use(createManagementBuildingPerformanceRouter());
  router.use(createManagementPortfolioOverviewRouter());
  router.use(createManagementOperationsCommandCenterRouter());
  router.use(createVisitorRouter());
  router.use(createVisitorInvitationRouter());
  router.use(createExpectedVisitorRouter());
  router.use(createWalkInVisitRouter());
  router.use(createVisitorPhotoRouter());
  router.use(createHostConfirmationRouter());
  router.use(createVisitCheckInRouter());
  router.use(createVisitorPassRouter());
  router.use(createContractorVisitorRouter());
  router.use(createDeliveryCourierRouter());
  router.use(createFrontDeskLogRouter());
  router.use(createEngineeringOverviewRouter());
  router.use(createDocumentRouter());
  router.use(createDocumentVersionRouter());
  router.use(createDocumentExpiryRouter());
  router.use(createDocumentApprovalRouter());
  router.use(createWorkCompletionDocumentRouter());
  router.use(createBastDocumentRouter());
  router.use(createHandoverDocumentRouter());
  router.use(createAcceptanceSignOffRouter());
  router.use(createSupportingDocumentRouter());
  router.use(createInvitationRouter());
  router.use(createAuditRouter());
  router.use(createWorkRequestRouter());
  router.use(createWorkOrderRouter());
  router.use(createWorkOrderAssignmentRouter());
  router.use(createWorkOrderActionRouter());
  router.use(createWorkOrderEvidenceRouter());
  router.use(createWorkOrderVerificationRouter());
  router.use(createWorkOrderHistoryRouter());
  router.use(createFindingClassificationRouter());
  router.use(createFindingSeverityRouter());
  router.use(createFindingRouter());
  router.use(createFindingAssignmentRouter());
  router.use(createFindingReviewRouter());
  router.use(createFindingReworkRouter());
  router.use(createFindingClosureRouter());
  router.use(createFindingHistoryRouter());
  router.use(createCleaningAreaRouter());
  router.use(createCleaningScheduleBindingRouter());
  router.use(createDailyCleaningRouter());
  router.use(createCleaningAssignmentRouter());
  router.use(createInventoryItemRouter());
  router.use(createInventoryWarehouseRouter());
  router.use(createInventoryStockBalanceRouter());
  router.use(createInventoryStockMovementRouter());
  router.use(createInventoryStockTransferRouter());
  router.use(createInventoryStockAdjustmentRouter());
  router.use(createInventoryMinimumStockRouter());
  router.use(createInventoryAssetSparePartRouter());
  router.use(createInventoryWorkOrderMaterialUsageRouter());
  router.use(createInventoryHkConsumableBindingRouter());
  router.use(createInventoryMaterialReservationRouter());
  router.use(createPurchaseRequestRouter());
  router.use(createMaterialRequestRouter());
  router.use(createServiceRequestRouter());
  router.use(createProcurementApprovalRouter());
  router.use(createVendorSelectionRouter());
  router.use(createPOReadinessRouter());
  router.use(createRfqRouter());
  router.use(createRfqVendorInvitationRouter());
  router.use(createVendorQuotationRouter());
  router.use(createRfqComparisonRouter());
  router.use(createRfqRecommendationRouter());
  router.use(createRfqPoConversionRouter());
  // CR-BE-PRICE-01 PART 01 — Price Authority Foundation (internal reference
  // prices; never exposed to RFQ Vendor sessions).
  router.use(createPriceCatalogEntryRouter());
  // CR-BE-SVC-01 PART 01 — Service Catalog Foundation (governed Service master
  // identity; Client-scoped, identity only — no demand/price/lineage behavior).
  router.use(createServiceCatalogRouter());
  // CR-BE-ESG-01 PART 01 — ESG Metric Definition Foundation (governed ESG
  // metric vocabulary; Client-scoped, identity only — no values/waste/baseline).
  router.use(createEsgMetricDefinitionRouter());
  // CR-BE-ESG-01 PART 02 — Waste Operational Records (Building-scoped waste
  // measurement; no aggregation/recycling KPI/baselines/targets).
  router.use(createEsgWasteRecordRouter());
  // CR-BE-ESG-01 PART 03 — Metric Values & Periods (Building-scoped periodized
  // values, unique period authority, provenance, no auto aggregation).
  router.use(createEsgMetricValueRouter());
  router.use(createEsgReadModelsRouter());
  // CR-BE-R2P-01 PART 01 — Purchase Order commitment (after PO Readiness,
  // which remains its precondition and sole readiness authority).
  router.use(createPurchaseOrderRouter());
  // CR-BE-R2P-01 PART 04 — SPK / Work Contract (after the PO, which must be
  // ISSUED before an execution mandate can be raised against it).
  router.use(createWorkContractRouter());
  router.use(createReceivingRouter());
  router.use(createWOProcurementBindingRouter());
  router.use(createToiletInspectionRouter());
  router.use(createPublicAreaInspectionRouter());
  router.use(createSupervisorInspectionRouter());
  router.use(createHousekeepingFindingRouter());
  router.use(createHousekeepingEvidenceRouter());
  router.use(createConsumableReadinessRouter());
  router.use(createQualityAuditRouter());
  router.use(createHousekeepingComplaintRouter());
  router.use(createHousekeepingReportRouter());
  router.use(createUtilityMeterRouter());
  router.use(createUtilityTypeConfigurationRouter());
  router.use(createUtilityMeterHierarchyRouter());
  router.use(createUtilityMeterTenantRouter());
  router.use(createUtilityMeterReadingRouter());
  router.use(createUtilityMeterReadingEvidenceRouter());
  router.use(createUtilityMeterConsumptionRouter());
  router.use(createUtilityUsageHistoryRouter());
  router.use(createUtilityTariffRouter());
  router.use(createBuildingUtilityReconciliationRouter());
  router.use(createUtilityReadingDueRouter());
  router.use(createUtilityOcrCandidateRouter());
  router.use(createUtilityOperationalExceptionRouter());
  router.use(createUtilityCalculationRouter());
  router.use(createUtilityAbnormalConsumptionRouter());
  router.use(createUtilityVerificationRouter());
  router.use(createUtilityAggregationRouter());
  router.use(createUtilityBillRouter());
  router.use(createServiceChargeReadinessRouter());
  router.use(createTenantInvoiceRouter());
  router.use(createInvoicePaymentStatusRouter());
  router.use(createPaymentReceiptRouter());
  router.use(createVendorServiceCostRouter());
  router.use(createVendorInvoiceRouter());
  router.use(createBasicExpenseRouter());
  router.use(createBasicFinancialReportingRouter());
  router.use(createOperationalFinanceRouter());
  router.use(createContractorContextRouter());
  router.use(createPermitRouter());
  router.use(createPermitApplicationRouter());
  router.use(createPermitWorkContextRouter());
  router.use(createPermitSafetyRequirementRouter());
  router.use(createPermitApprovalRouter());
  router.use(createPermitValidityRouter());
  router.use(createPermitWorkerRouter());
  router.use(createPermitEquipmentRouter());
  router.use(createPermitEvidenceRouter());
  router.use(createPermitWorkLifecycleRouter());
  router.use(createIncidentRouter());
  router.use(createOperationalIncidentRouter());
  router.use(createAssetFailureRouter());
  router.use(createFindingEscalationRouter());
  router.use(createImmediateActionRouter());
  router.use(createInvestigationReadinessRouter());
  router.use(createCorrectiveActionRouter());
  router.use(createCorrectiveActionResponsibilityRouter());
  router.use(createCorrectiveActionVerificationRouter());
  router.use(createIncidentClosureRouter());
  // CR-BE-FX-01 PART 02 — FX Rate lifecycle + Client FX Policy governance.
  router.use(createFxRateRouter());
  return router;
}
