import { AppError } from '../../shared/errors'; import { isValidUuid } from '../clients'; import { isSourceFormStatus,isSourceFormType,type CreateSourceFormInput,type UpdateSourceFormInput } from './source-form.types';
type Detail={field:string;message:string};const CODE=/^[A-Z][A-Z0-9_-]*$/; const object=(v:unknown):v is Record<string,unknown>=>typeof v==='object'&&v!==null&&!Array.isArray(v);
export const normalizeSourceFormCode=(v:string)=>v.trim().toUpperCase();
function uuid(raw:string,field:string){const v=raw.trim();if(!isValidUuid(v))throw AppError.validation('Request validation failed.',[{field,message:`${field} must be a valid UUID.`}]);return v.toLowerCase()}
export const parseSourceFormIdParam=(v:string)=>uuid(v,'sourceFormId'); export const parseSourceFormClientIdParam=(v:string)=>uuid(v,'clientId');
function string(v:unknown,field:string,max:number,details:Detail[],required=false){if(v===undefined&&!required)return undefined;if(typeof v!=='string'||(required&&v.trim()==='')){details.push({field,message:`${field} is required.`});return undefined}const x=v.trim();if(x.length>max){details.push({field,message:`${field} must be at most ${max} characters.`});return undefined}return x}
function type(v:unknown,details:Detail[]){if(!isSourceFormType(v)){details.push({field:'sourceType',message:'sourceType must be one of: INTERNAL, VENDOR, EXTERNAL_REFERENCE.'});return undefined}return v}
function status(v:unknown,details:Detail[]){if(v===undefined)return undefined;if(!isSourceFormStatus(v)){details.push({field:'status',message:'status must be one of: ACTIVE, INACTIVE.'});return undefined}return v}
export function parseCreateSourceFormBody(body:unknown):Omit<CreateSourceFormInput,'clientId'>{if(!object(body))throw AppError.validation('Request validation failed.',[{field:'body',message:'Request body must be a JSON object.'}]);const d:Detail[]=[];const raw=string(body.code,'code',64,d,true);const code=raw&&CODE.test(normalizeSourceFormCode(raw))?normalizeSourceFormCode(raw):(raw?(d.push({field:'code',message:'code must start with a letter and contain only letters, digits, hyphens, and underscores.'}),undefined):undefined);const name=string(body.name,'name',160,d,true);const sourceType=type(body.sourceType,d);const sourceReference=string(body.sourceReference,'sourceReference',512,d);const description=string(body.description,'description',2048,d);const s=status(body.status,d);if(d.length||!code||!name||!sourceType)throw AppError.validation('Request validation failed.',d);return {code,name,sourceType,...(sourceReference===undefined?{}:{sourceReference}),...(description===undefined?{}:{description}),...(s===undefined?{}:{status:s})}}
export function parseUpdateSourceFormBody(body:unknown):UpdateSourceFormInput{if(!object(body))throw AppError.validation('Request validation failed.',[{field:'body',message:'Request body must be a JSON object.'}]);if(body.clientId!==undefined||body.code!==undefined)throw AppError.validation('Request validation failed.',[{field:body.clientId!==undefined?'clientId':'code',message:'This field is immutable and cannot be updated.'}]);const d:Detail[]=[];const name=body.name===undefined?undefined:string(body.name,'name',160,d,true);const sourceType=body.sourceType===undefined?undefined:type(body.sourceType,d);const sourceReference=body.sourceReference===null?null:body.sourceReference===undefined?undefined:string(body.sourceReference,'sourceReference',512,d);const description=body.description===null?null:body.description===undefined?undefined:string(body.description,'description',2048,d);const s=status(body.status,d);if(d.length)throw AppError.validation('Request validation failed.',d);return {...(name===undefined?{}:{name}),...(sourceType===undefined?{}:{sourceType}),...(sourceReference===undefined?{}:{sourceReference}),...(description===undefined?{}:{description}),...(s===undefined?{}:{status:s})}}
