import assert from'node:assert/strict';import{randomUUID}from'node:crypto';import{after,before,describe,it,type TestContext}from'node:test';import type{Pool}from'pg';import type{DatabaseConfig}from'../src/config';import{closePool,initDatabase,migrateUp}from'../src/database';import{buildingAssignmentService}from'../src/modules/building-assignments';import{buildingService}from'../src/modules/buildings';import{clientMonetaryContextService}from'../src/modules/client-monetary-contexts';import{clientService}from'../src/modules/clients';import{currencyService}from'../src/modules/currencies';import{propertyService}from'../src/modules/properties';import{purchaseRequestService}from'../src/modules/purchase-requests';import{vendorBuildingService}from'../src/modules/vendor-buildings';import{vendorService}from'../src/modules/vendors';import{createAdminUser}from'./helpers/access';import{api}from'./helpers/http';import{ensureTestDatabase}from'./helpers/postgres';
/** CR-BE-CUR-02 PART 01 — command-time currency for Vendor / Service Costs and Basic Expenses. */
let database:DatabaseConfig|null=null,pool:Pool|null=null,token='',userId='';const suffix=()=>randomUUID().slice(0,8).toUpperCase(),auth=()=>({Authorization:`Bearer ${token}`});
before(async()=>{const db=await ensureTestDatabase();if(!db)return;pool=await initDatabase(db);await migrateUp(pool);await pool.query(`TRUNCATE basic_expense_history,basic_expenses,vendor_service_cost_history,vendor_service_costs,service_requests,purchase_requests,vendor_works,vendor_assignments,work_orders,work_requests,vendor_building_relationships,vendors,buildings,properties,users,roles,permissions,clients CASCADE`);const a=await createAdminUser();token=a.token;userId=a.userId;database=db});
after(async()=>{if(pool)await closePool(pool);pool=null;database=null});
function ready(t:TestContext){if(!database||!pool){t.skip('test database unavailable');return false}return true}
async function structure(codes:string[]=['IDR','USD','JPY']){const client=await clientService.createClient({code:`C_${suffix()}`,name:'Client'}),property=await propertyService.createProperty({clientId:client.id,code:`P_${suffix()}`,name:'Property'}),building=await buildingService.createBuilding({propertyId:property.id,code:`B_${suffix()}`,name:'Building'});await buildingAssignmentService.createAssignment(userId,{buildingId:building.id});await clientMonetaryContextService.setClientMonetaryContext({clientId:client.id,baseCurrencyCode:'IDR',defaultTransactionCurrencyCode:'IDR',allowedCurrencyCodes:codes},userId);return{client,building}}
async function serviceVendor(f:{client:{id:string};building:{id:string}}){const vendor=await vendorService.createVendor({clientId:f.client.id,vendorCode:`V_${suffix()}`,vendorName:'Vendor'});await vendorBuildingService.assignBuildingToVendor({vendorId:vendor.id,buildingId:f.building.id});const pr=await purchaseRequestService.createPurchaseRequest({clientId:f.client.id,buildingId:f.building.id,requestNumber:`PR_${suffix()}`,requestType:'SERVICE',title:'Service purchase',requestedByUserId:userId}),r=await api().post(`/api/v1/purchase-requests/${pr.id}/service-requests`).set(auth()).send({serviceType:'CLEANING',title:'Cleaning service',vendorId:vendor.id});assert.equal(r.status,201,JSON.stringify(r.body));return{vendor,service:r.body.data}}
function costBody(f:{building:{id:string}},serviceId:string,extra:Record<string,unknown>={}){return{buildingId:f.building.id,contextType:'SERVICE_REQUEST',contextId:serviceId,costAmount:150,costDate:'2026-08-15',costType:'SERVICE_FEE',costCategory:'OPERATIONS',currencyCode:'USD',...extra}}
function expenseBody(f:{building:{id:string}},extra:Record<string,unknown>={}){return{buildingId:f.building.id,expenseNumber:`EXP-${suffix()}`,expenseCategory:'OPERATIONS',description:'Operational expense',amount:150,currencyCode:'USD',expenseDate:'2026-08-15',...extra}}
const createCost=(vendorId:string,body:object)=>api().post(`/api/v1/vendors/${vendorId}/costs`).set(auth()).send(body);
const createExpense=(body:object)=>api().post('/api/v1/basic-expenses').set(auth()).send(body);
async function legacyCost(f:{client:{id:string};building:{id:string}}){const s=await serviceVendor(f),id=randomUUID();await pool!.query(`INSERT INTO vendor_service_costs(id,client_id,building_id,vendor_id,context_type,service_request_id,cost_amount,cost_date,cost_type,cost_category,status,created_by_user_id)VALUES($1,$2,$3,$4,'SERVICE_REQUEST',$5,100,'2026-08-10','SERVICE_FEE','OPERATIONS','DRAFT',$6)`,[id,f.client.id,f.building.id,s.vendor.id,s.service.id,userId]);return id}
async function legacyExpense(f:{client:{id:string};building:{id:string}}){const id=randomUUID();await pool!.query(`INSERT INTO basic_expenses(id,client_id,building_id,expense_number,expense_category,description,amount,expense_date,status,created_by_user_id)VALUES($1,$2,$3,$4,'OPERATIONS','Legacy expense',100,'2026-08-10','DRAFT',$5)`,[id,f.client.id,f.building.id,`EXP-${suffix()}`,userId]);return id}
describe('CR-BE-CUR-02 PART 01 — command currency for operational costs',()=>{
it('rejects a new Vendor / Service Cost without an explicit currency (no default/inference)',async t=>{if(!ready(t))return;const f=await structure(),s=await serviceVendor(f),r=await createCost(s.vendor.id,costBody(f,s.service.id,{currencyCode:undefined}));assert.equal(r.status,400);assert.equal(r.body.error.code,'VALIDATION_ERROR');
const unknown=await createCost(s.vendor.id,costBody(f,s.service.id,{currencyCode:'ZZZ'}));assert.equal(unknown.status,400);assert.equal(unknown.body.error.code,'CURRENCY_INACTIVE_OR_UNKNOWN')});
it('accepts an ACTIVE, Client-allowed currency and persists the exact snapshot',async t=>{if(!ready(t))return;const f=await structure(),s=await serviceVendor(f),r=await createCost(s.vendor.id,costBody(f,s.service.id,{currencyCode:'USD'}));assert.equal(r.status,201,JSON.stringify(r.body));assert.equal(r.body.data.currencyCode,'USD');const row=await pool!.query('SELECT currency_code FROM vendor_service_costs WHERE id=$1',[r.body.data.id]);assert.equal(row.rows[0].currency_code,'USD');
const h=await pool!.query('SELECT action,currency_code FROM vendor_service_cost_history WHERE vendor_service_cost_id=$1 ORDER BY changed_at',[r.body.data.id]);assert.deepEqual(h.rows.map(x=>[x.action,x.currency_code]),[['CREATED','USD']])});
it('rejects an INACTIVE Currency Master code even when Client-allowed',async t=>{if(!ready(t))return;const f=await structure(),s=await serviceVendor(f);await currencyService.setCurrencyStatus('JPY','INACTIVE',userId);try{const r=await createCost(s.vendor.id,costBody(f,s.service.id,{currencyCode:'JPY'}));assert.equal(r.status,400);assert.equal(r.body.error.code,'CURRENCY_INACTIVE_OR_UNKNOWN')}finally{await currencyService.setCurrencyStatus('JPY','ACTIVE',userId)}});
it('rejects a currency that is ACTIVE but not allowed for the resolved Client',async t=>{if(!ready(t))return;const f=await structure(),s=await serviceVendor(f),r=await createCost(s.vendor.id,costBody(f,s.service.id,{currencyCode:'EUR'}));assert.equal(r.status,400);assert.equal(r.body.error.code,'CLIENT_CURRENCY_NOT_ALLOWED')});
it('keeps a legacy NULL-currency cost readable and lets non-monetary updates keep NULL',async t=>{if(!ready(t))return;const f=await structure(),id=await legacyCost(f),get=await api().get(`/api/v1/vendor-service-costs/${id}`).set(auth());assert.equal(get.status,200);assert.equal(get.body.data.currencyCode,null);
const update=await api().patch(`/api/v1/vendor-service-costs/${id}`).set(auth()).send({notes:'Clarified note.'});assert.equal(update.status,200,JSON.stringify(update.body));assert.equal(update.body.data.currencyCode,null)});
it('requires an explicit currency only when a legacy NULL-currency monetary amount changes',async t=>{if(!ready(t))return;const f=await structure(),id=await legacyCost(f),denied=await api().patch(`/api/v1/vendor-service-costs/${id}`).set(auth()).send({costAmount:175});assert.equal(denied.status,400);assert.equal(denied.body.error.code,'VENDOR_SERVICE_COST_CURRENCY_REQUIRED');
const allowed=await api().patch(`/api/v1/vendor-service-costs/${id}`).set(auth()).send({costAmount:175,currencyCode:'IDR'});assert.equal(allowed.status,200,JSON.stringify(allowed.body));assert.equal(allowed.body.data.currencyCode,'IDR');
const h=await pool!.query('SELECT action,currency_code FROM vendor_service_cost_history WHERE vendor_service_cost_id=$1 ORDER BY changed_at',[id]);assert.deepEqual(h.rows.map(x=>[x.action,x.currency_code]),[['UPDATED','IDR']]);
const relabel=await api().patch(`/api/v1/vendor-service-costs/${id}`).set(auth()).send({currencyCode:'USD'});assert.equal(relabel.status,400);assert.equal(relabel.body.error.code,'VENDOR_SERVICE_COST_CURRENCY_IMMUTABLE')});
it('applies the same rules to Basic Expenses',async t=>{if(!ready(t))return;const f=await structure(),missing=await createExpense(expenseBody(f,{currencyCode:undefined}));assert.equal(missing.status,400);assert.equal(missing.body.error.code,'VALIDATION_ERROR');
const created=await createExpense(expenseBody(f,{currencyCode:'USD'}));assert.equal(created.status,201,JSON.stringify(created.body));assert.equal(created.body.data.currencyCode,'USD');
const id=await legacyExpense(f),get=await api().get(`/api/v1/basic-expenses/${id}`).set(auth());assert.equal(get.status,200);assert.equal(get.body.data.currencyCode,null);
const keepNull=await api().patch(`/api/v1/basic-expenses/${id}`).set(auth()).send({notes:'Note only.'});assert.equal(keepNull.status,200);assert.equal(keepNull.body.data.currencyCode,null);
const denied=await api().patch(`/api/v1/basic-expenses/${id}`).set(auth()).send({amount:200});assert.equal(denied.status,400);assert.equal(denied.body.error.code,'BASIC_EXPENSE_CURRENCY_REQUIRED');
const governed=await api().patch(`/api/v1/basic-expenses/${id}`).set(auth()).send({amount:200,currencyCode:'IDR'});assert.equal(governed.status,200,JSON.stringify(governed.body));assert.equal(governed.body.data.currencyCode,'IDR');
const h=await pool!.query('SELECT action,currency_code FROM basic_expense_history WHERE basic_expense_id=$1 ORDER BY changed_at',[id]);assert.deepEqual(h.rows.map(x=>[x.action,x.currency_code]),[['UPDATED',null],['UPDATED','IDR']])});
it('does not widen access: another Client without USD in its allowed set cannot use it',async t=>{if(!ready(t))return;const a=await structure(['IDR','USD']),b=await structure(['IDR']),sb=await serviceVendor(b),denied=await createCost(sb.vendor.id,costBody(b,sb.service.id,{currencyCode:'USD'}));assert.equal(denied.status,400);assert.equal(denied.body.error.code,'CLIENT_CURRENCY_NOT_ALLOWED');
const sa=await serviceVendor(a),accepted=await createCost(sa.vendor.id,costBody(a,sa.service.id,{currencyCode:'USD'}));assert.equal(accepted.status,201);assert.equal(accepted.body.data.currencyCode,'USD')});
});
