import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { mkdir, rm } from 'node:fs/promises';
import { resolve } from 'node:path';
import { after, before, describe, it, type TestContext } from 'node:test';
import type { Pool } from 'pg';
import EmbeddedPostgres from 'embedded-postgres';
import { parse } from 'yaml';
import type { DatabaseConfig } from '../src/config';
import { closePool, initDatabase, migrateUp } from '../src/database';
import { hashSessionToken } from '../src/modules/auth';
import { buildingAssignmentService } from '../src/modules/building-assignments';
import { buildingService } from '../src/modules/buildings';
import { clientService } from '../src/modules/clients';
import { entitlementService } from '../src/modules/entitlements';
import { featureEntitlementConfigurationRepository } from '../src/modules/feature-entitlement-configurations/feature-entitlement-configuration.repository';
import { licenseService } from '../src/modules/licenses';
import { moduleConfigurationRepository } from '../src/modules/module-configurations/module-configuration.repository';
import { moduleService } from '../src/modules/modules';
import { navigationRegistryRepository } from '../src/modules/navigation-registry/navigation-registry.repository';
import { propertyService } from '../src/modules/properties';
import { subscriptionService } from '../src/modules/subscriptions';
import { createAdminUser, createPlainSession, createSessionWithPermissions } from './helpers/access';
import { activateLatestConfigurationVersion } from './helpers/configuration-lifecycle';
import { api } from './helpers/http';
import { ensureTestDatabase } from './helpers/postgres';

const PORT=55458,DIR='/tmp/asentra-be27e-pg',EMBEDDED=process.env.ASENTRA_USE_EMBEDDED_POSTGRES==='true',START=new Date('2026-01-01'),END=new Date('2027-12-31');
process.env.NODE_ENV='test';process.env.LOG_LEVEL='error';process.env.DB_NAME='asentra_test';if(EMBEDDED){process.env.DB_HOST='127.0.0.1';process.env.DB_PORT=String(PORT);process.env.DB_USER='postgres';process.env.DB_PASSWORD='postgres';process.env.DB_SSL='false'}
let pg:EmbeddedPostgres|null=null,db:DatabaseConfig|null=null,pool:Pool|null=null,adminToken='',adminId='',plainToken='',readerToken='',readerId='',clientA='',buildingA='',sibling='',clientB='',buildingB='',siblingNav='',otherNav='',subscription='';
const auth=(t=adminToken)=>({Authorization:`Bearer ${t}`}),suffix=()=>randomUUID().slice(0,8).toUpperCase(),ok=(t:TestContext)=>{if(!db||!pool){t.skip('BE-27E database unavailable');return false}return true};
async function scope(assign?:string,count=1){const c=await clientService.createClient({code:`NAV_${suffix()}`,name:'Nav Client'}),p=await propertyService.createProperty({clientId:c.id,code:`P_${suffix()}`,name:'Nav Property'}),bs=[];for(let i=0;i<count;i++)bs.push(await buildingService.createBuilding({propertyId:p.id,code:`B_${suffix()}`,name:`Building ${i}`}));if(assign)await buildingAssignmentService.createAssignment(assign,{buildingId:bs[0].id});return{c,bs}}
async function mod(){const code=`NAVM_${suffix()}`;return moduleService.createModule({code,name:code})}
async function nav(scopeType:'CLIENT'|'BUILDING',scopeId:string,body:Record<string,unknown>,token=adminToken){const response=await api().post(`/api/v1/${scopeType==='CLIENT'?'clients':'buildings'}/${scopeId}/navigation-items`).set(auth(token)).send(body);if(response.status===201)await activateLatestConfigurationVersion(token,'NAVIGATION_ITEM',response.body.data.id);return response}
async function userForToken(token:string){return(await pool!.query<{user_id:string}>('SELECT user_id FROM user_sessions WHERE token_hash=$1',[hashSessionToken(token)])).rows[0].user_id}

before(async()=>{if(EMBEDDED){await rm(DIR,{recursive:true,force:true});await mkdir(DIR,{recursive:true});pg=new EmbeddedPostgres({databaseDir:DIR,port:PORT,user:'postgres',password:'',persistent:true,authMethod:'trust'});await pg.initialise();await pg.start();const a=pg.getPgClient('postgres','127.0.0.1');await a.connect();await a.query('CREATE DATABASE asentra_test');await a.end()}const x=await ensureTestDatabase();if(!x)return;db=x;pool=await initDatabase(x);await migrateUp(pool);await pool.query(`TRUNCATE navigation_items,feature_entitlement_configurations,module_configurations,building_configurations,client_configurations,module_entitlements,licenses,subscriptions,modules,user_building_assignments,buildings,properties,clients,user_sessions,user_credentials,role_permission_assignments,user_role_assignments,permissions,roles,users CASCADE`);const a=await createAdminUser();adminToken=a.token;adminId=a.userId;plainToken=await createPlainSession();readerToken=await createSessionWithPermissions([{code:'navigation_registry.read',name:'Read Navigation Registry'}]);readerId=await userForToken(readerToken);const s=await scope(adminId,2);clientA=s.c.id;buildingA=s.bs[0].id;sibling=s.bs[1].id;await buildingAssignmentService.createAssignment(readerId,{buildingId:buildingA});const sub=await subscriptionService.createSubscription({clientId:clientA,code:`S_${suffix()}`,planCode:'ENTERPRISE',startsAt:START,endsAt:END});subscription=sub.id;await licenseService.createLicense(sub.id,{validFrom:START,validUntil:END});const sm=await mod();siblingNav=(await navigationRegistryRepository.create({scopeType:'BUILDING',clientId:null,buildingId:sibling,navigationKey:'PRIVATE',label:'Private',routeReference:'/private',parentNavigationKey:null,displayOrder:0,moduleId:sm.id,featureKey:null,permissionId:null,enabled:true})).id;const o=await scope(undefined,1);clientB=o.c.id;buildingB=o.bs[0].id;otherNav=(await navigationRegistryRepository.create({scopeType:'CLIENT',clientId:clientB,buildingId:null,navigationKey:'OTHER',label:'Other',routeReference:'/other',parentNavigationKey:null,displayOrder:0,moduleId:null,featureKey:null,permissionId:null,enabled:true})).id});
after(async()=>{try{if(pool)await closePool(pool);if(pg)await pg.stop()}finally{await rm(DIR,{recursive:true,force:true})}pool=null;pg=null;db=null});

describe('BE-27E Navigation Registry',()=>{
it('stores key, label, route, parent, ordering and bindings',async t=>{if(!ok(t))return;const m=await mod();await moduleConfigurationRepository.create({scopeType:'CLIENT',clientId:clientA,buildingId:null,moduleId:m.id,enabled:true});await featureEntitlementConfigurationRepository.create({scopeType:'CLIENT',clientId:clientA,buildingId:null,moduleId:m.id,featureKey:'VIEW',state:'ENABLED'});let r=await nav('CLIENT',clientA,{navigationKey:'ROOT',label:'Root',routeReference:'/root',displayOrder:1});assert.equal(r.status,201,JSON.stringify(r.body));r=await nav('CLIENT',clientA,{navigationKey:'CHILD',label:'Child',routeReference:'/child',parentNavigationKey:'ROOT',displayOrder:2,moduleKey:m.code,featureKey:'VIEW',permissionCode:'work_order.read'});assert.equal(r.status,201,JSON.stringify(r.body));assert.equal(r.body.data.parentNavigationKey,'ROOT');assert.equal(r.body.data.moduleId,m.id);assert.equal(r.body.data.featureKey,'VIEW');assert.equal(r.body.data.permissionCode,'work_order.read')});
it('rejects duplicate key, missing parent, missing Feature and invalid hierarchy',async t=>{if(!ok(t))return;await nav('CLIENT',clientA,{navigationKey:'DUP',label:'One',routeReference:'/one'});let r=await nav('CLIENT',clientA,{navigationKey:'dup',label:'Two',routeReference:'/two'});assert.equal(r.status,409);r=await nav('CLIENT',clientA,{navigationKey:'ORPHAN',label:'Orphan',routeReference:'/o',parentNavigationKey:'MISSING'});assert.equal(r.body.error.code,'NAVIGATION_PARENT_NOT_FOUND');const m=await mod();r=await nav('CLIENT',clientA,{navigationKey:'NO_FEATURE',label:'No feature',routeReference:'/nf',moduleKey:m.code,featureKey:'MISSING'});assert.equal(r.body.error.code,'NAVIGATION_FEATURE_NOT_FOUND');r=await nav('CLIENT',clientA,{navigationKey:'SELF',label:'Self',routeReference:'/s',parentNavigationKey:'SELF'});assert.equal(r.status,400)});
it('lists, gets and updates mutable presentation fields only',async t=>{if(!ok(t))return;const r=await nav('CLIENT',clientA,{navigationKey:`EDIT_${suffix()}`,label:'Before',routeReference:'/before',displayOrder:5});const id=r.body.data.id;let x=await api().patch(`/api/v1/navigation-items/${id}`).set(auth()).send({label:'After',routeReference:'/after',displayOrder:3,enabled:false});assert.equal(x.status,200);assert.equal(x.body.data.label,'After');x=await api().get(`/api/v1/navigation-items/${id}`).set(auth());assert.equal(x.status,200);const list=await api().get(`/api/v1/clients/${clientA}/navigation-items`).set(auth());assert.equal(list.status,200);x=await api().patch(`/api/v1/navigation-items/${id}`).set(auth()).send({moduleKey:'CHANGED'});assert.equal(x.status,400)});
});

describe('BE-27E effective navigation',()=>{
it('filters by enabled Module, Feature, Permission and parent visibility',async t=>{if(!ok(t))return;const m=await mod();await entitlementService.createEntitlement(subscription,{moduleId:m.id,startsAt:START,endsAt:END});await moduleConfigurationRepository.create({scopeType:'CLIENT',clientId:clientA,buildingId:null,moduleId:m.id,enabled:true});await featureEntitlementConfigurationRepository.create({scopeType:'CLIENT',clientId:clientA,buildingId:null,moduleId:m.id,featureKey:'ACCESS',state:'ENABLED'});for(const body of[{navigationKey:'E_ROOT',label:'Root',routeReference:'/e',displayOrder:0},{navigationKey:'E_MODULE',label:'Module',routeReference:'/m',parentNavigationKey:'E_ROOT',displayOrder:1,moduleKey:m.code},{navigationKey:'E_FEATURE',label:'Feature',routeReference:'/f',parentNavigationKey:'E_ROOT',displayOrder:2,moduleKey:m.code,featureKey:'ACCESS'},{navigationKey:'E_PERMISSION',label:'Permission',routeReference:'/p',displayOrder:3,permissionCode:'work_order.read'},{navigationKey:'E_HIDDEN_PARENT',label:'Hidden parent',routeReference:'/hp',displayOrder:4,permissionCode:'work_order.read'},{navigationKey:'E_CHILD',label:'Child',routeReference:'/c',parentNavigationKey:'E_HIDDEN_PARENT',displayOrder:0},{navigationKey:'E_DISABLED',label:'Disabled',routeReference:'/d',enabled:false}]){const r=await nav('CLIENT',clientA,body);assert.equal(r.status,201,JSON.stringify(r.body))}let r=await api().get(`/api/v1/clients/${clientA}/navigation/effective`).set(auth());assert.equal(r.status,200);let keys=r.body.data.items.map((x:any)=>x.navigationKey);for(const k of['E_ROOT','E_MODULE','E_FEATURE','E_PERMISSION','E_HIDDEN_PARENT','E_CHILD'])assert.ok(keys.includes(k),k);assert.ok(!keys.includes('E_DISABLED'));assert.ok(keys.indexOf('E_ROOT')<keys.indexOf('E_MODULE'));r=await api().get(`/api/v1/clients/${clientA}/navigation/effective`).set(auth(readerToken));assert.equal(r.status,200);keys=r.body.data.items.map((x:any)=>x.navigationKey);assert.ok(keys.includes('E_ROOT'));assert.ok(keys.includes('E_MODULE'));assert.ok(keys.includes('E_FEATURE'));assert.ok(!keys.includes('E_PERMISSION'));assert.ok(!keys.includes('E_HIDDEN_PARENT'));assert.ok(!keys.includes('E_CHILD'))});
it('applies Building registry override over Client navigation key',async t=>{if(!ok(t))return;const key=`OVERRIDE_${suffix()}`;await nav('CLIENT',clientA,{navigationKey:key,label:'Client',routeReference:'/client'});await nav('BUILDING',buildingA,{navigationKey:key,label:'Building',routeReference:'/building',displayOrder:1});const r=await api().get(`/api/v1/buildings/${buildingA}/navigation/effective`).set(auth());assert.equal(r.status,200);const item=r.body.data.items.find((x:any)=>x.navigationKey===key);assert.equal(item.label,'Building');assert.equal(item.routeReference,'/building');assert.equal(item.scopeType,'BUILDING')});
});

describe('BE-27E RBAC and isolation',()=>{
it('requires authentication and registry permissions',async t=>{if(!ok(t))return;let r=await api().get(`/api/v1/clients/${clientA}/navigation-items`);assert.equal(r.status,401);r=await nav('CLIENT',clientA,{navigationKey:'DENIED',label:'Denied',routeReference:'/denied'},plainToken);assert.equal(r.status,403);assert.equal(r.body.error.code,'PERMISSION_DENIED')});
it('denies sibling Building and cross-Client records',async t=>{if(!ok(t))return;for(const path of[`/api/v1/buildings/${sibling}/navigation-items`,`/api/v1/buildings/${sibling}/navigation/effective`,`/api/v1/navigation-items/${siblingNav}`,`/api/v1/clients/${clientB}/navigation-items`,`/api/v1/clients/${clientB}/navigation/effective`,`/api/v1/buildings/${buildingB}/navigation-items`,`/api/v1/navigation-items/${otherNav}`]){const r=await api().get(path).set(auth());assert.equal(r.status,403,path);assert.equal(r.body.error.code,'BUILDING_ACCESS_DENIED')}});
});

describe('BE-27E OpenAPI contract',()=>{it('documents Navigation Registry in the final BE-27 contract',()=>{const spec=parse(readFileSync(resolve(__dirname,'../docs/api/openapi.yaml'),'utf8'));for(const p of['/clients/{clientId}/navigation-items','/clients/{clientId}/navigation/effective','/buildings/{buildingId}/navigation-items','/buildings/{buildingId}/navigation/effective','/navigation-items/{navigationItemId}'])assert.ok(spec.paths[p],p);for(const s of['NavigationItem','CreateNavigationItemRequest','UpdateNavigationItemRequest','EffectiveNavigation'])assert.ok(spec.components.schemas[s],s);assert.ok(spec.paths['/clients/{clientId}/workspaces'])})});
