import assert from'node:assert/strict';import{randomUUID}from'node:crypto';import{after,before,describe,it,type TestContext}from'node:test';import type{Pool}from'pg';import type{DatabaseConfig}from'../src/config';import{closePool,initDatabase,migrateUp}from'../src/database';import{areaService}from'../src/modules/areas';import{buildingAssignmentService}from'../src/modules/building-assignments';import{buildingService}from'../src/modules/buildings';import{clientMonetaryContextService}from'../src/modules/client-monetary-contexts';import{clientService}from'../src/modules/clients';import{floorService}from'../src/modules/floors';import{parseIssuePaymentReceiptBody}from'../src/modules/payment-receipts';import{propertyService}from'../src/modules/properties';import{roomService}from'../src/modules/rooms';import{spaceService}from'../src/modules/spaces';import{createAdminUser,createPlainSession}from'./helpers/access';import{api}from'./helpers/http';import{ensureTestDatabase}from'./helpers/postgres';
let database:DatabaseConfig|null=null,pool:Pool|null=null,token='',userId='';const suffix=()=>randomUUID().slice(0,8).toUpperCase(),auth=(v=token)=>({Authorization:`Bearer ${v}`});
before(async()=>{const db=await ensureTestDatabase();if(!db)return;pool=await initDatabase(db);await migrateUp(pool);await pool.query(`TRUNCATE payment_receipt_history,payment_receipts,invoice_payment_status_history,invoice_payment_status,tenant_invoice_history,tenant_invoice_lines,tenant_invoices,tenant_charge_history,tenant_charges,tenant_building_contexts,tenant_space_relationships,tenant_companies,spaces,rooms,areas,floors,buildings,properties,users,roles,permissions,clients CASCADE`);const a=await createAdminUser();token=a.token;userId=a.userId;database=db});after(async()=>{if(pool)await closePool(pool);pool=null;database=null});function ready(t:TestContext){if(!database||!pool){t.skip('test database unavailable');return false}return true}
async function fixture(uid=userId,tok=token){const client=await clientService.createClient({code:`C_${suffix()}`,name:'Owner'}),property=await propertyService.createProperty({clientId:client.id,code:`P_${suffix()}`,name:'Property'}),building=await buildingService.createBuilding({propertyId:property.id,code:`B_${suffix()}`,name:'Building'});await buildingAssignmentService.createAssignment(uid,{buildingId:building.id});await clientMonetaryContextService.setClientMonetaryContext({clientId:client.id,baseCurrencyCode:'IDR',defaultTransactionCurrencyCode:'IDR',allowedCurrencyCodes:['IDR','USD']},uid);const floor=await floorService.createFloor({buildingId:building.id,code:`F_${suffix()}`,name:'Floor',levelNumber:1}),area=await areaService.createArea({floorId:floor.id,code:`A_${suffix()}`,name:'Area'}),room=await roomService.createRoom({areaId:area.id,code:`R_${suffix()}`,name:'Room'}),space=await spaceService.createSpace({roomId:room.id,code:`S_${suffix()}`,name:'Space'});const tr=await api().post(`/api/v1/clients/${client.id}/tenant-companies`).set(auth(tok)).send({tenantCode:`TNT_${suffix()}`,tenantName:'Tenant'});assert.equal(tr.status,201);const tenant=tr.body.data;assert.equal((await api().post(`/api/v1/tenant-companies/${tenant.id}/spaces`).set(auth(tok)).send({buildingId:building.id,spaceId:space.id})).status,201);assert.equal((await api().post(`/api/v1/tenant-companies/${tenant.id}/building-contexts`).set(auth(tok)).send({buildingId:building.id})).status,201);return{client,building,space,tenant}}
async function invoice(f:Awaited<ReturnType<typeof fixture>>,amount=1000){const charge=await api().post(`/api/v1/tenant-companies/${f.tenant.id}/charges`).set(auth()).send({buildingId:f.building.id,spaceId:f.space.id,chargeType:'SERVICE',description:'Charge',amount,currencyCode:'IDR',chargeDate:'2026-08-01'});const inv=await api().post(`/api/v1/tenant-companies/${f.tenant.id}/invoices`).set(auth()).send({buildingId:f.building.id,spaceId:f.space.id,invoiceNumber:`INV-${suffix()}`,invoiceDate:'2026-08-01',dueDate:'2099-01-01',currencyCode:'IDR'});assert.equal(inv.status,201);assert.equal((await api().post(`/api/v1/tenant-invoices/${inv.body.data.id}/lines`).set(auth()).send({sourceType:'TENANT_CHARGE',sourceId:charge.body.data.id})).status,201);const fin=await api().post(`/api/v1/tenant-invoices/${inv.body.data.id}/finalize`).set(auth()).send({});assert.equal(fin.status,200);return fin.body.data}
async function payment(invoiceId:string,paidAmount:number,reference=`PAY-${suffix()}`){const r=await api().post(`/api/v1/tenant-invoices/${invoiceId}/payment-status`).set(auth()).send({paidAmount,paidAt:'2026-08-10T00:00:00.000Z',paymentReference:reference});assert.equal(r.status,201,JSON.stringify(r.body));return r.body.data}
async function issue(invoiceId:string,amount:number,reference=`RCPT-PAY-${suffix()}`,tok=token){return api().post(`/api/v1/tenant-invoices/${invoiceId}/receipts`).set(auth(tok)).send({receiptNumber:`RCT-${suffix()}`,receivedAmount:amount,receivedAt:'2026-08-10T01:00:00.000Z',paymentReference:reference,paymentMethod:'bank_transfer',notes:'Settlement evidence.'})}
describe('BE-19F Payment Receipt',()=>{
 it('validates receipt amount and data-driven method without database access',()=>{const p=parseIssuePaymentReceiptBody({receiptNumber:' rct-001 ',receivedAmount:100,receivedAt:'2026-08-10T00:00:00Z',paymentMethod:' bank_transfer '});assert.equal(p.receiptNumber,'RCT-001');assert.equal(p.paymentMethod,'BANK_TRANSFER');assert.throws(()=>parseIssuePaymentReceiptBody({...p,receivedAmount:0}))});
 it('issues, gets, and filters a valid Receipt',async t=>{if(!ready(t))return;const f=await fixture(),inv=await invoice(f);await payment(inv.id,1000);const r=await issue(inv.id,1000);assert.equal(r.status,201,JSON.stringify(r.body));assert.equal(r.body.data.status,'ISSUED');assert.equal(r.body.data.receivedAmount,1000);assert.equal(r.body.data.tenantCompanyId,f.tenant.id);assert.equal((await api().get(`/api/v1/payment-receipts/${r.body.data.id}`).set(auth())).status,200);const list=await api().get('/api/v1/payment-receipts').query({tenantCompanyId:f.tenant.id,invoiceId:inv.id,buildingId:f.building.id,receivedFrom:'2026-08-01T00:00:00Z',receivedTo:'2026-08-31T23:59:59Z'}).set(auth());assert.equal(list.status,200);assert.equal(list.body.data.length,1)});
 it('supports partial-payment Receipts within recorded paid amount',async t=>{if(!ready(t))return;const f=await fixture(),inv=await invoice(f);await payment(inv.id,400);const one=await issue(inv.id,200,'PART-1'),two=await issue(inv.id,200,'PART-2');assert.equal(one.status,201);assert.equal(two.status,201);assert.equal(Number(await paymentReceiptSum(inv.id)),400)});
 it('rejects an invalid Invoice or missing Payment Status context',async t=>{if(!ready(t))return;const unknown=await issue(randomUUID(),100);assert.equal(unknown.status,404);assert.equal(unknown.body.error.code,'TENANT_INVOICE_NOT_FOUND');const f=await fixture(),inv=await invoice(f),missing=await issue(inv.id,100);assert.equal(missing.status,400);assert.equal(missing.body.error.code,'PAYMENT_RECEIPT_CONTEXT_INVALID')});
 it('rejects invalid or uncovered Receipt amounts',async t=>{if(!ready(t))return;const f=await fixture(),inv=await invoice(f);await payment(inv.id,400);const excessive=await issue(inv.id,401);assert.equal(excessive.status,400);assert.equal(excessive.body.error.code,'PAYMENT_RECEIPT_AMOUNT_INVALID');const first=await issue(inv.id,300,'COVER-1');assert.equal(first.status,201);const remainder=await issue(inv.id,101,'COVER-2');assert.equal(remainder.status,400)});
 it('protects duplicate payment references',async t=>{if(!ready(t))return;const f=await fixture(),inv=await invoice(f);await payment(inv.id,500);assert.equal((await issue(inv.id,200,'DUP-REF')).status,201);const duplicate=await issue(inv.id,100,'DUP-REF');assert.equal(duplicate.status,409);assert.equal(duplicate.body.error.code,'PAYMENT_RECEIPT_REFERENCE_ALREADY_EXISTS')});
 it('keeps Receipt totals consistent with Payment Status',async t=>{if(!ready(t))return;const f=await fixture(),inv=await invoice(f);const ps=await payment(inv.id,600);await issue(inv.id,250,'CONS-1');await issue(inv.id,350,'CONS-2');const status=await api().get(`/api/v1/tenant-invoices/${inv.id}/payment-status`).set(auth());assert.equal(status.body.data.id,ps.id);assert.equal(status.body.data.paidAmount,600);assert.equal(Number(await paymentReceiptSum(inv.id)),600);const invoiceRead=await api().get(`/api/v1/tenant-invoices/${inv.id}`).set(auth());assert.equal(invoiceRead.body.data.totalAmount,1000)});
 it('only permits explicit void and preserves issued history',async t=>{if(!ready(t))return;const f=await fixture(),inv=await invoice(f);await payment(inv.id,500);const issued=await issue(inv.id,500,'VOID-REF');const id=issued.body.data.id;const voided=await api().post(`/api/v1/payment-receipts/${id}/void`).set(auth()).send({});assert.equal(voided.status,200);assert.equal(voided.body.data.status,'VOID');assert.equal(voided.body.data.receivedAmount,500);const again=await api().post(`/api/v1/payment-receipts/${id}/void`).set(auth()).send({});assert.equal(again.status,400);const history=await pool!.query('SELECT action FROM payment_receipt_history WHERE payment_receipt_id=$1 ORDER BY changed_at',[id]);assert.deepEqual(history.rows.map(x=>x.action),['ISSUED','VOIDED'])});
 it('enforces RBAC',async t=>{if(!ready(t))return;const f=await fixture(),inv=await invoice(f);await payment(inv.id,1000);const plain=await createPlainSession(),r=await issue(inv.id,1000,'RBAC-REF',plain);assert.equal(r.status,403);assert.equal(r.body.error.code,'PERMISSION_DENIED')});
 it('enforces Client and Building isolation',async t=>{if(!ready(t))return;const f=await fixture(),inv=await invoice(f);await payment(inv.id,1000);const receipt=await issue(inv.id,1000),other=await createAdminUser();await fixture(other.userId,other.token);const denied=await api().get(`/api/v1/payment-receipts/${receipt.body.data.id}`).set(auth(other.token));assert.equal(denied.status,403);assert.equal(denied.body.error.code,'BUILDING_ACCESS_DENIED');const list=await api().get('/api/v1/payment-receipts').set(auth(other.token));assert.equal(list.status,200);assert.equal(list.body.data.some((x:{id:string})=>x.id===receipt.body.data.id),false)});
});
async function paymentReceiptSum(invoiceId:string){const r=await pool!.query<{total:string}>(`SELECT COALESCE(SUM(received_amount),0)::text AS total FROM payment_receipts WHERE invoice_id=$1 AND status='ISSUED'`,[invoiceId]);return r.rows[0].total}
