import assert from 'node:assert/strict';import{readFileSync}from'node:fs';import{resolve}from'node:path';import{describe,it}from'node:test';import{parse}from'yaml';import{api}from'./helpers/http';
const spec=parse(readFileSync(resolve(__dirname,'../docs/api/openapi.yaml'),'utf8'));
describe('SLA escalation OpenAPI contract',()=>{
it('documents only the PART 01 escalation configuration paths and schemas',()=>{assert.ok(spec.paths['/clients/{clientId}/sla-escalation-policies'].post);assert.ok(spec.paths['/clients/{clientId}/sla-escalation-policies'].get);assert.ok(spec.paths['/sla-escalation-policies/{id}'].get);assert.ok(spec.paths['/sla-escalation-policies/{id}'].patch);assert.ok(spec.paths['/sla-escalation-policies/{id}/levels'].post);assert.ok(spec.paths['/sla-escalation-policies/{id}/levels'].get);assert.ok(spec.paths['/sla-escalation-levels/{id}'].get);assert.ok(spec.paths['/sla-escalation-levels/{id}'].patch);for(const x of['SlaEscalationPolicy','CreateSlaEscalationPolicyRequest','UpdateSlaEscalationPolicyRequest','SlaEscalationLevel','CreateSlaEscalationLevelRequest','UpdateSlaEscalationLevelRequest','SlaEscalationRecipientRule','SlaEscalationDerivedTarget','SlaEscalationClockType'])assert.ok(spec.components.schemas[x],x);
for(const forbidden of['/sla-escalations','/sla-escalation-actions','/sla-escalation-policies/{id}/trigger','/sla-escalation-policies/{id}/execute'])assert.equal(spec.paths[forbidden],undefined,forbidden);
assert.equal(spec.paths['/sla-escalation-policies/{id}'].delete,undefined);assert.equal(spec.paths['/sla-escalation-levels/{id}'].delete,undefined)});
it('documents the PART 05 escalation history read path and its privacy boundary',()=>{const p=spec.paths['/work-orders/{id}/sla/escalations'];assert.ok(p,'path missing');assert.ok(p.get,'GET missing');assert.equal(p.post,undefined);assert.equal(p.patch,undefined);assert.equal(p.put,undefined);assert.equal(p.delete,undefined);assert.equal(p.get['x-required-permission'],'work_order.read');assert.equal(p.get['x-building-scoped'],true);assert.deepEqual(p.get.security,[{bearerAuth:[]}]);for(const c of['400','401','403','404'])assert.ok(p.get.responses[c],c);
const items=p.get.responses['200'].content['application/json'].schema.allOf[1].properties.data;assert.equal(items.type,'array');assert.equal(items.items.$ref,'#/components/schemas/SlaEscalationAction');
const s2=spec.components.schemas.SlaEscalationAction;assert.ok(s2,'SlaEscalationAction schema missing');for(const f of['id','workOrderId','slaClockId','clockType','policyId','escalationLevelId','level','templateKey','breachedAt','dueAt','status','triggeredAt','cancelledAt','cancelReason','recipientsResolved','notificationsCreated','failureReason'])assert.ok(s2.properties[f],f);
assert.deepEqual(s2.properties.status.enum,['PENDING','TRIGGERED','CANCELLED','SKIPPED']);assert.deepEqual(s2.properties.cancelReason.enum,['CLOCK_SATISFIED','CLOCK_TERMINATED']);
for(const leaked of['recipientRule','recipients','recipientUserIds','providerMessageId','provider','deliveryStatus','emailAddress','phoneNumber'])assert.equal(s2.properties[leaked],undefined,leaked)});
it('keeps the SLA-01 definition contract untouched',()=>{assert.ok(spec.paths['/clients/{clientId}/sla-definitions'].post);assert.ok(spec.paths['/sla-definitions/{id}'].patch);assert.ok(spec.paths['/work-orders/{id}/sla'].get);for(const x of['SlaDefinition','AppliedSla','SlaClock'])assert.ok(spec.components.schemas[x],x)});
it('keeps every documented escalation route registered and protected',async()=>{const id='00000000-0000-0000-0000-000000000000';for(const[method,path]of[['post',`/clients/${id}/sla-escalation-policies`],['get',`/clients/${id}/sla-escalation-policies`],['get',`/sla-escalation-policies/${id}`],['patch',`/sla-escalation-policies/${id}`],['post',`/sla-escalation-policies/${id}/levels`],['get',`/sla-escalation-policies/${id}/levels`],['get',`/sla-escalation-levels/${id}`],['patch',`/sla-escalation-levels/${id}`]]as const){const r=method==='post'?await api().post(`/api/v1${path}`).send({}):method==='patch'?await api().patch(`/api/v1${path}`).send({}):await api().get(`/api/v1${path}`);assert.equal(r.status,401,`${method} ${path}`)}});
it('exposes no escalation execution route, only the protected read route', async()=>{const id='00000000-0000-0000-0000-000000000000';for(const r of[await api().post(`/api/v1/sla-escalation-policies/${id}/trigger`).send({}),await api().get('/api/v1/sla-escalations'),await api().get('/api/v1/sla-escalation-actions'),await api().post(`/api/v1/work-orders/${id}/sla/escalations`).send({}),await api().delete(`/api/v1/work-orders/${id}/sla/escalations`)])assert.equal(r.status,404);
assert.equal((await api().get(`/api/v1/work-orders/${id}/sla/escalations`)).status,401)});
});
