import assert from'node:assert/strict';import{randomUUID}from'node:crypto';import{mkdir,rm}from'node:fs/promises';import{after,before,describe,it,type TestContext}from'node:test';import type{Pool}from'pg';import EmbeddedPostgres from'embedded-postgres';import type{DatabaseConfig}from'../src/config';import{closePool,initDatabase,migrateUp}from'../src/database';import{buildingAssignmentService}from'../src/modules/building-assignments';import{buildingService}from'../src/modules/buildings';import{clientService}from'../src/modules/clients';import{createNotificationTemplate}from'../src/modules/notification-templates';import{propertyService}from'../src/modules/properties';import{createAdminUser}from'./helpers/access';import{api}from'./helpers/http';import{ensureTestDatabase}from'./helpers/postgres';
const PORT=55503,DIR='/tmp/asentra-sla02-p1';process.env.NODE_ENV='test';process.env.LOG_LEVEL='error';process.env.DB_NAME='asentra_test';process.env.DB_HOST='127.0.0.1';process.env.DB_PORT=String(PORT);process.env.DB_USER='postgres';process.env.DB_PASSWORD='postgres';process.env.DB_SSL='false';
let pg:EmbeddedPostgres|null=null,pool:Pool|null=null,db:DatabaseConfig|null=null,token='',user='',clientA='',clientB='',buildingA='',buildingB='',templateKey='';
const auth=()=>({Authorization:`Bearer ${token}`}),s=()=>randomUUID().slice(0,8).toUpperCase();
async function scope(assign=false){const c=await clientService.createClient({code:`ESC_${s()}`,name:'Escalation Client'}),p=await propertyService.createProperty({clientId:c.id,code:`P_${s()}`,name:'P'}),b=await buildingService.createBuilding({propertyId:p.id,code:`B_${s()}`,name:'B'});if(assign)await buildingAssignmentService.createAssignment(user,{buildingId:b.id});return{c,b}}
function ok(t:TestContext){if(!db||!pool){t.skip('database unavailable');return false}return true}
function createPolicy(client=clientA,x:Record<string,unknown>={}){return api().post(`/api/v1/clients/${client}/sla-escalation-policies`).set(auth()).send({code:`ESC.${s()}`,name:'Response breach escalation',operationalType:'WORK_ORDER',clockType:'RESPONSE',effectiveFrom:'2026-08-23T00:00:00Z',...x})}
function createLevel(policyId:string,x:Record<string,unknown>={}){return api().post(`/api/v1/sla-escalation-policies/${policyId}/levels`).set(auth()).send({level:1,offsetMinutes:0,templateKey,recipientRule:{derived:[{kind:'WORK_ORDER_ASSIGNEE'}]},...x})}
before(async()=>{await rm(DIR,{recursive:true,force:true});await mkdir(DIR,{recursive:true});pg=new EmbeddedPostgres({databaseDir:DIR,port:PORT,user:'postgres',password:'',persistent:true,authMethod:'trust'});await pg.initialise();await pg.start();const a=pg.getPgClient('postgres','127.0.0.1');await a.connect();await a.query('CREATE DATABASE asentra_test');await a.end();db=await ensureTestDatabase();if(!db)return;pool=await initDatabase(db);await migrateUp(pool);const admin=await createAdminUser();token=admin.token;user=admin.userId;const A=await scope(true),B=await scope(false);clientA=A.c.id;buildingA=A.b.id;clientB=B.c.id;buildingB=B.b.id;const tpl=await createNotificationTemplate({key:`sla.escalation.${s().toLowerCase()}`,type:'SLA_ESCALATION',channel:'IN_APP',subject:'SLA breached'});templateKey=tpl.key});
after(async()=>{if(pool)await closePool(pool);if(pg)await pg.stop();await rm(DIR,{recursive:true,force:true})});
describe('CR-BE-SLA-02 PART 01 escalation policies and levels',()=>{
it('creates client and building scoped policies with existing work type and priority vocabulary',async t=>{if(!ok(t))return;const a=await createPolicy();assert.equal(a.status,201,JSON.stringify(a.body));assert.equal(a.body.data.buildingId,null);assert.equal(a.body.data.clockType,'RESPONSE');assert.equal(a.body.data.status,'ACTIVE');const b=await createPolicy(clientA,{buildingId:buildingA,clockType:'ANY',workType:'hvac',priority:'CRITICAL'});assert.equal(b.status,201,JSON.stringify(b.body));assert.equal(b.body.data.buildingId,buildingA);assert.equal(b.body.data.workType,'HVAC');assert.equal(b.body.data.priority,'CRITICAL');assert.equal(b.body.data.clockType,'ANY')});
it('rejects a duplicate policy code within the same client',async t=>{if(!ok(t))return;const code=`ESC.${s()}`;assert.equal((await createPolicy(clientA,{code})).status,201);const dup=await createPolicy(clientA,{code});assert.equal(dup.status,409,JSON.stringify(dup.body))});
it('validates clock type, operational type, priority, code format and effective range',async t=>{if(!ok(t))return;for(const body of[{clockType:'BOTH'},{clockType:undefined},{operationalType:'INCIDENT'},{priority:'URGENT'},{code:'9bad'},{effectiveTo:'2026-08-22T00:00:00Z'},{unexpected:true}]){const r=await createPolicy(clientA,body);assert.equal(r.status,400,`${JSON.stringify(body)} -> ${JSON.stringify(r.body)}`)}});
it('enforces client and building isolation on policies',async t=>{if(!ok(t))return;assert.equal((await createPolicy(clientB)).status,403);assert.equal((await createPolicy(clientA,{buildingId:buildingB})).status,403);const foreign=await api().get(`/api/v1/clients/${clientB}/sla-escalation-policies`).set(auth());assert.equal(foreign.status,403)});
it('updates, disables, reads and filters policies',async t=>{if(!ok(t))return;const made=await createPolicy(clientA,{buildingId:buildingA,clockType:'RESOLUTION',priority:'HIGH'});const id=made.body.data.id;const changed=await api().patch(`/api/v1/sla-escalation-policies/${id}`).set(auth()).send({name:'Changed',status:'INACTIVE',description:'Escalate resolution breaches'});assert.equal(changed.status,200,JSON.stringify(changed.body));assert.equal(changed.body.data.status,'INACTIVE');assert.equal(changed.body.data.description,'Escalate resolution breaches');const one=await api().get(`/api/v1/sla-escalation-policies/${id}`).set(auth());assert.equal(one.status,200);const list=await api().get(`/api/v1/clients/${clientA}/sla-escalation-policies?buildingId=${buildingA}&status=INACTIVE&clockType=RESOLUTION&priority=HIGH`).set(auth());assert.equal(list.status,200);assert.ok(list.body.data.some((x:{id:string})=>x.id===id));assert.ok(list.body.data.every((x:{buildingId:string;status:string;clockType:string})=>x.buildingId===buildingA&&x.status==='INACTIVE'&&x.clockType==='RESOLUTION'))});
it('creates ordered levels with static specs and derived target vocabulary',async t=>{if(!ok(t))return;const policy=(await createPolicy()).body.data.id;const first=await createLevel(policy,{level:1,offsetMinutes:0});assert.equal(first.status,201,JSON.stringify(first.body));assert.equal(first.body.data.offsetMinutes,0);assert.deepEqual(first.body.data.recipientRule.derived,[{kind:'WORK_ORDER_ASSIGNEE'}]);const second=await createLevel(policy,{level:2,offsetMinutes:30,recipientRule:{specs:[{kind:'ROLE',roleCode:'ops_manager'}],derived:[{kind:'BUILDING_PERMISSION',permissionCode:'work_order.manage'}]}});assert.equal(second.status,201,JSON.stringify(second.body));assert.deepEqual(second.body.data.recipientRule.specs,[{kind:'ROLE',roleCode:'OPS_MANAGER'}]);assert.deepEqual(second.body.data.recipientRule.derived,[{kind:'BUILDING_PERMISSION',permissionCode:'work_order.manage'}]);const levels=await api().get(`/api/v1/sla-escalation-policies/${policy}/levels`).set(auth());assert.equal(levels.status,200);assert.deepEqual(levels.body.data.map((x:{level:number})=>x.level),[1,2])});
it('rejects duplicate level numbers and duplicate offsets within one policy',async t=>{if(!ok(t))return;const policy=(await createPolicy()).body.data.id;assert.equal((await createLevel(policy,{level:1,offsetMinutes:15})).status,201);assert.equal((await createLevel(policy,{level:1,offsetMinutes:45})).status,409);assert.equal((await createLevel(policy,{level:2,offsetMinutes:15})).status,409);assert.equal((await createLevel(policy,{level:2,offsetMinutes:45})).status,201)});
it('validates level bounds, template existence and recipient rule vocabulary',async t=>{if(!ok(t))return;const policy=(await createPolicy()).body.data.id;for(const body of[{level:0},{offsetMinutes:-1},{recipientRule:{}},{recipientRule:{specs:[],derived:[]}},{recipientRule:{derived:[{kind:'CEO'}]}},{recipientRule:{derived:[{kind:'BUILDING_ROLE'}]}},{recipientRule:{derived:[{kind:'WORK_ORDER_CREATOR',roleCode:'X'}]}},{recipientRule:{specs:[{kind:'USER',userId:'not-a-uuid'}]}},{recipientRule:{unexpected:1,derived:[{kind:'WORK_ORDER_CREATOR'}]}}]){const r=await createLevel(policy,body);assert.equal(r.status,400,`${JSON.stringify(body)} -> ${JSON.stringify(r.body)}`)}const missing=await createLevel(policy,{templateKey:'sla.escalation.does.not.exist'});assert.equal(missing.status,400,JSON.stringify(missing.body))});
it('updates a level and keeps policy isolation on level access',async t=>{if(!ok(t))return;const policy=(await createPolicy(clientA,{buildingId:buildingA})).body.data.id;const level=(await createLevel(policy,{level:1,offsetMinutes:0})).body.data.id;const changed=await api().patch(`/api/v1/sla-escalation-levels/${level}`).set(auth()).send({offsetMinutes:60,status:'INACTIVE',recipientRule:{derived:[{kind:'WORK_ORDER_ASSIGNEE_SUPERVISOR'}]}});assert.equal(changed.status,200,JSON.stringify(changed.body));assert.equal(changed.body.data.offsetMinutes,60);assert.equal(changed.body.data.status,'INACTIVE');assert.deepEqual(changed.body.data.recipientRule.derived,[{kind:'WORK_ORDER_ASSIGNEE_SUPERVISOR'}]);const one=await api().get(`/api/v1/sla-escalation-levels/${level}`).set(auth());assert.equal(one.status,200);assert.equal((await api().get(`/api/v1/sla-escalation-levels/${randomUUID()}`).set(auth())).status,404)});
it('requires authentication on every configuration route',async t=>{if(!ok(t))return;const id=randomUUID();for(const r of[await api().post(`/api/v1/clients/${clientA}/sla-escalation-policies`).send({}),await api().get(`/api/v1/clients/${clientA}/sla-escalation-policies`),await api().get(`/api/v1/sla-escalation-policies/${id}`),await api().patch(`/api/v1/sla-escalation-policies/${id}`).send({}),await api().post(`/api/v1/sla-escalation-policies/${id}/levels`).send({}),await api().get(`/api/v1/sla-escalation-policies/${id}/levels`),await api().get(`/api/v1/sla-escalation-levels/${id}`),await api().patch(`/api/v1/sla-escalation-levels/${id}`).send({})])assert.equal(r.status,401)});
it('exposes no escalation execution surface in PART 01',async t=>{if(!ok(t))return;const policy=(await createPolicy()).body.data.id;for(const r of[await api().post(`/api/v1/sla-escalation-policies/${policy}/trigger`).set(auth()).send({}),await api().get('/api/v1/sla-escalations').set(auth()),await api().post(`/api/v1/sla-escalation-policies/${policy}/execute`).set(auth()).send({})])assert.equal(r.status,404);const tables=await pool!.query<{table_name:string}>(`SELECT table_name FROM information_schema.tables WHERE table_name LIKE 'sla_escalation%' ORDER BY table_name`);assert.deepEqual(tables.rows.map(r=>r.table_name),['sla_escalation_actions','sla_escalation_levels','sla_escalation_policies'])});
});
