import assert from'node:assert/strict';import{randomUUID}from'node:crypto';import{mkdir,rm}from'node:fs/promises';import{after,before,describe,it,type TestContext}from'node:test';import type{Pool}from'pg';import EmbeddedPostgres from'embedded-postgres';import type{DatabaseConfig}from'../src/config';import{closePool,initDatabase,migrateUp}from'../src/database';import{buildingAssignmentService}from'../src/modules/building-assignments';import{buildingService}from'../src/modules/buildings';import{clientService}from'../src/modules/clients';import{propertyService}from'../src/modules/properties';import{createAdminUser}from'./helpers/access';import{api}from'./helpers/http';import{ensureTestDatabase}from'./helpers/postgres';
const PORT=55501,DIR='/tmp/asentra-sla01-p1';process.env.NODE_ENV='test';process.env.LOG_LEVEL='error';process.env.DB_NAME='asentra_test';process.env.DB_HOST='127.0.0.1';process.env.DB_PORT=String(PORT);process.env.DB_USER='postgres';process.env.DB_PASSWORD='postgres';process.env.DB_SSL='false';let pg:EmbeddedPostgres|null=null,pool:Pool|null=null,db:DatabaseConfig|null=null,token='',user='',clientA='',clientB='',buildingA='',buildingB='';const auth=()=>({Authorization:`Bearer ${token}`}),s=()=>randomUUID().slice(0,8).toUpperCase();
async function scope(assign=false){const c=await clientService.createClient({code:`SLA_${s()}`,name:'SLA Client'}),p=await propertyService.createProperty({clientId:c.id,code:`P_${s()}`,name:'P'}),b=await buildingService.createBuilding({propertyId:p.id,code:`B_${s()}`,name:'B'});if(assign)await buildingAssignmentService.createAssignment(user,{buildingId:b.id});return{c,b}}
function ok(t:TestContext){if(!db||!pool){t.skip('database unavailable');return false}return true}function create(client=clientA,x:Record<string,unknown>={}){return api().post(`/api/v1/clients/${client}/sla-definitions`).set(auth()).send({code:`SLA.${s()}`,name:'Response SLA',operationalType:'WORK_ORDER',responseTargetMinutes:30,effectiveFrom:'2026-08-23T00:00:00Z',...x})}
before(async()=>{await rm(DIR,{recursive:true,force:true});await mkdir(DIR,{recursive:true});pg=new EmbeddedPostgres({databaseDir:DIR,port:PORT,user:'postgres',password:'',persistent:true,authMethod:'trust'});await pg.initialise();await pg.start();const a=pg.getPgClient('postgres','127.0.0.1');await a.connect();await a.query('CREATE DATABASE asentra_test');await a.end();db=await ensureTestDatabase();if(!db)return;pool=await initDatabase(db);await migrateUp(pool);const admin=await createAdminUser();token=admin.token;user=admin.userId;const A=await scope(true),B=await scope(false);clientA=A.c.id;buildingA=A.b.id;clientB=B.c.id;buildingB=B.b.id});after(async()=>{if(pool)await closePool(pool);if(pg)await pg.stop();await rm(DIR,{recursive:true,force:true})});
describe('CR-BE-SLA-01 PART 01 SLA definitions',()=>{
it('creates client and building scoped definitions with existing priorities',async t=>{if(!ok(t))return;const a=await create();assert.equal(a.status,201,JSON.stringify(a.body));assert.equal(a.body.data.buildingId,null);const b=await create(clientA,{buildingId:buildingA,priority:'CRITICAL',resolutionTargetMinutes:120});assert.equal(b.status,201,JSON.stringify(b.body));assert.equal(b.body.data.buildingId,buildingA);assert.equal(b.body.data.priority,'CRITICAL')});
it('validates positive targets, applicability, and effective range',async t=>{if(!ok(t))return;for(const body of[{responseTargetMinutes:0},{responseTargetMinutes:undefined,resolutionTargetMinutes:-1},{operationalType:'INCIDENT'},{priority:'URGENT'},{effectiveTo:'2026-08-22T00:00:00Z'}]){const r=await create(clientA,body);assert.equal(r.status,400,JSON.stringify(r.body))}});
it('enforces client and building isolation',async t=>{if(!ok(t))return;assert.equal((await create(clientB)).status,403);assert.equal((await create(clientA,{buildingId:buildingB})).status,403)});
it('updates, disables, reads, and filters in effective context',async t=>{if(!ok(t))return;const made=await create(clientA,{buildingId:buildingA,priority:'HIGH'});const id=made.body.data.id;const changed=await api().patch(`/api/v1/sla-definitions/${id}`).set(auth()).send({name:'Changed',status:'INACTIVE',resolutionTargetMinutes:90});assert.equal(changed.status,200,JSON.stringify(changed.body));assert.equal(changed.body.data.status,'INACTIVE');const one=await api().get(`/api/v1/sla-definitions/${id}`).set(auth());assert.equal(one.status,200);const list=await api().get(`/api/v1/clients/${clientA}/sla-definitions?buildingId=${buildingA}&status=INACTIVE&priority=HIGH`).set(auth());assert.equal(list.status,200);assert.ok(list.body.data.some((x:{id:string})=>x.id===id));assert.ok(list.body.data.every((x:{buildingId:string;status:string})=>x.buildingId===buildingA&&x.status==='INACTIVE'))});
});
