import assert from'node:assert/strict';import{randomUUID}from'node:crypto';import{mkdir,rm}from'node:fs/promises';import{after,before,describe,it,type TestContext}from'node:test';import type{Pool}from'pg';import EmbeddedPostgres from'embedded-postgres';import type{DatabaseConfig}from'../src/config';import{closePool,initDatabase,migrateUp}from'../src/database';import{buildingAssignmentService}from'../src/modules/building-assignments';import{buildingService}from'../src/modules/buildings';import{clientService}from'../src/modules/clients';import{propertyService}from'../src/modules/properties';import{slaDefinitionRepository}from'../src/modules/sla-definitions/sla-definition.repository';import{createAdminUser,createPlainSession}from'./helpers/access';import{api}from'./helpers/http';import{ensureTestDatabase}from'./helpers/postgres';
const PORT=55502,DIR='/tmp/asentra-sla01-p2';process.env.NODE_ENV='test';process.env.LOG_LEVEL='error';process.env.DB_NAME='asentra_test';process.env.DB_HOST='127.0.0.1';process.env.DB_PORT=String(PORT);process.env.DB_USER='postgres';process.env.DB_PASSWORD='postgres';process.env.DB_SSL='false';let pg:EmbeddedPostgres|null=null,pool:Pool|null=null,db:DatabaseConfig|null=null,token='',plain='',user='',client='',building='';const auth=(x=token)=>({Authorization:`Bearer ${x}`}),s=()=>randomUUID().slice(0,8).toUpperCase();function ready(t:TestContext){if(!db||!pool){t.skip('database unavailable');return false}return true}
async function def(x:Record<string,unknown>={}){return slaDefinitionRepository.create({clientId:client,code:`D.${s()}`,name:'SLA',operationalType:'WORK_ORDER',responseTargetMinutes:30,effectiveFrom:'2026-01-01T00:00:00Z',...x} as any)}async function wo(workType:string){return api().post(`/api/v1/buildings/${building}/work-orders`).set(auth()).send({clientId:client,workOrderNumber:`WO_${s()}`,title:'SLA work',workType})}async function sla(id:string){return api().get(`/api/v1/work-orders/${id}/sla`).set(auth())}
before(async()=>{await rm(DIR,{recursive:true,force:true});await mkdir(DIR,{recursive:true});pg=new EmbeddedPostgres({databaseDir:DIR,port:PORT,user:'postgres',password:'',persistent:true,authMethod:'trust'});await pg.initialise();await pg.start();const a=pg.getPgClient('postgres','127.0.0.1');await a.connect();await a.query('CREATE DATABASE asentra_test');await a.end();db=await ensureTestDatabase();if(!db)return;pool=await initDatabase(db);await migrateUp(pool);const admin=await createAdminUser();token=admin.token;user=admin.userId;plain=await createPlainSession();const c=await clientService.createClient({code:`C_${s()}`,name:'Client'}),p=await propertyService.createProperty({clientId:c.id,code:`P_${s()}`,name:'P'}),b=await buildingService.createBuilding({propertyId:p.id,code:`B_${s()}`,name:'B'});client=c.id;building=b.id;await buildingAssignmentService.createAssignment(user,{buildingId:building})});after(async()=>{if(pool)await closePool(pool);if(pg)await pg.stop();await rm(DIR,{recursive:true,force:true})});
describe('CR-BE-SLA-01 PART 02 application and clocks',()=>{
it('selects client-wide definition and creates only configured clock at authoritative createdAt',async t=>{if(!ready(t))return;await def({workType:'CLIENT_ONLY',resolutionTargetMinutes:undefined});const w=await wo('CLIENT_ONLY');assert.equal(w.status,201,JSON.stringify(w.body));const a=await sla(w.body.data.id);assert.equal(a.status,200);assert.equal(a.body.data.buildingId,building);assert.equal(a.body.data.clocks.length,1);assert.equal(a.body.data.clocks[0].clockType,'RESPONSE');assert.equal(a.body.data.clocks[0].startedAt,w.body.data.createdAt)});
it('prefers Building scope, then greater applicability specificity',async t=>{if(!ready(t))return;await def({workType:'BUILDING_WIN',responseTargetMinutes:10});await def({buildingId:building,workType:'BUILDING_WIN',responseTargetMinutes:20});const w=await wo('BUILDING_WIN'),a=await sla(w.body.data.id);assert.equal(a.body.data.responseTargetMinutes,20);await def({workType:'SPECIFIC',responseTargetMinutes:11});await def({workType:'SPECIFIC',priority:'MEDIUM',responseTargetMinutes:22});const w2=await wo('SPECIFIC'),a2=await sla(w2.body.data.id);assert.equal(a2.body.data.responseTargetMinutes,22)});
it('ignores inactive, future, and expired definitions',async t=>{if(!ready(t))return;await def({workType:'IGNORED',status:'INACTIVE'});await def({workType:'IGNORED',effectiveFrom:'2099-01-01T00:00:00Z'});await def({workType:'IGNORED',effectiveFrom:'2020-01-01T00:00:00Z',effectiveTo:'2021-01-01T00:00:00Z'});const w=await wo('IGNORED');assert.equal(w.status,201);assert.equal((await sla(w.body.data.id)).body.data,null)});
it('rejects equal-specificity ambiguity and rolls back Work Order creation',async t=>{if(!ready(t))return;await def({workType:'AMBIG',responseTargetMinutes:5});await def({workType:'AMBIG',responseTargetMinutes:6});const w=await wo('AMBIG');assert.equal(w.status,409,JSON.stringify(w.body));const count=await pool!.query("SELECT count(*)::int n FROM work_orders WHERE work_type='AMBIG'");assert.equal(count.rows[0].n,0)});
it('persists immutable snapshot and both target clocks despite later definition update',async t=>{if(!ready(t))return;const d=await def({workType:'SNAPSHOT',responseTargetMinutes:15,resolutionTargetMinutes:90});const w=await wo('SNAPSHOT'),before=await sla(w.body.data.id);assert.deepEqual(before.body.data.clocks.map((x:{clockType:string})=>x.clockType),['RESOLUTION','RESPONSE']);assert.ok(before.body.data.clocks.every((x:{startedAt:string})=>x.startedAt===w.body.data.createdAt));const changed=await api().patch(`/api/v1/sla-definitions/${d.id}`).set(auth()).send({responseTargetMinutes:999,resolutionTargetMinutes:888,name:'Changed'});assert.equal(changed.status,200);const afterRead=await sla(w.body.data.id);assert.equal(afterRead.body.data.responseTargetMinutes,15);assert.equal(afterRead.body.data.resolutionTargetMinutes,90);assert.equal(afterRead.body.data.definitionCode,d.code)});
it('does not backfill historical Work Orders and preserves read isolation',async t=>{if(!ready(t))return;const old=await wo('HISTORICAL');assert.equal(old.status,201);await def({workType:'HISTORICAL'});assert.equal((await sla(old.body.data.id)).body.data,null);const denied=await api().get(`/api/v1/work-orders/${old.body.data.id}/sla`).set(auth(plain));assert.equal(denied.status,403)});
});
