import assert from'node:assert/strict';import{randomUUID}from'node:crypto';import{after,before,describe,it,type TestContext}from'node:test';import type{Pool}from'pg';import type{DatabaseConfig}from'../src/config';import{closePool,initDatabase,migrateUp}from'../src/database';import{buildingAssignmentService}from'../src/modules/building-assignments';import{buildingService}from'../src/modules/buildings';import{clientService}from'../src/modules/clients';import{propertyService}from'../src/modules/properties';import{clientMonetaryContextService}from'../src/modules/client-monetary-contexts';import{purchaseRequestService}from'../src/modules/purchase-requests';import{vendorAssignmentService}from'../src/modules/vendor-assignments';import{vendorBuildingService}from'../src/modules/vendor-buildings';import{vendorService}from'../src/modules/vendors';import{parseCreateVendorServiceCostBody}from'../src/modules/vendor-service-costs';import{workOrderService}from'../src/modules/work-orders';import{createAdminUser,createPlainSession}from'./helpers/access';import{api}from'./helpers/http';import{ensureTestDatabase}from'./helpers/postgres';let database:DatabaseConfig|null=null,pool:Pool|null=null,token='',userId='';const suffix=()=>randomUUID().slice(0,8).toUpperCase(),auth=(v=token)=>({Authorization:`Bearer ${v}`});
before(async()=>{const db=await ensureTestDatabase();if(!db)return;pool=await initDatabase(db);await migrateUp(pool);await pool.query(`TRUNCATE vendor_service_cost_history,vendor_service_costs,receivings,purchase_order_readiness,vendor_selection_readiness,procurement_approval_bindings,service_requests,purchase_requests,vendor_works,vendor_assignments,work_orders,work_requests,vendor_building_relationships,vendors,buildings,properties,users,roles,permissions,clients CASCADE`);const a=await createAdminUser();token=a.token;userId=a.userId;database=db});after(async()=>{if(pool)await closePool(pool);pool=null;database=null});function ready(t:TestContext){if(!database||!pool){t.skip('test database unavailable');return false}return true}
async function structure(uid=userId){const client=await clientService.createClient({code:`C_${suffix()}`,name:'Client'}),property=await propertyService.createProperty({clientId:client.id,code:`P_${suffix()}`,name:'Property'}),building=await buildingService.createBuilding({propertyId:property.id,code:`B_${suffix()}`,name:'Building'});await buildingAssignmentService.createAssignment(uid,{buildingId:building.id});await clientMonetaryContextService.setClientMonetaryContext({clientId:client.id,baseCurrencyCode:'IDR',defaultTransactionCurrencyCode:'IDR',allowedCurrencyCodes:['IDR']},uid);return{client,building}}
async function vendorWork(){const f=await structure(),vendor=await vendorService.createVendor({clientId:f.client.id,vendorCode:`V_${suffix()}`,vendorName:'Vendor'});await vendorBuildingService.assignBuildingToVendor({vendorId:vendor.id,buildingId:f.building.id});const wo=await workOrderService.createWorkOrder({clientId:f.client.id,buildingId:f.building.id,workOrderNumber:`WO_${suffix()}`,title:'Vendor work',workType:'REPAIR',createdByUserId:userId}),assignment=await vendorAssignmentService.assignVendor({vendorId:vendor.id,workOrderId:wo.id,assignedByUserId:userId}),r=await api().post(`/api/v1/vendor-assignments/${assignment.id}/work`).set(auth()).send({});assert.equal(r.status,201,JSON.stringify(r.body));return{...f,vendor,wo,work:r.body.data}}
async function serviceContext(){const f=await structure(),vendor=await vendorService.createVendor({clientId:f.client.id,vendorCode:`V_${suffix()}`,vendorName:'Service Vendor'}),pr=await purchaseRequestService.createPurchaseRequest({clientId:f.client.id,buildingId:f.building.id,requestNumber:`PR_${suffix()}`,requestType:'SERVICE',title:'Service purchase',requestedByUserId:userId}),r=await api().post(`/api/v1/purchase-requests/${pr.id}/service-requests`).set(auth()).send({serviceType:'CLEANING',title:'Cleaning service',vendorId:vendor.id});assert.equal(r.status,201,JSON.stringify(r.body));return{...f,vendor,service:r.body.data}}
function payload(buildingId:string,contextType:'VENDOR_WORK'|'SERVICE_REQUEST',contextId:string,extra:Record<string,unknown>={}){return{buildingId,contextType,contextId,costAmount:250000,costDate:'2026-08-15',costType:'SERVICE_FEE',costCategory:'OPERATIONS',currencyCode:'IDR',reference:`COST-${suffix()}`,notes:'Operational cost.',...extra}}
async function create(vendorId:string,body:object,tok=token){return api().post(`/api/v1/vendors/${vendorId}/costs`).set(auth(tok)).send(body)}
describe('BE-19G Vendor / Service Cost',()=>{
 it('validates positive amount and data-driven codes without database access',()=>{const p=parseCreateVendorServiceCostBody(payload(randomUUID(),'VENDOR_WORK',randomUUID(),{costType:' service_fee '}));assert.equal(p.costType,'SERVICE_FEE');assert.throws(()=>parseCreateVendorServiceCostBody({...p,costAmount:0}))});
 it('creates, gets, and filters a valid Vendor Work cost',async t=>{if(!ready(t))return;const f=await vendorWork(),r=await create(f.vendor.id,payload(f.building.id,'VENDOR_WORK',f.work.id));assert.equal(r.status,201,JSON.stringify(r.body));assert.equal(r.body.data.vendorWorkId,f.work.id);assert.equal(r.body.data.workOrderId,f.wo.id);assert.equal(r.body.data.status,'DRAFT');assert.equal((await api().get(`/api/v1/vendor-service-costs/${r.body.data.id}`).set(auth())).status,200);const list=await api().get('/api/v1/vendor-service-costs').query({vendorId:f.vendor.id,buildingId:f.building.id,workOrderId:f.wo.id,status:'DRAFT',costDateFrom:'2026-08-01',costDateTo:'2026-08-31'}).set(auth());assert.equal(list.status,200);assert.equal(list.body.data.length,1)});
 it('creates a valid Procurement Service Request cost',async t=>{if(!ready(t))return;const f=await serviceContext(),r=await create(f.vendor.id,payload(f.building.id,'SERVICE_REQUEST',f.service.id));assert.equal(r.status,201,JSON.stringify(r.body));assert.equal(r.body.data.serviceRequestId,f.service.id);assert.equal(r.body.data.workOrderId,null)});
 it('rejects an invalid Vendor',async t=>{if(!ready(t))return;const f=await vendorWork(),r=await create(randomUUID(),payload(f.building.id,'VENDOR_WORK',f.work.id));assert.equal(r.status,404);assert.equal(r.body.error.code,'VENDOR_NOT_FOUND')});
 it('rejects invalid Work and Vendor Work references',async t=>{if(!ready(t))return;const f=await vendorWork(),unknown=await create(f.vendor.id,payload(f.building.id,'VENDOR_WORK',randomUUID()));assert.equal(unknown.status,400);assert.equal(unknown.body.error.code,'VENDOR_SERVICE_COST_CONTEXT_INVALID');const other=await vendorWork(),wrong=await create(f.vendor.id,payload(f.building.id,'VENDOR_WORK',other.work.id));assert.equal(wrong.status,400)});
 it('rejects invalid amounts',async t=>{if(!ready(t))return;const f=await vendorWork(),r=await create(f.vendor.id,payload(f.building.id,'VENDOR_WORK',f.work.id,{costAmount:-1}));assert.equal(r.status,400);assert.equal(r.body.error.code,'VALIDATION_ERROR')});
 it('rejects a Building mismatch',async t=>{if(!ready(t))return;const f=await vendorWork(),other=await structure(),r=await create(f.vendor.id,payload(other.building.id,'VENDOR_WORK',f.work.id));assert.equal(r.status,400);assert.equal(r.body.error.code,'VENDOR_SERVICE_COST_CONTEXT_INVALID')});
 it('finalizes and protects cost history from overwrite',async t=>{if(!ready(t))return;const f=await vendorWork(),created=await create(f.vendor.id,payload(f.building.id,'VENDOR_WORK',f.work.id)),id=created.body.data.id;const updated=await api().patch(`/api/v1/vendor-service-costs/${id}`).set(auth()).send({costAmount:275000});assert.equal(updated.status,200);const fin=await api().post(`/api/v1/vendor-service-costs/${id}/finalize`).set(auth()).send({});assert.equal(fin.status,200);assert.equal(fin.body.data.status,'FINALIZED');const overwrite=await api().patch(`/api/v1/vendor-service-costs/${id}`).set(auth()).send({costAmount:1});assert.equal(overwrite.status,400);assert.equal(overwrite.body.error.code,'VENDOR_SERVICE_COST_FINALIZED_PROTECTED');const history=await pool!.query('SELECT action FROM vendor_service_cost_history WHERE vendor_service_cost_id=$1 ORDER BY changed_at',[id]);assert.deepEqual(history.rows.map(x=>x.action),['CREATED','UPDATED','FINALIZED'])});
 it('enforces RBAC',async t=>{if(!ready(t))return;const f=await vendorWork(),plain=await createPlainSession(),r=await create(f.vendor.id,payload(f.building.id,'VENDOR_WORK',f.work.id),plain);assert.equal(r.status,403);assert.equal(r.body.error.code,'PERMISSION_DENIED')});
 it('enforces Client and Building isolation',async t=>{if(!ready(t))return;const f=await vendorWork(),created=await create(f.vendor.id,payload(f.building.id,'VENDOR_WORK',f.work.id)),other=await createAdminUser();await structure(other.userId);const denied=await api().get(`/api/v1/vendor-service-costs/${created.body.data.id}`).set(auth(other.token));assert.equal(denied.status,403);assert.equal(denied.body.error.code,'BUILDING_ACCESS_DENIED');const list=await api().get('/api/v1/vendor-service-costs').set(auth(other.token));assert.equal(list.status,200);assert.equal(list.body.data.some((x:{id:string})=>x.id===created.body.data.id),false)});
});
