import { resolveBuildingConfigurationContext } from '../building-configurations';
import { clientInactiveError } from '../clients';
import { resolveClientConfigurationContext } from '../client-configurations';
import { contextAccessService } from '../context-access';
import { captureConfigurationVersion, resolveLifecycleEffectiveSnapshot } from '../configuration-versions';
import { featureEntitlementConfigurationRepository } from '../feature-entitlement-configurations/feature-entitlement-configuration.repository';
import { featureEntitlementConfigurationService } from '../feature-entitlement-configurations';
import { moduleConfigurationService, type ModuleConfigurationScope } from '../module-configurations';
import { moduleInactiveError, moduleNotFoundError, moduleRepository } from '../modules';
import { permissionInactiveError, permissionNotFoundError, permissionRepository, permissionService } from '../permissions';
import { navigationFeatureNotFoundError, navigationHierarchyInvalidError, navigationItemNotFoundError, navigationKeyAlreadyExistsError, navigationParentNotFoundError } from './navigation-registry.errors';
import { navigationRegistryRepository } from './navigation-registry.repository';
import type { CreateNavigationItemInput, EffectiveNavigation, EffectiveNavigationItem, NavigationItemRecord, NewNavigationItem, PublicNavigationItem, UpdateNavigationItemInput } from './navigation-registry.types';

export function toPublicNavigationItem(r:NavigationItemRecord):PublicNavigationItem{return{...r,createdAt:r.createdAt.toISOString(),updatedAt:r.updatedAt.toISOString()}}
async function versionNavigation(r:PublicNavigationItem,u:string){await captureConfigurationVersion({sourceType:'NAVIGATION_ITEM',sourceConfigurationId:r.id,clientId:r.clientId,buildingId:r.buildingId,status:r.enabled?'ENABLED':'DISABLED',snapshot:r},u);return r}
async function lifecycleNavigation(r:NavigationItemRecord){const s=await resolveLifecycleEffectiveSnapshot('NAVIGATION_ITEM',r.id,toPublicNavigationItem(r));if(typeof s!=='object'||s===null||Array.isArray(s))return null;return{...r,label:typeof s.label==='string'?s.label:r.label,routeReference:typeof s.routeReference==='string'?s.routeReference:r.routeReference,displayOrder:typeof s.displayOrder==='number'?s.displayOrder:r.displayOrder,enabled:typeof s.enabled==='boolean'?s.enabled:r.enabled}}
const unique=(e:unknown)=>e instanceof Error&&(e as{code?:string}).code==='23505'&&['navigation_items_client_key_unique','navigation_items_building_key_unique'].includes((e as{constraint?:string}).constraint??'');
async function bindings(i:CreateNavigationItemInput){let moduleId:null|string=null,permissionId:null|string=null;if(i.moduleKey){const m=await moduleRepository.findByCode(i.moduleKey);if(!m)throw moduleNotFoundError();if(m.status!=='ACTIVE')throw moduleInactiveError();moduleId=m.id}if(i.permissionCode){const p=await permissionRepository.findByCode(i.permissionCode);if(!p)throw permissionNotFoundError();if(p.status!=='ACTIVE')throw permissionInactiveError();permissionId=p.id}return{moduleId,permissionId}}
async function available(scope:ModuleConfigurationScope,scopeId:string,clientId:string,key:string){return scope==='CLIENT'?navigationRegistryRepository.findByScopeAndKey('CLIENT',scopeId,key):(await navigationRegistryRepository.findByScopeAndKey('BUILDING',scopeId,key))??navigationRegistryRepository.findByScopeAndKey('CLIENT',clientId,key)}
async function featureAvailable(scope:ModuleConfigurationScope,scopeId:string,clientId:string,moduleId:string,featureKey:string){return scope==='CLIENT'?featureEntitlementConfigurationRepository.findByScopeModuleFeature('CLIENT',scopeId,moduleId,featureKey):(await featureEntitlementConfigurationRepository.findByScopeModuleFeature('BUILDING',scopeId,moduleId,featureKey))??featureEntitlementConfigurationRepository.findByScopeModuleFeature('CLIENT',clientId,moduleId,featureKey)}
async function validateHierarchy(scope:ModuleConfigurationScope,scopeId:string,clientId:string,input:CreateNavigationItemInput){if(!input.parentNavigationKey)return;const parent=await available(scope,scopeId,clientId,input.parentNavigationKey);if(!parent)throw navigationParentNotFoundError();const clientItems=await navigationRegistryRepository.listByScope('CLIENT',clientId),scopeItems=scope==='BUILDING'?await navigationRegistryRepository.listByScope('BUILDING',scopeId):[];const map=new Map(clientItems.map(x=>[x.navigationKey,x.parentNavigationKey]));for(const x of scopeItems)map.set(x.navigationKey,x.parentNavigationKey);map.set(input.navigationKey,input.parentNavigationKey);let key:string|null=input.navigationKey;const seen=new Set<string>();while(key){if(seen.has(key))throw navigationHierarchyInvalidError();seen.add(key);key=map.get(key)??null}}
async function createFor(scope:ModuleConfigurationScope,scopeId:string,clientId:string,input:CreateNavigationItemInput){if(await navigationRegistryRepository.findByScopeAndKey(scope,scopeId,input.navigationKey))throw navigationKeyAlreadyExistsError();const b=await bindings(input);if(input.featureKey&&(!b.moduleId||!await featureAvailable(scope,scopeId,clientId,b.moduleId,input.featureKey)))throw navigationFeatureNotFoundError();await validateHierarchy(scope,scopeId,clientId,input);const n:NewNavigationItem={scopeType:scope,clientId:scope==='CLIENT'?scopeId:null,buildingId:scope==='BUILDING'?scopeId:null,navigationKey:input.navigationKey,label:input.label,routeReference:input.routeReference,parentNavigationKey:input.parentNavigationKey??null,displayOrder:input.displayOrder,moduleId:b.moduleId,featureKey:input.featureKey??null,permissionId:b.permissionId,enabled:input.enabled};try{return toPublicNavigationItem(await navigationRegistryRepository.create(n))}catch(e){if(unique(e))throw navigationKeyAlreadyExistsError();throw e}}
export async function createClientNavigationItem(clientId:string,input:CreateNavigationItemInput,userId:string){const c=await resolveClientConfigurationContext(clientId,userId);if(c.status!=='ACTIVE')throw clientInactiveError();return versionNavigation(await createFor('CLIENT',c.id,c.id,input),userId)}
export async function createBuildingNavigationItem(buildingId:string,input:CreateNavigationItemInput,userId:string){const c=await resolveBuildingConfigurationContext(buildingId,userId);if(c.clientStatus!=='ACTIVE')throw clientInactiveError();return versionNavigation(await createFor('BUILDING',c.buildingId,c.clientId,input),userId)}
export async function listClientNavigationItems(clientId:string,userId:string){await resolveClientConfigurationContext(clientId,userId);return(await navigationRegistryRepository.listByScope('CLIENT',clientId)).map(toPublicNavigationItem)}
export async function listBuildingNavigationItems(buildingId:string,userId:string){await resolveBuildingConfigurationContext(buildingId,userId);return(await navigationRegistryRepository.listByScope('BUILDING',buildingId)).map(toPublicNavigationItem)}
async function scoped(id:string,userId:string){const r=await navigationRegistryRepository.findById(id);if(!r)throw navigationItemNotFoundError();if(r.scopeType==='BUILDING'&&r.buildingId)await contextAccessService.assertBuildingAccess(userId,r.buildingId);else await resolveClientConfigurationContext(r.clientId,userId);return r}
export async function getNavigationItem(id:string,userId:string){return toPublicNavigationItem(await scoped(id,userId))}
export async function updateNavigationItem(id:string,input:UpdateNavigationItemInput,userId:string){await scoped(id,userId);const r=await navigationRegistryRepository.update(id,input);if(!r)throw navigationItemNotFoundError();return versionNavigation(toPublicNavigationItem(r),userId)}
function ordered(records:NavigationItemRecord[]){const children=new Map<string|null,NavigationItemRecord[]>();for(const r of records){const a=children.get(r.parentNavigationKey)??[];a.push(r);children.set(r.parentNavigationKey,a)}for(const a of children.values())a.sort((x,y)=>x.displayOrder-y.displayOrder||x.navigationKey.localeCompare(y.navigationKey));const out:NavigationItemRecord[]=[],visit=(parent:string|null)=>{for(const r of children.get(parent)??[]){out.push(r);visit(r.navigationKey)}};visit(null);return out}
async function effective(clientId:string,buildingId:string|null,records:NavigationItemRecord[],userId:string,preview:NavigationItemRecord|null=null):Promise<EffectiveNavigation>{const [modules,features,permissions]=await Promise.all([buildingId?moduleConfigurationService.getEffectiveBuildingModuleConfiguration(buildingId,userId):moduleConfigurationService.getEffectiveClientModuleConfiguration(clientId,userId),buildingId?featureEntitlementConfigurationService.getEffectiveBuildingFeatureEntitlements(buildingId,userId):featureEntitlementConfigurationService.getEffectiveClientFeatureEntitlements(clientId,userId),permissionService.resolvePermissionsForUser(userId)]);const mm=new Map(modules.modules.map(x=>[x.moduleId,x.enabled])),fm=new Map(features.features.map(x=>[`${x.moduleId}:${x.featureKey}`,x.state==='ENABLED'])),ps=new Set(permissions),eligible=new Map<string,NavigationItemRecord>(),lifecycle:NavigationItemRecord[]=[];for(const record of records){const r=preview?.id===record.id?preview:await lifecycleNavigation(record);if(r)lifecycle.push(r)}for(const r of lifecycle){if(!r.enabled)continue;if(r.moduleId&&!mm.get(r.moduleId))continue;if(r.featureKey&&(!r.moduleId||!fm.get(`${r.moduleId}:${r.featureKey}`)))continue;if(r.permissionCode&&!ps.has(r.permissionCode))continue;eligible.set(r.navigationKey,r)}let changed=true;while(changed){changed=false;for(const[k,r]of eligible)if(r.parentNavigationKey&&!eligible.has(r.parentNavigationKey)){eligible.delete(k);changed=true}}const items:EffectiveNavigationItem[]=ordered([...eligible.values()]).map(r=>{const p=toPublicNavigationItem(r);const{createdAt:_c,updatedAt:_u,...item}=p;return item});return{clientId,buildingId,items}}
export async function getPreviewNavigation(sourceId:string,snapshot:unknown,clientId:string,buildingId:string|null,userId:string){const current=await navigationRegistryRepository.findById(sourceId);if(!current)throw navigationItemNotFoundError();if(current.clientId!==clientId||current.buildingId!==buildingId||typeof snapshot!=='object'||snapshot===null||Array.isArray(snapshot))throw navigationItemNotFoundError();const s=snapshot as Record<string,unknown>,preview:NavigationItemRecord={...current,label:typeof s.label==='string'?s.label:current.label,routeReference:typeof s.routeReference==='string'?s.routeReference:current.routeReference,displayOrder:typeof s.displayOrder==='number'?s.displayOrder:current.displayOrder,enabled:typeof s.enabled==='boolean'?s.enabled:current.enabled};if(buildingId){const[a,b]=await Promise.all([navigationRegistryRepository.listByScope('CLIENT',clientId),navigationRegistryRepository.listByScope('BUILDING',buildingId)]),m=new Map(a.map(x=>[x.navigationKey,x]));for(const x of b)m.set(x.navigationKey,x);m.set(preview.navigationKey,preview);return effective(clientId,buildingId,[...m.values()],userId,preview)}const rows=await navigationRegistryRepository.listByScope('CLIENT',clientId);return effective(clientId,null,rows,userId,preview)}
export async function getEffectiveClientNavigation(clientId:string,userId:string){const c=await resolveClientConfigurationContext(clientId,userId);if(c.status!=='ACTIVE')throw clientInactiveError();return effective(c.id,null,await navigationRegistryRepository.listByScope('CLIENT',c.id),userId)}
export async function getEffectiveBuildingNavigation(buildingId:string,userId:string){const c=await resolveBuildingConfigurationContext(buildingId,userId);if(c.clientStatus!=='ACTIVE')throw clientInactiveError();const[client,building]=await Promise.all([navigationRegistryRepository.listByScope('CLIENT',c.clientId),navigationRegistryRepository.listByScope('BUILDING',c.buildingId)]);const map=new Map(client.map(x=>[x.navigationKey,x]));for(const x of building)map.set(x.navigationKey,x);return effective(c.clientId,c.buildingId,[...map.values()],userId)}
export const navigationRegistryService={createBuildingNavigationItem,createClientNavigationItem,getEffectiveBuildingNavigation,getEffectiveClientNavigation,getNavigationItem,getPreviewNavigation,listBuildingNavigationItems,listClientNavigationItems,updateNavigationItem};
