import { AppError } from '../../shared/errors';
import { isValidUuid } from '../clients';
import { isValidModuleCode, normalizeModuleCode } from '../modules';
import { isValidPermissionCode, normalizePermissionCode } from '../permissions';
import type { CreateNavigationItemInput, UpdateNavigationItemInput } from './navigation-registry.types';

const KEY=/^[A-Z][A-Z0-9_.-]*$/; type D={field:string;message:string};
const record=(v:unknown):v is Record<string,unknown>=>typeof v==='object'&&v!==null&&!Array.isArray(v);
function uuid(v:string,field:string){const x=v.trim().toLowerCase();if(!isValidUuid(x))throw AppError.validation('Request validation failed.',[{field,message:`${field} must be a valid UUID.`}]);return x}
export const parseNavigationClientIdParam=(v:string)=>uuid(v,'clientId');
export const parseNavigationBuildingIdParam=(v:string)=>uuid(v,'buildingId');
export const parseNavigationItemIdParam=(v:string)=>uuid(v,'navigationItemId');
function code(v:unknown,field:string,d:D[],required=false):string|null|undefined{if(v===undefined)return required?(d.push({field,message:`${field} is required.`}),undefined):undefined;if(v===null||v==='')return null;if(typeof v!=='string'){d.push({field,message:`${field} must be a string or null.`});return undefined}const x=v.trim().toUpperCase();if(!KEY.test(x)||x.length>100){d.push({field,message:`${field} is invalid.`});return undefined}return x}
function text(v:unknown,field:string,max:number,d:D[],required=false){if(v===undefined)return required?(d.push({field,message:`${field} is required.`}),undefined):undefined;if(typeof v!=='string'||v.trim()===''){d.push({field,message:`${field} must be a non-empty string.`});return undefined}const x=v.trim();if(x.length>max||/[\u0000-\u001f]/.test(x)){d.push({field,message:`${field} is invalid.`});return undefined}return x}
export function parseCreateNavigationItemBody(body:unknown):CreateNavigationItemInput{if(!record(body))throw AppError.validation('Request validation failed.',[{field:'body',message:'Request body must be a JSON object.'}]);const d:D[]=[];for(const f of Object.keys(body))if(!['navigationKey','label','routeReference','parentNavigationKey','displayOrder','moduleKey','featureKey','permissionCode','enabled'].includes(f))d.push({field:f,message:`${f} is not allowed.`});const navigationKey=code(body.navigationKey,'navigationKey',d,true);const label=text(body.label,'label',160,d,true);const routeReference=text(body.routeReference,'routeReference',512,d,true);const parentNavigationKey=code(body.parentNavigationKey,'parentNavigationKey',d);let moduleKey:string|null|undefined;if(body.moduleKey!==undefined&&body.moduleKey!==null&&body.moduleKey!==''){if(typeof body.moduleKey!=='string'){d.push({field:'moduleKey',message:'moduleKey must be a string or null.'})}else{const x=normalizeModuleCode(body.moduleKey);if(!isValidModuleCode(x))d.push({field:'moduleKey',message:'moduleKey is invalid.'});else moduleKey=x}}else if(body.moduleKey===null||body.moduleKey==='')moduleKey=null;const featureKey=code(body.featureKey,'featureKey',d);let permissionCode:string|null|undefined;if(body.permissionCode!==undefined&&body.permissionCode!==null&&body.permissionCode!==''){if(typeof body.permissionCode!=='string'){d.push({field:'permissionCode',message:'permissionCode must be a string or null.'})}else{const x=normalizePermissionCode(body.permissionCode);if(!isValidPermissionCode(x))d.push({field:'permissionCode',message:'permissionCode is invalid.'});else permissionCode=x}}else if(body.permissionCode===null||body.permissionCode==='')permissionCode=null;const displayOrder=body.displayOrder===undefined?0:body.displayOrder;if(!Number.isInteger(displayOrder)||Number(displayOrder)<0)d.push({field:'displayOrder',message:'displayOrder must be an integer >= 0.'});const enabled=body.enabled===undefined?true:body.enabled;if(typeof enabled!=='boolean')d.push({field:'enabled',message:'enabled must be a boolean.'});if(featureKey&&!moduleKey)d.push({field:'moduleKey',message:'moduleKey is required when featureKey is set.'});if(parentNavigationKey&&navigationKey&&parentNavigationKey===navigationKey)d.push({field:'parentNavigationKey',message:'Navigation item cannot be its own parent.'});if(d.length||!navigationKey||!label||!routeReference)throw AppError.validation('Request validation failed.',d);return{navigationKey,label,routeReference,parentNavigationKey:parentNavigationKey??null,displayOrder:Number(displayOrder),moduleKey:moduleKey??null,featureKey:featureKey??null,permissionCode:permissionCode??null,enabled:enabled as boolean}}
export function parseUpdateNavigationItemBody(body:unknown):UpdateNavigationItemInput{if(!record(body))throw AppError.validation('Request validation failed.',[{field:'body',message:'Request body must be a JSON object.'}]);const d:D[]=[];for(const f of Object.keys(body))if(!['label','routeReference','displayOrder','enabled'].includes(f))d.push({field:f,message:`${f} is immutable or not allowed.`});const label=body.label===undefined?undefined:text(body.label,'label',160,d,true);const routeReference=body.routeReference===undefined?undefined:text(body.routeReference,'routeReference',512,d,true);const displayOrder=body.displayOrder;if(displayOrder!==undefined&&(!Number.isInteger(displayOrder)||Number(displayOrder)<0))d.push({field:'displayOrder',message:'displayOrder must be an integer >= 0.'});const enabled=body.enabled;if(enabled!==undefined&&typeof enabled!=='boolean')d.push({field:'enabled',message:'enabled must be a boolean.'});if(!Object.keys(body).length)d.push({field:'body',message:'At least one field is required.'});if(d.length)throw AppError.validation('Request validation failed.',d);return{...(label!==undefined?{label}:{}),...(routeReference!==undefined?{routeReference}:{}),...(displayOrder!==undefined?{displayOrder:Number(displayOrder)}:{}),...(enabled!==undefined?{enabled:enabled as boolean}:{})}}
