import{buildingNotFoundError,buildingRepository}from'../buildings';import{contextAccessService}from'../context-access';import{assertActiveAllowedCurrencyCommand}from'../client-monetary-contexts';import{recordOperationalEvent}from'../operational-events';import{propertyNotFoundError,propertyRepository}from'../properties';import{vendorServiceCostRepository}from'../vendor-service-costs';import{basicExpenseAmountMismatchError,basicExpenseCancelNotAllowedError,basicExpenseContextInvalidError,basicExpenseCurrencyImmutableError,basicExpenseCurrencyRequiredError,basicExpenseFinalizedProtectedError,basicExpenseNotDraftError,basicExpenseNotFoundError,basicExpenseNumberExistsError}from'./basic-expense.errors';import{basicExpenseRepository}from'./basic-expense.repository';import type{BasicExpenseFilters,BasicExpenseRecord,CreateBasicExpenseInput,NewBasicExpense,PublicBasicExpense,UpdateBasicExpenseInput}from'./basic-expense.types';const out=(r:BasicExpenseRecord):PublicBasicExpense=>({...r,amount:Number(r.amount),finalizedAt:r.finalizedAt?.toISOString()??null,cancelledAt:r.cancelledAt?.toISOString()??null,createdAt:r.createdAt.toISOString(),updatedAt:r.updatedAt.toISOString()});const unique=(e:unknown)=>typeof e==='object'&&e!==null&&'code'in e&&e.code==='23505';async function buildingContext(id:string,u:string){await contextAccessService.assertBuildingAccess(u,id);const b=await buildingRepository.findById(id);if(!b)throw buildingNotFoundError();const p=await propertyRepository.findById(b.propertyId);if(!p)throw propertyNotFoundError();return p.clientId}async function checkCost(id:string|null,buildingId:string,amount:number){if(!id)return;const c=await vendorServiceCostRepository.findById(id);if(!c||c.buildingId!==buildingId||c.status!=='FINALIZED')throw basicExpenseContextInvalidError();if(Number(c.costAmount)!==amount)throw basicExpenseAmountMismatchError()}async function load(id:string,u:string){const r=await basicExpenseRepository.findById(id);if(!r)throw basicExpenseNotFoundError();await contextAccessService.assertBuildingAccess(u,r.buildingId);return r}
export async function createBasicExpense(i:CreateBasicExpenseInput,u:string){const clientId=await buildingContext(i.buildingId,u),costId=i.vendorServiceCostId??null;await checkCost(costId,i.buildingId,i.amount);await assertActiveAllowedCurrencyCommand(clientId,i.currencyCode);const n:NewBasicExpense={clientId,buildingId:i.buildingId,expenseNumber:i.expenseNumber,expenseCategory:i.expenseCategory,description:i.description,amount:i.amount,currencyCode:i.currencyCode,expenseDate:i.expenseDate,vendorServiceCostId:costId,notes:i.notes?.trim()||null,createdByUserId:u};try{const r=await basicExpenseRepository.create(n);await recordOperationalEvent({clientId,buildingId:r.buildingId,eventType:'BASIC_EXPENSE_CREATED',entityType:'BASIC_EXPENSE',entityId:r.id,actorUserId:u,summary:`Basic Expense ${r.expenseNumber} created as draft.`,metadata:{vendorServiceCostId:r.vendorServiceCostId,amount:r.amount,currencyCode:r.currencyCode}});return out(r)}catch(e){if(unique(e))throw basicExpenseNumberExistsError();throw e}}
export async function getBasicExpense(id:string,u:string){return out(await load(id,u))}export async function listBasicExpenses(f:BasicExpenseFilters,u:string){if(f.buildingId)await contextAccessService.assertBuildingAccess(u,f.buildingId);return(await basicExpenseRepository.list(f,await contextAccessService.getAccessibleBuildingIds(u))).map(out)}
export async function updateBasicExpense(id:string,i:UpdateBasicExpenseInput,u:string){const r=await load(id,u);if(r.status==='FINALIZED')throw basicExpenseFinalizedProtectedError();if(r.status!=='DRAFT')throw basicExpenseNotDraftError();
/* CUR-02 PART 01: historical NULL stays NULL unless the amount changes, which
requires an explicit governed currency; an existing snapshot is immutable. */
if(r.currencyCode===null){if(i.amount!==undefined&&i.currencyCode===undefined)throw basicExpenseCurrencyRequiredError();if(i.currencyCode!==undefined)await assertActiveAllowedCurrencyCommand(r.clientId,i.currencyCode)}
else if(i.currencyCode!==undefined&&i.currencyCode!==r.currencyCode)throw basicExpenseCurrencyImmutableError();
await checkCost(r.vendorServiceCostId,r.buildingId,i.amount??Number(r.amount));const x=await basicExpenseRepository.update(id,i,u);if(!x)throw basicExpenseNotDraftError();return out(x)}
export async function finalizeBasicExpense(id:string,u:string){const r=await load(id,u);if(r.status==='FINALIZED')throw basicExpenseFinalizedProtectedError();if(r.status!=='DRAFT')throw basicExpenseNotDraftError();await checkCost(r.vendorServiceCostId,r.buildingId,Number(r.amount));const x=await basicExpenseRepository.finalize(id,u);if(!x)throw basicExpenseFinalizedProtectedError();return out(x)}
export async function cancelBasicExpense(id:string,u:string){const r=await load(id,u);if(r.status==='CANCELLED')throw basicExpenseCancelNotAllowedError();const x=await basicExpenseRepository.cancel(id,u);if(!x)throw basicExpenseCancelNotAllowedError();return out(x)}export const basicExpenseService={cancelBasicExpense,createBasicExpense,finalizeBasicExpense,getBasicExpense,listBasicExpenses,updateBasicExpense};
