import{contextAccessService}from'../context-access';import{assertActiveAllowedCurrencyCommand}from'../client-monetary-contexts';import{recordOperationalEvent}from'../operational-events';import{serviceRequestRepository}from'../service-requests';import{vendorWorkRepository}from'../vendor-work';import{vendorNotFoundError,vendorRepository}from'../vendors';import{vendorServiceCostCancelNotAllowedError,vendorServiceCostContextInvalidError,vendorServiceCostCurrencyImmutableError,vendorServiceCostCurrencyRequiredError,vendorServiceCostFinalizedProtectedError,vendorServiceCostNotDraftError,vendorServiceCostNotFoundError}from'./vendor-service-cost.errors';import{vendorServiceCostRepository}from'./vendor-service-cost.repository';import type{CreateVendorServiceCostInput,NewVendorServiceCost,PublicVendorServiceCost,UpdateVendorServiceCostInput,VendorServiceCostFilters,VendorServiceCostRecord}from'./vendor-service-cost.types';
const out=(r:VendorServiceCostRecord):PublicVendorServiceCost=>({...r,costAmount:Number(r.costAmount),finalizedAt:r.finalizedAt?.toISOString()??null,cancelledAt:r.cancelledAt?.toISOString()??null,createdAt:r.createdAt.toISOString(),updatedAt:r.updatedAt.toISOString()});async function load(id:string,u:string){const r=await vendorServiceCostRepository.findById(id);if(!r)throw vendorServiceCostNotFoundError();await contextAccessService.assertBuildingAccess(u,r.buildingId);return r}
export async function createVendorServiceCost(i:CreateVendorServiceCostInput,u:string):Promise<PublicVendorServiceCost>{const vendor=await vendorRepository.findById(i.vendorId);if(!vendor)throw vendorNotFoundError();await contextAccessService.assertBuildingAccess(u,i.buildingId);if(vendor.status!=='ACTIVE')throw vendorServiceCostContextInvalidError();let clientId=vendor.clientId,vendorWorkId:null|string=null,workOrderId:null|string=null,serviceRequestId:null|string=null;if(i.contextType==='VENDOR_WORK'){const w=await vendorWorkRepository.findById(i.contextId);if(!w||w.vendorId!==vendor.id||w.buildingId!==i.buildingId)throw vendorServiceCostContextInvalidError();vendorWorkId=w.id;workOrderId=w.workOrderId}else{const s=await serviceRequestRepository.findById(i.contextId);if(!s||s.vendorId!==vendor.id||s.buildingId!==i.buildingId||s.clientId!==vendor.clientId||s.status!=='OPEN')throw vendorServiceCostContextInvalidError();serviceRequestId=s.id}await assertActiveAllowedCurrencyCommand(clientId,i.currencyCode);const r=await vendorServiceCostRepository.create({clientId,buildingId:i.buildingId,vendorId:vendor.id,contextType:i.contextType,vendorWorkId,workOrderId,serviceRequestId,costAmount:i.costAmount,costDate:i.costDate,costType:i.costType,costCategory:i.costCategory,currencyCode:i.currencyCode,reference:i.reference?.trim()||null,notes:i.notes?.trim()||null,createdByUserId:u});await recordOperationalEvent({clientId,buildingId:r.buildingId,eventType:'VENDOR_SERVICE_COST_CREATED',entityType:'VENDOR_SERVICE_COST',entityId:r.id,actorUserId:u,summary:'Vendor / Service Cost created as draft.',metadata:{vendorId:r.vendorId,contextType:r.contextType,vendorWorkId:r.vendorWorkId,serviceRequestId:r.serviceRequestId,currencyCode:r.currencyCode}});return out(r)}
export async function getVendorServiceCost(id:string,u:string){return out(await load(id,u))}export async function listVendorServiceCosts(f:VendorServiceCostFilters,u:string){if(f.buildingId)await contextAccessService.assertBuildingAccess(u,f.buildingId);return(await vendorServiceCostRepository.list(f,await contextAccessService.getAccessibleBuildingIds(u))).map(out)}
export async function updateVendorServiceCost(id:string,i:UpdateVendorServiceCostInput,u:string){const current=await load(id,u);if(current.status==='FINALIZED')throw vendorServiceCostFinalizedProtectedError();if(current.status!=='DRAFT')throw vendorServiceCostNotDraftError();
/* CUR-02 PART 01: historical NULL stays NULL unless a monetary amount changes,
which requires an explicit governed currency; an existing snapshot is immutable. */
if(current.currencyCode===null){if(i.costAmount!==undefined&&i.currencyCode===undefined)throw vendorServiceCostCurrencyRequiredError();if(i.currencyCode!==undefined)await assertActiveAllowedCurrencyCommand(current.clientId,i.currencyCode)}
else if(i.currencyCode!==undefined&&i.currencyCode!==current.currencyCode)throw vendorServiceCostCurrencyImmutableError();
const r=await vendorServiceCostRepository.update(id,i,u);if(!r)throw vendorServiceCostNotDraftError();return out(r)}
export async function finalizeVendorServiceCost(id:string,u:string){const current=await load(id,u);if(current.status==='FINALIZED')throw vendorServiceCostFinalizedProtectedError();if(current.status!=='DRAFT')throw vendorServiceCostNotDraftError();const r=await vendorServiceCostRepository.finalize(id,u);if(!r)throw vendorServiceCostFinalizedProtectedError();await recordOperationalEvent({clientId:r.clientId,buildingId:r.buildingId,eventType:'VENDOR_SERVICE_COST_FINALIZED',entityType:'VENDOR_SERVICE_COST',entityId:r.id,actorUserId:u,summary:'Vendor / Service Cost finalized.'});return out(r)}
export async function cancelVendorServiceCost(id:string,u:string){const current=await load(id,u);if(current.status==='CANCELLED')throw vendorServiceCostCancelNotAllowedError();const r=await vendorServiceCostRepository.cancel(id,u);if(!r)throw vendorServiceCostCancelNotAllowedError();return out(r)}
export const vendorServiceCostService={cancelVendorServiceCost,createVendorServiceCost,finalizeVendorServiceCost,getVendorServiceCost,listVendorServiceCosts,updateVendorServiceCost};
