import{randomUUID}from'node:crypto';import type{PoolClient}from'pg';import{getPool,withTransaction}from'../../database';import type{NewVendorServiceCost,UpdateVendorServiceCostInput,VendorServiceCostFilters,VendorServiceCostRecord}from'./vendor-service-cost.types';
const S=`id,client_id AS "clientId",building_id AS "buildingId",vendor_id AS "vendorId",context_type AS "contextType",vendor_work_id AS "vendorWorkId",work_order_id AS "workOrderId",service_request_id AS "serviceRequestId",cost_amount::text AS "costAmount",cost_date::text AS "costDate",cost_type AS "costType",cost_category AS "costCategory",currency_code AS "currencyCode",status,reference,notes,created_by_user_id AS "createdByUserId",finalized_at AS "finalizedAt",finalized_by_user_id AS "finalizedByUserId",cancelled_at AS "cancelledAt",cancelled_by_user_id AS "cancelledByUserId",created_at AS "createdAt",updated_at AS "updatedAt"`;type Action='CREATED'|'UPDATED'|'FINALIZED'|'CANCELLED';
async function hist(c:PoolClient,r:VendorServiceCostRecord,a:Action,u:string){await c.query(`INSERT INTO vendor_service_cost_history(id,vendor_service_cost_id,action,cost_amount,cost_date,cost_type,cost_category,currency_code,status,reference,notes,changed_by_user_id)VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)`,[randomUUID(),r.id,a,r.costAmount,r.costDate,r.costType,r.costCategory,r.currencyCode,r.status,r.reference,r.notes,u])}
async function create(i:NewVendorServiceCost){return withTransaction(async c=>{const r=await c.query<VendorServiceCostRecord>(`INSERT INTO vendor_service_costs(id,client_id,building_id,vendor_id,context_type,vendor_work_id,work_order_id,service_request_id,cost_amount,cost_date,cost_type,cost_category,currency_code,reference,notes,created_by_user_id)VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16)RETURNING ${S}`,[randomUUID(),i.clientId,i.buildingId,i.vendorId,i.contextType,i.vendorWorkId,i.workOrderId,i.serviceRequestId,i.costAmount,i.costDate,i.costType,i.costCategory,i.currencyCode,i.reference,i.notes,i.createdByUserId]);await hist(c,r.rows[0],'CREATED',i.createdByUserId);return r.rows[0]})}
async function findById(id:string){const r=await getPool().query<VendorServiceCostRecord>(`SELECT ${S} FROM vendor_service_costs WHERE id=$1`,[id]);return r.rows[0]??null}
async function list(f:VendorServiceCostFilters,ids:string[]){if(!ids.length)return[];const v:unknown[]=[ids],w=['building_id=ANY($1::uuid[])'];for(const[k,col]of[['vendorId','vendor_id'],['buildingId','building_id'],['workOrderId','work_order_id'],['status','status']]as[keyof VendorServiceCostFilters,string][])if(f[k]!==undefined){v.push(f[k]);w.push(`${col}=$${v.length}`)}if(f.costDateFrom){v.push(f.costDateFrom);w.push(`cost_date>=$${v.length}::date`)}if(f.costDateTo){v.push(f.costDateTo);w.push(`cost_date<=$${v.length}::date`)}return(await getPool().query<VendorServiceCostRecord>(`SELECT ${S} FROM vendor_service_costs WHERE ${w.join(' AND ')} ORDER BY cost_date DESC,created_at DESC`,v)).rows}
async function update(id:string,i:UpdateVendorServiceCostInput,u:string){return withTransaction(async c=>{const v:unknown[]=[],sets:string[]=[];for(const[k,col]of[['costAmount','cost_amount'],['costDate','cost_date'],['costType','cost_type'],['costCategory','cost_category'],['currencyCode','currency_code'],['reference','reference'],['notes','notes']]as[keyof UpdateVendorServiceCostInput,string][])if(i[k]!==undefined){v.push(i[k]);sets.push(`${col}=$${v.length}`)}if(!sets.length)return findById(id);v.push(id);sets.push('updated_at=NOW()');const r=await c.query<VendorServiceCostRecord>(`UPDATE vendor_service_costs SET ${sets.join(',')} WHERE id=$${v.length} AND status='DRAFT' RETURNING ${S}`,v),x=r.rows[0]??null;if(x)await hist(c,x,'UPDATED',u);return x})}
async function finalize(id:string,u:string){return transition(id,u,'FINALIZED','finalized_at=NOW(),finalized_by_user_id=$2','FINALIZED')}
async function cancel(id:string,u:string){return transition(id,u,'CANCELLED','cancelled_at=NOW(),cancelled_by_user_id=$2','CANCELLED')}
async function transition(id:string,u:string,status:string,stamps:string,action:Action){return withTransaction(async c=>{const allowed=status==='FINALIZED'?"status='DRAFT'":"status IN('DRAFT','FINALIZED')";const r=await c.query<VendorServiceCostRecord>(`UPDATE vendor_service_costs SET status=$3,${stamps},updated_at=NOW() WHERE id=$1 AND ${allowed} RETURNING ${S}`,[id,u,status]),x=r.rows[0]??null;if(x)await hist(c,x,action,u);return x})}
export const vendorServiceCostRepository={cancel,create,finalize,findById,list,update};
