import{AppError}from'../../shared/errors';import{isValidUuid}from'../clients';
import{PAYMENT_RECEIPT_STATUSES,isPaymentReceiptStatus,type IssuePaymentReceiptInput,type PaymentReceiptFilters,type PaymentReceiptStatus}from'./payment-receipt.types';
type Detail={field:string;message:string};const NUMBER=/^[A-Z0-9][A-Z0-9_\-/]{1,63}$/,METHOD=/^[A-Z][A-Z0-9_]{0,63}$/;
function record(v:unknown):v is Record<string,unknown>{return typeof v==='object'&&v!==null&&!Array.isArray(v)}
function fail(d:Detail[]):never{throw AppError.validation('Request validation failed.',d)}
const parseId=(raw:string,field:string)=>{const v=raw.trim().toLowerCase();if(!isValidUuid(v))fail([{field,message:`${field} must be a valid UUID.`}]);return v};
export const parsePaymentReceiptIdParam=(raw:string)=>parseId(raw,'paymentReceiptId');export const parsePaymentReceiptInvoiceIdParam=(raw:string)=>parseId(raw,'invoiceId');
export function parseIssuePaymentReceiptBody(body:unknown):Omit<IssuePaymentReceiptInput,'invoiceId'>{if(!record(body))fail([{field:'body',message:'Request body must be a JSON object.'}]);const d:Detail[]=[];
 const receiptNumber=readNumber(body.receiptNumber,d),receivedAmount=readAmount(body.receivedAmount,d),receivedAt=readDate(body.receivedAt,'receivedAt',d);
 const paymentReference=readString(body.paymentReference,'paymentReference',255,d),paymentMethod=readMethod(body.paymentMethod,d),notes=readString(body.notes,'notes',2000,d);
 if(!receivedAt)d.push({field:'receivedAt',message:'receivedAt is required and must be a valid ISO-8601 timestamp.'});
 if(!receiptNumber||receivedAmount===undefined||!receivedAt||d.length)fail(d);return{receiptNumber,receivedAmount,receivedAt,...(paymentReference!==undefined?{paymentReference}:{}),...(paymentMethod!==undefined?{paymentMethod}:{}),...(notes!==undefined?{notes}:{})};}
export function parsePaymentReceiptFilters(q:unknown):PaymentReceiptFilters{if(!record(q))return{};const d:Detail[]=[];const tenantCompanyId=readId(q.tenantCompanyId,'tenantCompanyId',false,d),invoiceId=readId(q.invoiceId,'invoiceId',false,d),buildingId=readId(q.buildingId,'buildingId',false,d),status=readStatus(q.status,d),receivedFrom=readDate(q.receivedFrom,'receivedFrom',d),receivedTo=readDate(q.receivedTo,'receivedTo',d);if(receivedFrom&&receivedTo&&receivedTo<receivedFrom)d.push({field:'receivedTo',message:'receivedTo must be the same as or after receivedFrom.'});if(d.length)fail(d);return{...(tenantCompanyId?{tenantCompanyId}:{}),...(invoiceId?{invoiceId}:{}),...(buildingId?{buildingId}:{}),...(status?{status}:{}),...(receivedFrom?{receivedFrom}:{}),...(receivedTo?{receivedTo}:{})};}
function readId(v:unknown,field:string,required:boolean,d:Detail[]):string|undefined{if(v===undefined&&!required)return undefined;if(typeof v!=='string'||!isValidUuid(v.trim())){d.push({field,message:`${field} ${required?'is required and ':''}must be a valid UUID.`});return undefined}return v.trim().toLowerCase()}
function readNumber(v:unknown,d:Detail[]):string|undefined{if(typeof v!=='string'){d.push({field:'receiptNumber',message:'receiptNumber is required.'});return undefined}const n=v.trim().toUpperCase();if(!NUMBER.test(n)){d.push({field:'receiptNumber',message:'receiptNumber has an invalid format.'});return undefined}return n}
function readAmount(v:unknown,d:Detail[]):number|undefined{if(typeof v!=='number'||!Number.isFinite(v)||v<=0||v>999_999_999_999.999999){d.push({field:'receivedAmount',message:'receivedAmount must be a finite positive number within the supported range.'});return undefined}if(Math.abs(v*1e6-Math.round(v*1e6))>1e-5){d.push({field:'receivedAmount',message:'receivedAmount must have at most six decimal places.'});return undefined}return v}
function readDate(v:unknown,field:string,d:Detail[]):Date|undefined{if(v===undefined)return undefined;if(typeof v!=='string'||!v.trim()){d.push({field,message:`${field} must be a valid ISO-8601 timestamp.`});return undefined}const date=new Date(v);if(Number.isNaN(date.getTime())){d.push({field,message:`${field} must be a valid ISO-8601 timestamp.`});return undefined}return date}
function readString(v:unknown,field:string,max:number,d:Detail[]):string|null|undefined{if(v===undefined)return undefined;if(v===null)return null;if(typeof v!=='string'){d.push({field,message:`${field} must be a string or null.`});return undefined}const s=v.trim();if(!s)return null;if(s.length>max){d.push({field,message:`${field} must be at most ${max} characters.`});return undefined}return s}
function readMethod(v:unknown,d:Detail[]):string|null|undefined{const value=readString(v,'paymentMethod',64,d);if(typeof value==='string'){const n=value.toUpperCase();if(!METHOD.test(n)){d.push({field:'paymentMethod',message:'paymentMethod must be a valid data-driven code.'});return undefined}return n}return value}
function readStatus(v:unknown,d:Detail[]):PaymentReceiptStatus|undefined{if(v===undefined)return undefined;if(!isPaymentReceiptStatus(v)){d.push({field:'status',message:`status must be one of: ${PAYMENT_RECEIPT_STATUSES.join(', ')}.`});return undefined}return v}
