import{contextAccessService}from'../context-access';import{invoicePaymentStatusRepository}from'../invoice-payment-status';import{recordOperationalEvent}from'../operational-events';import{tenantInvoiceNotFoundError,tenantInvoiceRepository}from'../tenant-invoices';
import{paymentReceiptAlreadyVoidError,paymentReceiptAmountInvalidError,paymentReceiptContextInvalidError,paymentReceiptDuplicateReferenceError,paymentReceiptNotFoundError,paymentReceiptNumberExistsError}from'./payment-receipt.errors';
import{paymentReceiptRepository}from'./payment-receipt.repository';import type{IssuePaymentReceiptInput,NewPaymentReceipt,PaymentReceiptFilters,PaymentReceiptRecord,PublicPaymentReceipt}from'./payment-receipt.types';
function out(r:PaymentReceiptRecord):PublicPaymentReceipt{return{...r,receivedAmount:Number(r.receivedAmount),receivedAt:r.receivedAt.toISOString(),voidedAt:r.voidedAt?.toISOString()??null,createdAt:r.createdAt.toISOString(),updatedAt:r.updatedAt.toISOString()}}
function pgInfo(e:unknown):{code?:string;constraint?:string}{return typeof e==='object'&&e!==null?e as{code?:string;constraint?:string}:{}}
async function load(id:string,actor:string){const r=await paymentReceiptRepository.findById(id);if(!r)throw paymentReceiptNotFoundError();await contextAccessService.assertBuildingAccess(actor,r.buildingId);return r}
export async function issuePaymentReceipt(input:IssuePaymentReceiptInput,actor:string):Promise<PublicPaymentReceipt>{
 const invoice=await tenantInvoiceRepository.findById(input.invoiceId);if(!invoice)throw tenantInvoiceNotFoundError();await contextAccessService.assertBuildingAccess(actor,invoice.buildingId);
 if(invoice.status!=='FINALIZED')throw paymentReceiptContextInvalidError();
 const payment=await invoicePaymentStatusRepository.findByInvoiceId(invoice.id);
 if(!payment||payment.invoiceId!==invoice.id||payment.clientId!==invoice.clientId||payment.tenantCompanyId!==invoice.tenantCompanyId||payment.buildingId!==invoice.buildingId||Number(payment.paidAmount)<=0||payment.paymentStatus==='CANCELLED')throw paymentReceiptContextInvalidError();
 const already=Number(await paymentReceiptRepository.sumIssuedForPaymentStatus(payment.id));
 if(input.receivedAmount<=0||already+input.receivedAmount>Number(payment.paidAmount))throw paymentReceiptAmountInvalidError();
 const payload:NewPaymentReceipt={receiptNumber:input.receiptNumber,invoiceId:invoice.id,invoicePaymentStatusId:payment.id,clientId:invoice.clientId,tenantCompanyId:invoice.tenantCompanyId,buildingId:invoice.buildingId,receivedAmount:input.receivedAmount,receivedAt:input.receivedAt,paymentReference:input.paymentReference?.trim()||payment.paymentReference||null,paymentMethod:input.paymentMethod?.trim()||null,notes:input.notes?.trim()||null,issuedByUserId:actor};
 try{const record=await paymentReceiptRepository.createIfCovered(payload);if(!record)throw paymentReceiptAmountInvalidError();
  await recordOperationalEvent({clientId:record.clientId,buildingId:record.buildingId,eventType:'PAYMENT_RECEIPT_ISSUED',entityType:'PAYMENT_RECEIPT',entityId:record.id,actorUserId:actor,summary:`Payment Receipt ${record.receiptNumber} issued.`,metadata:{invoiceId:record.invoiceId,invoicePaymentStatusId:record.invoicePaymentStatusId,receivedAmount:record.receivedAmount}});return out(record);
 }catch(error){const info=pgInfo(error);if(info.code==='23505'){if(info.constraint==='payment_receipts_number_unique')throw paymentReceiptNumberExistsError();throw paymentReceiptDuplicateReferenceError()}throw error;}
}
export async function getPaymentReceipt(id:string,actor:string):Promise<PublicPaymentReceipt>{return out(await load(id,actor))}
export async function listPaymentReceipts(filters:PaymentReceiptFilters,actor:string):Promise<PublicPaymentReceipt[]>{if(filters.buildingId)await contextAccessService.assertBuildingAccess(actor,filters.buildingId);const ids=await contextAccessService.getAccessibleBuildingIds(actor);return(await paymentReceiptRepository.list(filters,ids)).map(out)}
export async function voidPaymentReceipt(id:string,actor:string):Promise<PublicPaymentReceipt>{const current=await load(id,actor);if(current.status!=='ISSUED')throw paymentReceiptAlreadyVoidError();const record=await paymentReceiptRepository.voidReceipt(id,actor);if(!record)throw paymentReceiptAlreadyVoidError();await recordOperationalEvent({clientId:record.clientId,buildingId:record.buildingId,eventType:'PAYMENT_RECEIPT_VOIDED',entityType:'PAYMENT_RECEIPT',entityId:record.id,actorUserId:actor,summary:`Payment Receipt ${record.receiptNumber} voided.`});return out(record)}
export const paymentReceiptService={getPaymentReceipt,issuePaymentReceipt,listPaymentReceipts,voidPaymentReceipt};
