import type {
  UtilityMeterReadingSource,
  UtilityMeterReadingType,
} from '../utility-meter-readings';

/**
 * CR-BE-RN12-METER-FIELD-01 PART 01 — mobile field meter-reading contract.
 *
 * The technician-safe WRITE that records one canonical BE-18E Meter Reading
 * against the Reading Due a field actor is actually assigned to, plus the
 * canonical reads that make the outcome of that write definitively knowable.
 *
 * ONE READING DUE ⇒ AT MOST ONE FIELD READING
 * -------------------------------------------
 * The field execution identity is the Reading Due, never a bare meter. The
 * canonical domain already enforces the cardinality this command needs:
 * `utility_reading_dues.meter_reading_id` is `UNIQUE`, and
 * `utility_reading_due_state_check` requires `status='DUE' ⇒ meter_reading_id
 * IS NULL` and `status='COMPLETED' ⇒ meter_reading_id IS NOT NULL`. Combined
 * with `repo.complete`'s `WHERE status='DUE'` guard, exactly one transition can
 * ever win, so one due resolves to at most one authoritative reading.
 *
 * WHAT THIS MODULE ADDS — AND WHAT IT DELIBERATELY DOES NOT
 * ---------------------------------------------------------
 * It adds a field ADDRESSING and AUTHORITY layer over the existing canonical
 * write (`recordUtilityMeterReading`) and the existing canonical completion
 * (`completeUtilityReadingDue`). It does NOT add a second reading store, a
 * second event type, a second completion semantic, or any field-only variant of
 * either. A field submission produces exactly the rows a management submission
 * would produce for the same facts.
 *
 * Out of scope for PART 01, by design: evidence, OCR candidates, abnormality
 * evaluation, recheck/correction, `availableActions`, QR resolution,
 * mobile-sync resource kinds, and any consumption / delta / billing
 * calculation. BE-18G consumption remains a backend downstream concern.
 *
 * NO CLIENT PREVIOUS-READING AUTHORITY
 * ------------------------------------
 * The body carries no `previousReadingId` and no `previousReadingValue`. Any
 * later consumption chain resolves chronology on the backend from the persisted
 * readings; a field client is never the authority on which reading is previous.
 */

/**
 * The complete allowlist of the field submit body.
 *
 * `readingAt` stays caller-supplied because canonical BE-18 treats capture time
 * as a domain fact, and must: `completeUtilityReadingDue` requires
 * `reading.readingAt` to fall between `due.periodStart` and `due.periodEnd`. A
 * server-derived `NOW()` would fall outside that window for any OVERDUE due and
 * make completion impossible, so the field client states when the meter was
 * actually read. Everything else about the reading is server-derived.
 */
export const MOBILE_UTILITY_METER_READING_BODY_FIELDS = [
  'readingValue',
  'readingAt',
  'notes',
] as const;

/**
 * Authority facts a field client must never supply. Each is refused with an
 * explicit reason rather than silently dropped, so a client cannot discover by
 * trial that one of them was quietly ignored.
 */
export const MOBILE_UTILITY_METER_READING_DERIVED_FIELDS: Readonly<
  Record<string, string>
> = {
  readingDueId: 'readingDueId comes from the route path.',
  meterId: 'meterId is derived from the Reading Due.',
  uomId: 'uomId is the Meter’s own configured unit (BE-18A).',
  utilityType: 'utilityType is derived from the Meter.',
  clientId: 'clientId is derived from the Meter.',
  buildingId: 'buildingId is derived from the Meter.',
  recordedByUserId: 'recordedByUserId is the authenticated actor.',
  source: 'source is server-derived for a technician field capture.',
  readingType: 'readingType is server-derived for a technician field capture.',
  decimalPrecision:
    'decimalPrecision is governed server-side by BE-18B configuration.',
  tenantAssignmentId: 'tenantAssignmentId is the Meter’s live BE-18D assignment.',
  tenantCompanyId: 'tenantCompanyId is the Meter’s live BE-18D assignment.',
  meterReadingBindingId:
    'meterReadingBindingId belongs to the BE-10C engineering workflow.',
  formInstanceId: 'formInstanceId belongs to the BE-10C engineering workflow.',
  previousReadingId:
    'previousReadingId is not a field input; chronology is resolved on the backend.',
  previousReadingValue:
    'previousReadingValue is not a field input; chronology is resolved on the backend.',
  previousReading:
    'previousReading is not a field input; chronology is resolved on the backend.',
  consumption:
    'consumption is BE-18G and is never calculated by a field submission.',
  delta: 'delta is BE-18G and is never calculated by a field submission.',
  difference:
    'difference is BE-18G and is never calculated by a field submission.',
  usage: 'usage is BE-18G and is never calculated by a field submission.',
  id: 'id is generated by the backend.',
  createdAt: 'createdAt is generated by the backend.',
  updatedAt: 'updatedAt is generated by the backend.',
};

/** Parsed, normalized field submit body. */
export type MobileUtilityMeterReadingInput = {
  /** Canonical BE-18E constraint: `reading_value >= 0`. */
  readingValue: number;
  /** Capture time as a domain fact; must fall inside the due period. */
  readingAt: Date;
  notes?: string;
};

/**
 * Bounded mobile reading DTO.
 *
 * Exactly the canonical BE-18E facts a field workflow needs. Deliberately
 * excludes `clientId` / `buildingId` (the actor is already scoped to them),
 * `updatedAt` (readings are append-only, so it never diverges meaningfully),
 * the BE-18D tenant context and the BE-10C engineering linkage (management
 * provenance, not field workflow), and every `meter` / `uom` enrichment object
 * — PART 00's meter context is where a client reads meter identity.
 *
 * No tariff, rate, currency, amount, consumption, delta, abnormal evaluation or
 * OCR candidate appears here, and no `availableActions`: PARTs 02–03 own
 * command semantics, so freezing action tokens now would pre-empt them.
 */
export type MobileUtilityMeterReading = {
  id: string;
  meterId: string;
  uomId: string;
  readingValue: number;
  readingAt: string;
  source: UtilityMeterReadingSource;
  readingType: UtilityMeterReadingType;
  notes: string | null;
  recordedByUserId: string;
  createdAt: string;
};

/** Result of a field submit, distinguishing a first execution from a replay. */
export type MobileUtilityMeterReadingResult = {
  reading: MobileUtilityMeterReading;
};

/**
 * Server-defined idempotency operation key.
 *
 * Equals the operationId, matching the convention CR-BE-RN11-MATERIAL-FIELD-01
 * set with `recordMobileWorkOrderMaterialUsage`.
 */
export const RECORD_MOBILE_UTILITY_METER_READING_OPERATION_KEY =
  'recordMobileUtilityMeterReading';

/** Server-derived provenance for a technician field capture. */
export const MOBILE_FIELD_READING_SOURCE: UtilityMeterReadingSource = 'MANUAL';
export const MOBILE_FIELD_READING_TYPE: UtilityMeterReadingType = 'ACTUAL';
