import { randomUUID } from 'node:crypto';
import { getPool } from '../../database';
import type { CreateUtilityReadingDueInput, UtilityReadingDueFilters, UtilityReadingDueRecord } from './utility-reading-due.types';
const SELECT=`id,client_id AS "clientId",building_id AS "buildingId",meter_id AS "meterId",utility_type AS "utilityType",period_start AS "periodStart",period_end AS "periodEnd",due_at AS "dueAt",CASE WHEN status='DUE' AND due_at<NOW() THEN 'OVERDUE' ELSE status END AS status,schedule_definition_id AS "scheduleDefinitionId",generated_task_id AS "generatedTaskId",meter_reading_id AS "meterReadingId",completed_at AS "completedAt",completed_by_user_id AS "completedByUserId",cancelled_at AS "cancelledAt",cancelled_by_user_id AS "cancelledByUserId",cancellation_reason AS "cancellationReason",created_by_user_id AS "createdByUserId",created_at AS "createdAt",updated_at AS "updatedAt"`;
async function create(input:CreateUtilityReadingDueInput&{clientId:string;buildingId:string;utilityType:string;createdByUserId:string}){return(await getPool().query<UtilityReadingDueRecord>(`INSERT INTO utility_reading_dues(id,client_id,building_id,meter_id,utility_type,period_start,period_end,due_at,schedule_definition_id,generated_task_id,created_by_user_id)VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)RETURNING ${SELECT}`,[randomUUID(),input.clientId,input.buildingId,input.meterId,input.utilityType,input.periodStart,input.periodEnd,input.dueAt,input.scheduleDefinitionId??null,input.generatedTaskId??null,input.createdByUserId])).rows[0]}
async function findById(id:string){const r=await getPool().query<UtilityReadingDueRecord>(`SELECT ${SELECT} FROM utility_reading_dues WHERE id=$1`,[id]);return r.rows[0]??null}
function statusClause(status:string,index:number){if(status==='OVERDUE')return`status='DUE' AND due_at<NOW()`;if(status==='DUE')return`status='DUE' AND due_at>=NOW()`;return`status=$${index}`}
async function list(scope:{column:'meter_id'|'building_id'|'client_id';value:string},filters:UtilityReadingDueFilters,buildingIds?:string[]){const v:unknown[]=[scope.value],w=[`${scope.column}=$1`];if(buildingIds){if(!buildingIds.length)return[];v.push(buildingIds);w.push(`building_id=ANY($${v.length}::uuid[])`)}if(filters.status){const c=statusClause(filters.status,v.length+1);w.push(c);if(!['DUE','OVERDUE'].includes(filters.status))v.push(filters.status)}return(await getPool().query<UtilityReadingDueRecord>(`SELECT ${SELECT} FROM utility_reading_dues WHERE ${w.join(' AND ')} ORDER BY due_at,meter_id`,v)).rows}
async function complete(id:string,meterReadingId:string,userId:string){const r=await getPool().query<UtilityReadingDueRecord>(`UPDATE utility_reading_dues SET status='COMPLETED',meter_reading_id=$2,completed_at=NOW(),completed_by_user_id=$3,updated_at=NOW() WHERE id=$1 AND status='DUE' RETURNING ${SELECT}`,[id,meterReadingId,userId]);return r.rows[0]??null}
async function cancel(id:string,reason:string,userId:string){const r=await getPool().query<UtilityReadingDueRecord>(`UPDATE utility_reading_dues SET status='CANCELLED',cancelled_at=NOW(),cancelled_by_user_id=$3,cancellation_reason=$2,updated_at=NOW() WHERE id=$1 AND status='DUE' RETURNING ${SELECT}`,[id,reason,userId]);return r.rows[0]??null}
export const utilityReadingDueRepository={cancel,complete,create,findById,list};
