import { getPool } from '../../database';
import { contextAccessService } from '../context-access';
import { buildingAccessDeniedError } from '../context-access/context-access.errors';
import { recordOperationalEvent } from '../operational-events';
import { utilityMeterInactiveError, utilityMeterNotFoundError, utilityMeterRepository } from '../utility-meters';
import { utilityMeterReadingNotFoundError, utilityMeterReadingRepository } from '../utility-meter-readings';
import type { UtilityReadingDueExecutor } from './utility-reading-due.repository';
import { utilityReadingDueDuplicateError, utilityReadingDueInvalidScheduleError, utilityReadingDueNotFoundError, utilityReadingDueReadingMismatchError, utilityReadingDueTransitionError } from './utility-reading-due.errors';
import { utilityReadingDueRepository as repo } from './utility-reading-due.repository';
import type { CreateUtilityReadingDueInput, PublicUtilityReadingDue, UtilityReadingDueFilters, UtilityReadingDueRecord } from './utility-reading-due.types';
const out=(r:UtilityReadingDueRecord):PublicUtilityReadingDue=>({...r,periodStart:r.periodStart.toISOString(),periodEnd:r.periodEnd.toISOString(),dueAt:r.dueAt.toISOString(),completedAt:r.completedAt?.toISOString()??null,cancelledAt:r.cancelledAt?.toISOString()??null,createdAt:r.createdAt.toISOString(),updatedAt:r.updatedAt.toISOString()});
function duplicate(e:unknown){const x=e as{code?:string;constraint?:string};return x?.code==='23505'&&['utility_reading_due_meter_period_unique','utility_reading_due_task_unique'].includes(x.constraint??'')}
async function validateSchedule(input:CreateUtilityReadingDueInput,clientId:string,buildingId:string){if(input.scheduleDefinitionId){const s=(await getPool().query<any>('SELECT * FROM schedule_definitions WHERE id=$1',[input.scheduleDefinitionId])).rows[0];if(!s||s.target_type!=='UTILITY_METER'||s.target_id!==input.meterId||s.client_id!==clientId||s.building_id!==buildingId)throw utilityReadingDueInvalidScheduleError()}if(input.generatedTaskId){const t=(await getPool().query<any>('SELECT * FROM generated_tasks WHERE id=$1',[input.generatedTaskId])).rows[0];if(!t||t.target_type!=='UTILITY_METER'||t.target_id!==input.meterId||t.client_id!==clientId||t.building_id!==buildingId||(input.scheduleDefinitionId&&t.schedule_definition_id!==input.scheduleDefinitionId))throw utilityReadingDueInvalidScheduleError()}}
export async function createUtilityReadingDue(input:CreateUtilityReadingDueInput,userId:string){const meter=await utilityMeterRepository.findById(input.meterId);if(!meter)throw utilityMeterNotFoundError();await contextAccessService.assertBuildingAccess(userId,meter.buildingId);if(meter.status!=='ACTIVE')throw utilityMeterInactiveError('Inactive meters cannot receive Reading Due expectations.');await validateSchedule(input,meter.clientId,meter.buildingId);try{const r=await repo.create({...input,clientId:meter.clientId,buildingId:meter.buildingId,utilityType:meter.utilityType,createdByUserId:userId});await recordOperationalEvent({clientId:r.clientId,buildingId:r.buildingId,eventType:'UTILITY_READING_DUE_CREATED',entityType:'UTILITY_READING_DUE',entityId:r.id,actorUserId:userId,summary:'Utility meter reading expected',metadata:{meterId:r.meterId,periodStart:r.periodStart.toISOString(),periodEnd:r.periodEnd.toISOString(),dueAt:r.dueAt.toISOString(),scheduleDefinitionId:r.scheduleDefinitionId,generatedTaskId:r.generatedTaskId}});return out(r)}catch(e){if(duplicate(e))throw utilityReadingDueDuplicateError();throw e}}
async function accessible(id:string,userId:string,executor?:UtilityReadingDueExecutor){const r=await(executor?repo.findById(id,executor):repo.findById(id));if(!r)throw utilityReadingDueNotFoundError();await contextAccessService.assertBuildingAccess(userId,r.buildingId);return r}
export async function getUtilityReadingDue(id:string,userId:string){return out(await accessible(id,userId))}
export async function listMeterUtilityReadingDues(meterId:string,filters:UtilityReadingDueFilters,userId:string){const m=await utilityMeterRepository.findById(meterId);if(!m)throw utilityMeterNotFoundError();await contextAccessService.assertBuildingAccess(userId,m.buildingId);return(await repo.list({column:'meter_id',value:meterId},filters)).map(out)}
export async function listBuildingUtilityReadingDues(buildingId:string,filters:UtilityReadingDueFilters,userId:string){await contextAccessService.assertBuildingAccess(userId,buildingId);return(await repo.list({column:'building_id',value:buildingId},filters)).map(out)}
export async function listClientUtilityReadingDues(clientId:string,filters:UtilityReadingDueFilters,userId:string){if(!(await contextAccessService.canAccessClient(userId,clientId)))throw buildingAccessDeniedError();const ids=await contextAccessService.getAccessibleBuildingIds(userId);return(await repo.list({column:'client_id',value:clientId},filters,ids)).map(out)}
/**
 * Links an authoritative Meter Reading to a Reading Due and completes it.
 *
 * CR-BE-RN12-METER-FIELD-01 PART 01 — optional `executor`
 * -------------------------------------------------------
 * When supplied, the due lookup, the reading lookup, the completion UPDATE and
 * the `UTILITY_READING_DUE_COMPLETED` event all run on that connection, so a
 * caller inside `withTransaction` commits the linkage atomically with the
 * reading it just created.
 *
 * This is load-bearing, not cosmetic: the reading lookup MUST use the same
 * connection, because a field submission completes a due with a reading that
 * was inserted in the same still-open transaction and is therefore invisible
 * to any other connection. Omitting the argument preserves the existing
 * behaviour for every management and OCR caller.
 */
export async function completeUtilityReadingDue(id:string,meterReadingId:string,userId:string,executor?:UtilityReadingDueExecutor){const due=await accessible(id,userId,executor);if(!['DUE','OVERDUE'].includes(due.status))throw utilityReadingDueTransitionError();const reading=await(executor?utilityMeterReadingRepository.findById(meterReadingId,executor):utilityMeterReadingRepository.findById(meterReadingId));if(!reading)throw utilityMeterReadingNotFoundError();if(reading.clientId!==due.clientId||reading.buildingId!==due.buildingId||reading.meterId!==due.meterId||reading.readingAt<due.periodStart||reading.readingAt>due.periodEnd)throw utilityReadingDueReadingMismatchError();const r=await(executor?repo.complete(id,meterReadingId,userId,executor):repo.complete(id,meterReadingId,userId));if(!r)throw utilityReadingDueTransitionError();await recordOperationalEvent({clientId:r.clientId,buildingId:r.buildingId,eventType:'UTILITY_READING_DUE_COMPLETED',entityType:'UTILITY_READING_DUE',entityId:r.id,actorUserId:userId,summary:'Utility Reading Due linked to authoritative Meter Reading',metadata:{meterId:r.meterId,meterReadingId}},executor);return out(r)}
export async function cancelUtilityReadingDue(id:string,reason:string,userId:string){const due=await accessible(id,userId);if(!['DUE','OVERDUE'].includes(due.status))throw utilityReadingDueTransitionError();const r=await repo.cancel(id,reason,userId);if(!r)throw utilityReadingDueTransitionError();await recordOperationalEvent({clientId:r.clientId,buildingId:r.buildingId,eventType:'UTILITY_READING_DUE_CANCELLED',entityType:'UTILITY_READING_DUE',entityId:r.id,actorUserId:userId,summary:'Utility Reading Due cancelled',metadata:{meterId:r.meterId,reason}});return out(r)}
export const utilityReadingDueService={cancelUtilityReadingDue,completeUtilityReadingDue,createUtilityReadingDue,getUtilityReadingDue,listBuildingUtilityReadingDues,listClientUtilityReadingDues,listMeterUtilityReadingDues};
