import { AppError } from '../../shared/errors';
import { isValidUuid } from '../clients';
import { UTILITY_READING_DUE_STATUSES, type CreateUtilityReadingDueInput, type UtilityReadingDueFilters } from './utility-reading-due.types';
type D={field:string;message:string}; const fail=(d:D[]):never=>{throw AppError.validation('Request validation failed.',d)};
export function parseReadingDueId(raw:string,field='id'){const v=raw.trim().toLowerCase();if(!isValidUuid(v))fail([{field,message:`${field} must be a valid UUID.`}]);return v}
export function parseCreateReadingDue(meterId:string,body:unknown):CreateUtilityReadingDueInput{if(!body||typeof body!=='object'||Array.isArray(body))fail([{field:'body',message:'Request body must be a JSON object.'}]);const b=body as Record<string,unknown>,d:D[]=[];const periodStart=dt(b.periodStart,'periodStart',d),periodEnd=dt(b.periodEnd,'periodEnd',d),dueAt=dt(b.dueAt,'dueAt',d);if(periodStart&&periodEnd&&periodEnd<=periodStart)d.push({field:'periodEnd',message:'periodEnd must be later than periodStart.'});const scheduleDefinitionId=uuid(b.scheduleDefinitionId,'scheduleDefinitionId',d),generatedTaskId=uuid(b.generatedTaskId,'generatedTaskId',d);if(!periodStart||!periodEnd||!dueAt||d.length)fail(d);return{meterId,periodStart:periodStart!,periodEnd:periodEnd!,dueAt:dueAt!,...(scheduleDefinitionId?{scheduleDefinitionId}:{}),...(generatedTaskId?{generatedTaskId}:{})}}
export function parseCompleteReadingDue(body:unknown):{meterReadingId:string}{if(!body||typeof body!=='object'||Array.isArray(body))fail([{field:'body',message:'Request body must be a JSON object.'}]);const d:D[]=[],id=uuid((body as any).meterReadingId,'meterReadingId',d);if(!id||d.length)fail(d);return{meterReadingId:id!}}
export function parseCancelReadingDue(body:unknown):{reason:string}{if(!body||typeof body!=='object'||Array.isArray(body))fail([{field:'body',message:'Request body must be a JSON object.'}]);const v=(body as any).reason;if(typeof v!=='string'||!v.trim()||v.trim().length>1000)fail([{field:'reason',message:'reason is required and must be at most 1000 characters.'}]);return{reason:v.trim()}}
export function parseReadingDueFilters(query:unknown):UtilityReadingDueFilters{const v=query&&typeof query==='object'?(query as any).status:undefined;if(v===undefined)return{};if(typeof v!=='string'||!(UTILITY_READING_DUE_STATUSES as readonly string[]).includes(v))fail([{field:'status',message:`status must be one of: ${UTILITY_READING_DUE_STATUSES.join(', ')}.`}]);return{status:v as any}}
function dt(v:unknown,f:string,d:D[]){if(typeof v!=='string'||!v.trim()){d.push({field:f,message:`${f} must be a valid ISO-8601 timestamp.`});return}const x=new Date(v);if(Number.isNaN(+x)){d.push({field:f,message:`${f} must be a valid ISO-8601 timestamp.`});return}return x}
function uuid(v:unknown,f:string,d:D[]){if(v===undefined||v===null)return;if(typeof v!=='string'||!isValidUuid(v.trim())){d.push({field:f,message:`${f} must be a valid UUID.`});return}return v.trim().toLowerCase()}
