import { AppError } from '../../shared/errors';
import { isValidUuid } from '../clients';
import { isWorkOrderPriority, WORK_ORDER_PRIORITIES } from '../work-orders';
import { SLA_DEFINITION_STATUSES, SLA_OPERATIONAL_TYPES, type CreateSlaDefinitionInput, type SlaDefinitionFilters, type SlaDefinitionStatus, type SlaOperationalType, type UpdateSlaDefinitionInput } from './sla-definition.types';
type R=Record<string,unknown>; const obj=(v:unknown):v is R=>typeof v==='object'&&v!==null&&!Array.isArray(v);
const fail=(field:string,message:string):never=>{throw AppError.validation('Request validation failed.',[{field,message}])};
export function parseUuid(v:string,field:string){const n=v.trim().toLowerCase();if(!isValidUuid(n))fail(field,`${field} must be a valid UUID.`);return n}
const text=(v:unknown,f:string,max=200)=>{if(typeof v!=='string')fail(f,`${f} is required.`);const n=(v as string).trim();if(!n)fail(f,`${f} is required.`);if(n.length>max)fail(f,`${f} must be at most ${max} characters.`);return n};
const duration=(v:unknown,f:string)=>{if(v===undefined)return undefined;if(!Number.isInteger(v)||(v as number)<=0)fail(f,`${f} must be a positive integer.`);return v as number};
const date=(v:unknown,f:string,required=false)=>{if(v===undefined&&!required)return undefined;if(typeof v!=='string'||Number.isNaN(Date.parse(v)))fail(f,`${f} must be a valid ISO-8601 date-time.`);return new Date(v as string).toISOString()};
function common(b:R, update=false):any {const allowed=update?['name','workType','priority','responseTargetMinutes','resolutionTargetMinutes','status','effectiveFrom','effectiveTo']:['buildingId','code','name','operationalType','workType','priority','responseTargetMinutes','resolutionTargetMinutes','status','effectiveFrom','effectiveTo'];for(const k of Object.keys(b))if(!allowed.includes(k))fail(k,`${k} is not allowed.`);const out:any={};
if(!update||b.name!==undefined)out.name=text(b.name,'name');
if(!update){if(b.buildingId!==undefined)out.buildingId=parseUuid(String(b.buildingId),'buildingId');out.code=text(b.code,'code',100).toUpperCase();if(!/^[A-Z][A-Z0-9_.-]*$/.test(out.code))fail('code','code has an invalid format.');if(!SLA_OPERATIONAL_TYPES.includes(b.operationalType as SlaOperationalType))fail('operationalType',`operationalType must be one of: ${SLA_OPERATIONAL_TYPES.join(', ')}.`);out.operationalType=b.operationalType;}
if(b.workType!==undefined){out.workType=text(b.workType,'workType',100).toUpperCase();}
if(b.priority!==undefined){if(!isWorkOrderPriority(b.priority))fail('priority',`priority must be one of: ${WORK_ORDER_PRIORITIES.join(', ')}.`);out.priority=b.priority;}
for(const f of ['responseTargetMinutes','resolutionTargetMinutes'] as const){const v=duration(b[f],f);if(v!==undefined)out[f]=v;}
if(b.status!==undefined){if(!SLA_DEFINITION_STATUSES.includes(b.status as SlaDefinitionStatus))fail('status',`status must be one of: ${SLA_DEFINITION_STATUSES.join(', ')}.`);out.status=b.status;}
const from=date(b.effectiveFrom,'effectiveFrom',!update),to=date(b.effectiveTo,'effectiveTo');if(from)out.effectiveFrom=from;if(to)out.effectiveTo=to;
if(!update&&out.responseTargetMinutes===undefined&&out.resolutionTargetMinutes===undefined)fail('targets','At least one SLA target is required.');if(!update&&to&&new Date(to)<=new Date(from!))fail('effectiveTo','effectiveTo must be later than effectiveFrom.');if(update&&Object.keys(out).length===0)fail('body','At least one field is required.');return out;}
export function parseCreateBody(v:unknown):Omit<CreateSlaDefinitionInput,'clientId'>{if(!obj(v))fail('body','Request body must be a JSON object.');return common(v as R)}
export function parseUpdateBody(v:unknown):UpdateSlaDefinitionInput{if(!obj(v))fail('body','Request body must be a JSON object.');return common(v as R,true)}
export function parseFilters(q:R):SlaDefinitionFilters{const out:SlaDefinitionFilters={};if(q.buildingId!==undefined)out.buildingId=parseUuid(String(q.buildingId),'buildingId');if(q.status!==undefined){const s=String(q.status).toUpperCase();if(!SLA_DEFINITION_STATUSES.includes(s as SlaDefinitionStatus))fail('status','Invalid status.');out.status=s as SlaDefinitionStatus;}if(q.operationalType!==undefined){const x=String(q.operationalType).toUpperCase();if(!SLA_OPERATIONAL_TYPES.includes(x as SlaOperationalType))fail('operationalType','Invalid operationalType.');out.operationalType=x as SlaOperationalType;}if(q.priority!==undefined){const p=String(q.priority).toUpperCase();if(!isWorkOrderPriority(p))fail('priority','Invalid priority.');out.priority=p as import('../work-orders').WorkOrderPriority;}return out}
