import type {
  AssetFailureCategory,
  AssetFailureImpact,
  AssetFailureStatus,
} from '../asset-failures';
import type { IncidentStatus } from '../incidents';

/**
 * CR-BE-RN10-SAFE-EQUIPMENT-01 PART 01 — Mobile field-reported unsafe condition.
 *
 * An UNSAFE CONDITION has exactly ONE authoritative representation in the
 * backend: a BE-21C Asset Failure / Defect Incident whose
 * `operationalImpact` is `SAFETY_RISK`. This PART adds NO new entity, NO
 * `unsafe` boolean, NO unsafe Asset or Equipment status, and NO second
 * unsafe-condition table — the controlled BE-21C impact vocabulary already
 * carries the concept (`ASSET_FAILURE_IMPACTS`, mig 0216:
 * `NONE | DEGRADED | PARTIAL_OUTAGE | FULL_OUTAGE | SAFETY_RISK`).
 *
 * This module is a thin mobile FIELD COMMAND over the existing BE-21C
 * authority (`assetFailureService.createAssetFailure`). It composes; it does
 * not re-implement Asset Failure creation, and it duplicates no domain rule.
 *
 * WHAT THIS COMMAND DELIBERATELY DOES NOT DO
 * ------------------------------------------
 *   - it does not touch `assets.status` (BE-05E lifecycle) — recording an
 *     unsafe condition is an operational record, never a lifecycle move;
 *   - it does not touch `equipment_profiles.status` (BE-05D technical sheet);
 *   - it creates no OUT_OF_SERVICE / ISOLATED / SHUT_DOWN state and no
 *     RETURN_TO_SERVICE command — those are later RN-10 PARTs and are ABSENT
 *     from the backend entirely today;
 *   - it does not transition a Work Order or a Finding, and it never derives
 *     a Work Order CRITICAL priority.
 *
 * AUTHORITY SURFACE
 * -----------------
 * The field reporter describes WHAT THEY SAW. Every authoritative field is
 * server-derived, and every management/triage field is rejected rather than
 * ignored — silently dropping a caller's `failureStatus` would hide that
 * their intent was not honoured (the same posture BE-21C's own
 * `parseCreateAssetFailureBody` takes for `incidentType`).
 *
 * Server-derived, never accepted from the body:
 *   assetId, clientId, buildingId, incidentNumber, incidentType,
 *   operationalImpact, failureStatus, incidentStatus, reportedByUserId,
 *   createdByUserId, severity, priority, location*.
 */

/** The BE-21C impact that IS the authoritative unsafe-condition marker. */
export const UNSAFE_CONDITION_OPERATIONAL_IMPACT = 'SAFETY_RISK' as const;

/** The BE-21C failure-handling status every new report starts in. */
export const UNSAFE_CONDITION_INITIAL_FAILURE_STATUS = 'OPEN' as const;

/**
 * The ONLY body keys this command accepts.
 *
 * These are the smallest existing BE-21C human-entered narrative fields, named
 * exactly as BE-21C names them — no aliases are invented:
 *   `title`           the required human narrative / reason (≤200),
 *   `description`     optional elaboration (≤4000),
 *   `failureCategory` optional controlled observation code (defaults to the
 *                     existing `OTHER` escape hatch when the reporter does not
 *                     classify),
 *   `occurredAt`      optional observation instant; defaults to the server
 *                     report time. Never post-dated (BE-21C `assertOccurrence`).
 *
 * `failureCategory` is an OBSERVATION the technician is best placed to make
 * ("leakage", "overheating"); it is not triage authority. `severity` and
 * `priority` are deliberately NOT accepted: triage stays management authority
 * on the existing BE-21C update path, so RN-10 cannot drift into inferring
 * CRITICAL from a field report.
 */
export const MOBILE_UNSAFE_CONDITION_BODY_FIELDS = [
  'title',
  'description',
  'failureCategory',
  'occurredAt',
] as const;

export type MobileUnsafeConditionBodyField =
  (typeof MOBILE_UNSAFE_CONDITION_BODY_FIELDS)[number];

/**
 * Body keys that are REFUSED with a specific explanation (rather than the
 * generic unknown-field error) because they name real authority that this
 * command derives server-side. Kept explicit so the rejection stays
 * diagnosable and cannot be quietly relaxed.
 */
export const MOBILE_UNSAFE_CONDITION_DERIVED_FIELDS: Readonly<
  Record<string, string>
> = {
  assetId: 'assetId is taken from the request path.',
  clientId: 'clientId is derived from the Asset by the backend.',
  buildingId: 'buildingId is derived from the Asset by the backend.',
  incidentNumber: 'incidentNumber is generated by the backend.',
  incidentType: 'incidentType is fixed to ASSET_FAILURE by this endpoint.',
  operationalImpact:
    'operationalImpact is fixed to SAFETY_RISK by this endpoint.',
  failureStatus: 'failureStatus is derived by the backend (OPEN on report).',
  status: 'This Incident field is derived by the backend.',
  incidentStatus: 'This Incident field is derived by the backend.',
  reportedByUserId: 'The reporting actor is derived from the session.',
  createdByUserId: 'The reporting actor is derived from the session.',
  severity: 'severity is triage authority and is not part of field reporting.',
  priority: 'priority is triage authority and is not part of field reporting.',
  locationType: 'Location is derived from the authoritative Asset context.',
  locationId: 'Location is derived from the authoritative Asset context.',
  createdAt: 'This field is derived by the backend.',
  updatedAt: 'This field is derived by the backend.',
  cancelledAt: 'This field is derived by the backend.',
  cancelledByUserId: 'This field is derived by the backend.',
};

/** The accepted request body after validation. Timestamps are already parsed. */
export type MobileUnsafeConditionInput = {
  title: string;
  description?: string | null;
  failureCategory?: AssetFailureCategory;
  occurredAt?: Date;
};

/**
 * The reporting acknowledgement.
 *
 * Deliberately NOT the full `PublicAssetFailure` projection: that view carries
 * backend-authoritative `availableActions` resolved from `asset_failure.manage`,
 * which a field reporter does not hold and which would therefore always be
 * empty — an empty action list on a write response is a contract lie waiting to
 * be read as "nothing is possible". The canonical post-mutation read stays
 * `GET /asset-failures/{incidentId}` (the `incidentId` returned here is the
 * shared BE-21A identity that route addresses).
 */
export type MobileUnsafeConditionReported = {
  /** Shared BE-21A Incident id — the canonical read/address id. */
  incidentId: string;
  incidentNumber: string;
  assetId: string;
  clientId: string;
  buildingId: string;
  /**
   * Pinned to the literal `SAFETY_RISK`. Typed as the literal rather than as
   * the wide `AssetFailureImpact` union because this command SETS it — it is
   * not read back from the record, so the narrower type is the truthful one.
   */
  operationalImpact: typeof UNSAFE_CONDITION_OPERATIONAL_IMPACT;
  failureCategory: AssetFailureCategory;
  /**
   * Read back from the record. BE-21C starts every new failure at `OPEN`; the
   * value is NOT asserted here, and the contract test pins it to `OPEN` at
   * runtime so a change in the domain default cannot pass silently.
   */
  failureStatus: AssetFailureStatus;
  /** Read back from the record. BE-21A starts every new Incident at `REPORTED`. */
  incidentStatus: IncidentStatus;
  occurredAt: string;
  /** The authenticated caller — never a body field. */
  reportedByUserId: string;
  reportedAt: string;
  createdAt: string;
  /** The read to re-fetch the canonical record after this mutation. */
  canonicalRead: {
    operationId: 'getAssetFailure';
    path: string;
  };
};
