import type{NextFunction,Request,Response}from'express';import{sendSuccess}from'../../shared/api-response';import{authenticationRequiredError}from'../auth';import{slaEscalationPolicyService}from'./sla-escalation-policy.service';import{parseCreateLevelBody,parseCreatePolicyBody,parsePolicyFilters,parseUpdateLevelBody,parseUpdatePolicyBody,parseUuid}from'./sla-escalation-policy.validation';const p=(v:string|string[]|undefined)=>Array.isArray(v)?v[0]??'':v??'';const u=(q:Request)=>{if(!q.auth)throw authenticationRequiredError();return q.auth.userId};
export async function create(q:Request,r:Response,n:NextFunction){try{sendSuccess(r,await slaEscalationPolicyService.create({...parseCreatePolicyBody(q.body),clientId:parseUuid(p(q.params.clientId),'clientId')},u(q)),201)}catch(e){n(e)}}
export async function list(q:Request,r:Response,n:NextFunction){try{sendSuccess(r,await slaEscalationPolicyService.list(parseUuid(p(q.params.clientId),'clientId'),parsePolicyFilters(q.query as Record<string,unknown>),u(q)))}catch(e){n(e)}}
export async function get(q:Request,r:Response,n:NextFunction){try{sendSuccess(r,await slaEscalationPolicyService.get(parseUuid(p(q.params.id),'slaEscalationPolicyId'),u(q)))}catch(e){n(e)}}
export async function update(q:Request,r:Response,n:NextFunction){try{sendSuccess(r,await slaEscalationPolicyService.update(parseUuid(p(q.params.id),'slaEscalationPolicyId'),parseUpdatePolicyBody(q.body),u(q)))}catch(e){n(e)}}
export async function createLevel(q:Request,r:Response,n:NextFunction){try{sendSuccess(r,await slaEscalationPolicyService.createLevel({...parseCreateLevelBody(q.body),policyId:parseUuid(p(q.params.id),'slaEscalationPolicyId')},u(q)),201)}catch(e){n(e)}}
export async function listLevels(q:Request,r:Response,n:NextFunction){try{sendSuccess(r,await slaEscalationPolicyService.listLevels(parseUuid(p(q.params.id),'slaEscalationPolicyId'),u(q)))}catch(e){n(e)}}
export async function getLevel(q:Request,r:Response,n:NextFunction){try{sendSuccess(r,await slaEscalationPolicyService.getLevel(parseUuid(p(q.params.id),'slaEscalationLevelId'),u(q)))}catch(e){n(e)}}
export async function updateLevel(q:Request,r:Response,n:NextFunction){try{sendSuccess(r,await slaEscalationPolicyService.updateLevel(parseUuid(p(q.params.id),'slaEscalationLevelId'),parseUpdateLevelBody(q.body),u(q)))}catch(e){n(e)}}
