import { randomUUID } from 'node:crypto';import { getPool } from '../../database';import type {CreateSlaEscalationLevelInput,CreateSlaEscalationPolicyInput,SlaEscalationLevelRecord,SlaEscalationPolicyFilters,SlaEscalationPolicyRecord,UpdateSlaEscalationLevelInput,UpdateSlaEscalationPolicyInput} from './sla-escalation-policy.types';
const P=`id,client_id AS "clientId",building_id AS "buildingId",code,name,description,operational_type AS "operationalType",clock_type AS "clockType",work_type AS "workType",priority,status,effective_from AS "effectiveFrom",effective_to AS "effectiveTo",created_at AS "createdAt",updated_at AS "updatedAt"`;
const L=`id,policy_id AS "policyId",level,offset_minutes AS "offsetMinutes",template_key AS "templateKey",recipient_rule AS "recipientRule",status,created_at AS "createdAt",updated_at AS "updatedAt"`;
function sets(i:Record<string,unknown>,map:Record<string,string>){const v:unknown[]=[],s:string[]=[];for(const [k,col] of Object.entries(map))if(Object.prototype.hasOwnProperty.call(i,k)){v.push((i as any)[k]??null);s.push(`${col}=$${v.length}`)}return{v,s}}
async function createPolicy(i:CreateSlaEscalationPolicyInput){return (await getPool().query<SlaEscalationPolicyRecord>(`INSERT INTO sla_escalation_policies(id,client_id,building_id,code,name,description,operational_type,clock_type,work_type,priority,status,effective_from,effective_to) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) RETURNING ${P}`,[randomUUID(),i.clientId,i.buildingId??null,i.code,i.name,i.description??null,i.operationalType,i.clockType,i.workType??null,i.priority??null,i.status??'ACTIVE',i.effectiveFrom,i.effectiveTo??null])).rows[0]}
async function findPolicyById(id:string){return (await getPool().query<SlaEscalationPolicyRecord>(`SELECT ${P} FROM sla_escalation_policies WHERE id=$1`,[id])).rows[0]??null}
async function listPolicies(clientId:string,f:SlaEscalationPolicyFilters){const v:unknown[]=[clientId],w=['client_id=$1'];for(const [k,col] of [['buildingId','building_id'],['status','status'],['clockType','clock_type'],['priority','priority']] as const){if(f[k]!==undefined){v.push(f[k]);w.push(`${col}=$${v.length}`)}}return (await getPool().query<SlaEscalationPolicyRecord>(`SELECT ${P} FROM sla_escalation_policies WHERE ${w.join(' AND ')} ORDER BY code,effective_from`,v)).rows}
async function updatePolicy(id:string,i:UpdateSlaEscalationPolicyInput){const {v,s}=sets(i,{name:'name',description:'description',clockType:'clock_type',workType:'work_type',priority:'priority',status:'status',effectiveFrom:'effective_from',effectiveTo:'effective_to'});v.push(id);return (await getPool().query<SlaEscalationPolicyRecord>(`UPDATE sla_escalation_policies SET ${s.join(',')},updated_at=NOW() WHERE id=$${v.length} RETURNING ${P}`,v)).rows[0]??null}
async function createLevel(i:CreateSlaEscalationLevelInput){return (await getPool().query<SlaEscalationLevelRecord>(`INSERT INTO sla_escalation_levels(id,policy_id,level,offset_minutes,template_key,recipient_rule,status) VALUES($1,$2,$3,$4,$5,$6::jsonb,$7) RETURNING ${L}`,[randomUUID(),i.policyId,i.level,i.offsetMinutes??0,i.templateKey,JSON.stringify(i.recipientRule),i.status??'ACTIVE'])).rows[0]}
async function findLevelById(id:string){return (await getPool().query<SlaEscalationLevelRecord>(`SELECT ${L} FROM sla_escalation_levels WHERE id=$1`,[id])).rows[0]??null}
async function listLevels(policyId:string){return (await getPool().query<SlaEscalationLevelRecord>(`SELECT ${L} FROM sla_escalation_levels WHERE policy_id=$1 ORDER BY level`,[policyId])).rows}
async function findLevelByOffset(policyId:string,offsetMinutes:number,excludeId?:string){return (await getPool().query<SlaEscalationLevelRecord>(`SELECT ${L} FROM sla_escalation_levels WHERE policy_id=$1 AND offset_minutes=$2 AND ($3::uuid IS NULL OR id<>$3)`,[policyId,offsetMinutes,excludeId??null])).rows[0]??null}
async function updateLevel(id:string,i:UpdateSlaEscalationLevelInput){const v:unknown[]=[],s:string[]=[];for(const [k,col,cast] of [['level','level',''],['offsetMinutes','offset_minutes',''],['templateKey','template_key',''],['recipientRule','recipient_rule','::jsonb'],['status','status','']] as const)if(Object.prototype.hasOwnProperty.call(i,k)){v.push(k==='recipientRule'?JSON.stringify((i as any)[k]):(i as any)[k]??null);s.push(`${col}=$${v.length}${cast}`)}v.push(id);return (await getPool().query<SlaEscalationLevelRecord>(`UPDATE sla_escalation_levels SET ${s.join(',')},updated_at=NOW() WHERE id=$${v.length} RETURNING ${L}`,v)).rows[0]??null}
export const slaEscalationPolicyRepository={createPolicy,findPolicyById,listPolicies,updatePolicy,createLevel,findLevelById,listLevels,findLevelByOffset,updateLevel};
