import { AppError } from '../../shared/errors';import { clientInactiveError,clientNotFoundError,clientRepository } from '../clients';import { buildingAccessDeniedError,contextAccessService } from '../context-access';import { resolveBuildingConfigurationContext } from '../building-configurations/building-configuration.service';import { notificationTemplateRepository } from '../notification-templates';import { slaEscalationPolicyRepository } from './sla-escalation-policy.repository';import type {CreateSlaEscalationLevelInput,CreateSlaEscalationPolicyInput,PublicSlaEscalationLevel,PublicSlaEscalationPolicy,SlaEscalationLevelRecord,SlaEscalationPolicyFilters,SlaEscalationPolicyRecord,UpdateSlaEscalationLevelInput,UpdateSlaEscalationPolicyInput} from './sla-escalation-policy.types';
const pub=(r:SlaEscalationPolicyRecord):PublicSlaEscalationPolicy=>({...r,effectiveFrom:r.effectiveFrom.toISOString(),effectiveTo:r.effectiveTo?.toISOString()??null,createdAt:r.createdAt.toISOString(),updatedAt:r.updatedAt.toISOString()});
const pubLevel=(r:SlaEscalationLevelRecord):PublicSlaEscalationLevel=>({...r,createdAt:r.createdAt.toISOString(),updatedAt:r.updatedAt.toISOString()});
const conflict=(m:string)=>new AppError({code:'BAD_REQUEST',message:m,statusCode:409});
async function assertClient(userId:string,clientId:string){const c=await clientRepository.findById(clientId);if(!c)throw clientNotFoundError();if(!(await contextAccessService.canAccessClient(userId,clientId)))throw buildingAccessDeniedError();return c}
/** Same isolation rule as SLA-01: a Building-scoped row is gated by Building access, a Client-scoped row by Client access. */
async function assertPolicyAccess(r:SlaEscalationPolicyRecord,userId:string){if(r.buildingId)await contextAccessService.assertBuildingAccess(userId,r.buildingId);else await assertClient(userId,r.clientId)}
async function requirePolicy(id:string,userId:string){const r=await slaEscalationPolicyRepository.findPolicyById(id);if(!r)throw AppError.notFound('SLA escalation policy not found.');await assertPolicyAccess(r,userId);return r}
/** PART 01 stores the template KEY only; it never renders or sends. The key must exist in the BE-26B catalogue. */
async function assertTemplate(key:string){const t=await notificationTemplateRepository.findByKey(key);if(!t)throw AppError.validation('Request validation failed.',[{field:'templateKey',message:'templateKey must reference an existing notification template.'}])}
async function create(i:CreateSlaEscalationPolicyInput,userId:string){const c=await assertClient(userId,i.clientId);if(c.status!=='ACTIVE')throw clientInactiveError();if(i.buildingId){const x=await resolveBuildingConfigurationContext(i.buildingId,userId);if(x.clientId!==i.clientId)throw buildingAccessDeniedError()}try{return pub(await slaEscalationPolicyRepository.createPolicy(i))}catch(e){if((e as any)?.code==='23505')throw conflict('An SLA escalation policy with this code already exists for the client.');throw e}}
async function list(clientId:string,f:SlaEscalationPolicyFilters,userId:string){await assertClient(userId,clientId);if(f.buildingId){const x=await resolveBuildingConfigurationContext(f.buildingId,userId);if(x.clientId!==clientId)throw buildingAccessDeniedError()}return (await slaEscalationPolicyRepository.listPolicies(clientId,f)).map(pub)}
async function get(id:string,userId:string){return pub(await requirePolicy(id,userId))}
async function update(id:string,i:UpdateSlaEscalationPolicyInput,userId:string){const r=await requirePolicy(id,userId);const from=new Date(i.effectiveFrom??r.effectiveFrom),to=Object.prototype.hasOwnProperty.call(i,'effectiveTo')?(i.effectiveTo?new Date(i.effectiveTo):null):r.effectiveTo;if(to&&to<=from)throw AppError.validation('Request validation failed.',[{field:'effectiveTo',message:'effectiveTo must be later than effectiveFrom.'}]);return pub((await slaEscalationPolicyRepository.updatePolicy(id,i))!)}
async function createLevel(i:CreateSlaEscalationLevelInput,userId:string){await requirePolicy(i.policyId,userId);await assertTemplate(i.templateKey);const offset=i.offsetMinutes??0;if(await slaEscalationPolicyRepository.findLevelByOffset(i.policyId,offset))throw conflict('Another escalation level of this policy already uses this offsetMinutes.');try{return pubLevel(await slaEscalationPolicyRepository.createLevel(i))}catch(e){if((e as any)?.code==='23505')throw conflict('This escalation level already exists for the policy.');throw e}}
async function listLevels(policyId:string,userId:string){await requirePolicy(policyId,userId);return (await slaEscalationPolicyRepository.listLevels(policyId)).map(pubLevel)}
async function getLevel(id:string,userId:string){const r=await slaEscalationPolicyRepository.findLevelById(id);if(!r)throw AppError.notFound('SLA escalation level not found.');await requirePolicy(r.policyId,userId);return pubLevel(r)}
async function updateLevel(id:string,i:UpdateSlaEscalationLevelInput,userId:string){const r=await slaEscalationPolicyRepository.findLevelById(id);if(!r)throw AppError.notFound('SLA escalation level not found.');await requirePolicy(r.policyId,userId);if(i.templateKey!==undefined)await assertTemplate(i.templateKey);if(i.offsetMinutes!==undefined&&await slaEscalationPolicyRepository.findLevelByOffset(r.policyId,i.offsetMinutes,id))throw conflict('Another escalation level of this policy already uses this offsetMinutes.');try{return pubLevel((await slaEscalationPolicyRepository.updateLevel(id,i))!)}catch(e){if((e as any)?.code==='23505')throw conflict('This escalation level already exists for the policy.');throw e}}
export const slaEscalationPolicyService={create,list,get,update,createLevel,listLevels,getLevel,updateLevel};
