import { randomUUID } from 'node:crypto';
import type { PoolClient } from 'pg';
import { getPool } from '../../database';
import type {
  HandymanMaterialActualUsageRecord,
  HandymanMaterialControlledIssueRecord,
  HandymanMaterialReturnRecord,
  HandymanMaterialUsageKind,
} from './handyman-material-inventory.types';

type Executor = Pick<PoolClient, 'query'>;

type ControlledIssueRow = Omit<
  HandymanMaterialControlledIssueRecord,
  'quantity' | 'issuedAt' | 'createdAt'
> & {
  quantity: string | number;
  issuedAt: Date;
  createdAt: Date;
};

type ActualUsageRow = Omit<
  HandymanMaterialActualUsageRecord,
  'quantity' | 'usedAt' | 'createdAt'
> & {
  quantity: string | number;
  usedAt: Date;
  createdAt: Date;
};

type ReturnRow = Omit<
  HandymanMaterialReturnRecord,
  'quantity' | 'returnedAt' | 'createdAt'
> & {
  quantity: string | number;
  returnedAt: Date;
  createdAt: Date;
};

const CONTROLLED_ISSUE_SELECT = `
  id,
  client_id AS "clientId",
  building_id AS "buildingId",
  handyman_material_demand_id AS "handymanMaterialDemandId",
  handyman_job_id AS "handymanJobId",
  work_order_id AS "workOrderId",
  inventory_material_reservation_id AS "inventoryMaterialReservationId",
  warehouse_id AS "warehouseId",
  item_id AS "itemId",
  uom_id AS "uomId",
  handyman_service_visit_id AS "handymanServiceVisitId",
  handyman_work_session_id AS "handymanWorkSessionId",
  inventory_stock_movement_id AS "inventoryStockMovementId",
  quantity,
  issued_by_user_id AS "issuedByUserId",
  issued_at AS "issuedAt",
  reference,
  notes,
  idempotency_key AS "idempotencyKey",
  idempotency_fingerprint AS "idempotencyFingerprint",
  created_at AS "createdAt"
`;

const ACTUAL_USAGE_SELECT = `
  id,
  client_id AS "clientId",
  building_id AS "buildingId",
  handyman_material_demand_id AS "handymanMaterialDemandId",
  handyman_job_id AS "handymanJobId",
  work_order_id AS "workOrderId",
  handyman_material_controlled_issue_id AS "handymanMaterialControlledIssueId",
  inventory_item_id AS "inventoryItemId",
  uom_id AS "uomId",
  handyman_service_visit_id AS "handymanServiceVisitId",
  handyman_work_session_id AS "handymanWorkSessionId",
  usage_kind AS "usageKind",
  quantity,
  used_by_user_id AS "usedByUserId",
  used_at AS "usedAt",
  notes,
  idempotency_key AS "idempotencyKey",
  idempotency_fingerprint AS "idempotencyFingerprint",
  created_at AS "createdAt"
`;

const RETURN_SELECT = `
  id,
  client_id AS "clientId",
  building_id AS "buildingId",
  handyman_material_controlled_issue_id AS "handymanMaterialControlledIssueId",
  handyman_material_demand_id AS "handymanMaterialDemandId",
  handyman_job_id AS "handymanJobId",
  work_order_id AS "workOrderId",
  warehouse_id AS "warehouseId",
  item_id AS "itemId",
  uom_id AS "uomId",
  inventory_stock_movement_id AS "inventoryStockMovementId",
  quantity,
  returned_by_user_id AS "returnedByUserId",
  returned_at AS "returnedAt",
  reference,
  notes,
  idempotency_key AS "idempotencyKey",
  idempotency_fingerprint AS "idempotencyFingerprint",
  created_at AS "createdAt"
`;

function numberValue(value: string | number): number {
  return typeof value === 'number' ? value : Number(value);
}

function mapControlledIssue(
  row: ControlledIssueRow,
): HandymanMaterialControlledIssueRecord {
  return {
    ...row,
    quantity: numberValue(row.quantity),
    inventoryMaterialReservationId: row.inventoryMaterialReservationId ?? null,
    handymanServiceVisitId: row.handymanServiceVisitId ?? null,
    handymanWorkSessionId: row.handymanWorkSessionId ?? null,
    reference: row.reference ?? null,
    notes: row.notes ?? null,
  };
}

function mapActualUsage(row: ActualUsageRow): HandymanMaterialActualUsageRecord {
  return {
    ...row,
    quantity: numberValue(row.quantity),
    handymanMaterialControlledIssueId:
      row.handymanMaterialControlledIssueId ?? null,
    inventoryItemId: row.inventoryItemId ?? null,
    handymanServiceVisitId: row.handymanServiceVisitId ?? null,
    handymanWorkSessionId: row.handymanWorkSessionId ?? null,
    notes: row.notes ?? null,
  };
}

function mapReturn(row: ReturnRow): HandymanMaterialReturnRecord {
  return {
    ...row,
    quantity: numberValue(row.quantity),
    reference: row.reference ?? null,
    notes: row.notes ?? null,
  };
}

export type NewHandymanMaterialControlledIssue = {
  /** Generated by the service before the STOCK_OUT source is written. */
  id: string;
  clientId: string;
  buildingId: string;
  handymanMaterialDemandId: string;
  handymanJobId: string;
  workOrderId: string;
  inventoryMaterialReservationId: string | null;
  warehouseId: string;
  itemId: string;
  uomId: string;
  handymanServiceVisitId: string | null;
  handymanWorkSessionId: string | null;
  inventoryStockMovementId: string;
  quantity: number;
  issuedByUserId: string;
  issuedAt: Date;
  reference: string | null;
  notes: string | null;
  idempotencyKey: string;
  idempotencyFingerprint: string;
};

export type NewHandymanMaterialActualUsage = {
  clientId: string;
  buildingId: string;
  handymanMaterialDemandId: string;
  handymanJobId: string;
  workOrderId: string;
  handymanMaterialControlledIssueId: string | null;
  inventoryItemId: string | null;
  uomId: string;
  handymanServiceVisitId: string | null;
  handymanWorkSessionId: string | null;
  usageKind: HandymanMaterialUsageKind;
  quantity: number;
  usedByUserId: string;
  usedAt: Date;
  notes: string | null;
  idempotencyKey: string;
  idempotencyFingerprint: string;
};

export type NewHandymanMaterialReturn = {
  /** Generated by the service before the STOCK_IN source is written. */
  id: string;
  clientId: string;
  buildingId: string;
  handymanMaterialControlledIssueId: string;
  handymanMaterialDemandId: string;
  handymanJobId: string;
  workOrderId: string;
  warehouseId: string;
  itemId: string;
  uomId: string;
  inventoryStockMovementId: string;
  quantity: number;
  returnedByUserId: string;
  returnedAt: Date;
  reference: string | null;
  notes: string | null;
  idempotencyKey: string;
  idempotencyFingerprint: string;
};

async function createControlledIssue(
  input: NewHandymanMaterialControlledIssue,
  executor: Executor,
): Promise<HandymanMaterialControlledIssueRecord> {
  const result = await executor.query<ControlledIssueRow>(
    `INSERT INTO handyman_material_controlled_issues
       (id, client_id, building_id, handyman_material_demand_id,
        handyman_job_id, work_order_id, inventory_material_reservation_id,
        warehouse_id, item_id, uom_id, handyman_service_visit_id,
        handyman_work_session_id, inventory_stock_movement_id, quantity,
        issued_by_user_id, issued_at, reference, notes, idempotency_key,
        idempotency_fingerprint)
     VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14,
             $15, $16, $17, $18, $19, $20)
     RETURNING ${CONTROLLED_ISSUE_SELECT}`,
    [
      input.id,
      input.clientId,
      input.buildingId,
      input.handymanMaterialDemandId,
      input.handymanJobId,
      input.workOrderId,
      input.inventoryMaterialReservationId,
      input.warehouseId,
      input.itemId,
      input.uomId,
      input.handymanServiceVisitId,
      input.handymanWorkSessionId,
      input.inventoryStockMovementId,
      input.quantity,
      input.issuedByUserId,
      input.issuedAt,
      input.reference,
      input.notes,
      input.idempotencyKey,
      input.idempotencyFingerprint,
    ],
  );
  return mapControlledIssue(result.rows[0]);
}

async function findControlledIssueById(
  id: string,
  executor: Executor = getPool(),
): Promise<HandymanMaterialControlledIssueRecord | null> {
  const result = await executor.query<ControlledIssueRow>(
    `SELECT ${CONTROLLED_ISSUE_SELECT}
     FROM handyman_material_controlled_issues
     WHERE id = $1`,
    [id],
  );
  return result.rows[0] ? mapControlledIssue(result.rows[0]) : null;
}

/** Original issue lock: shared serialization point for provider usage/return. */
async function lockControlledIssueById(
  id: string,
  executor: Executor,
): Promise<HandymanMaterialControlledIssueRecord | null> {
  const result = await executor.query<ControlledIssueRow>(
    `SELECT ${CONTROLLED_ISSUE_SELECT}
     FROM handyman_material_controlled_issues
     WHERE id = $1
     FOR UPDATE`,
    [id],
  );
  return result.rows[0] ? mapControlledIssue(result.rows[0]) : null;
}

async function findControlledIssueByIdempotencyKey(
  clientId: string,
  idempotencyKey: string,
  executor: Executor = getPool(),
): Promise<HandymanMaterialControlledIssueRecord | null> {
  const result = await executor.query<ControlledIssueRow>(
    `SELECT ${CONTROLLED_ISSUE_SELECT}
     FROM handyman_material_controlled_issues
     WHERE client_id = $1 AND idempotency_key = $2`,
    [clientId, idempotencyKey],
  );
  return result.rows[0] ? mapControlledIssue(result.rows[0]) : null;
}

async function createActualUsage(
  input: NewHandymanMaterialActualUsage,
  executor: Executor,
): Promise<HandymanMaterialActualUsageRecord> {
  const result = await executor.query<ActualUsageRow>(
    `INSERT INTO handyman_material_actual_usages
       (id, client_id, building_id, handyman_material_demand_id,
        handyman_job_id, work_order_id, handyman_material_controlled_issue_id,
        inventory_item_id, uom_id, handyman_service_visit_id,
        handyman_work_session_id, usage_kind, quantity, used_by_user_id,
        used_at, notes, idempotency_key, idempotency_fingerprint)
     VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14,
             $15, $16, $17, $18)
     RETURNING ${ACTUAL_USAGE_SELECT}`,
    [
      randomUUID(),
      input.clientId,
      input.buildingId,
      input.handymanMaterialDemandId,
      input.handymanJobId,
      input.workOrderId,
      input.handymanMaterialControlledIssueId,
      input.inventoryItemId,
      input.uomId,
      input.handymanServiceVisitId,
      input.handymanWorkSessionId,
      input.usageKind,
      input.quantity,
      input.usedByUserId,
      input.usedAt,
      input.notes,
      input.idempotencyKey,
      input.idempotencyFingerprint,
    ],
  );
  return mapActualUsage(result.rows[0]);
}

async function findActualUsageByIdempotencyKey(
  clientId: string,
  idempotencyKey: string,
  executor: Executor = getPool(),
): Promise<HandymanMaterialActualUsageRecord | null> {
  const result = await executor.query<ActualUsageRow>(
    `SELECT ${ACTUAL_USAGE_SELECT}
     FROM handyman_material_actual_usages
     WHERE client_id = $1 AND idempotency_key = $2`,
    [clientId, idempotencyKey],
  );
  return result.rows[0] ? mapActualUsage(result.rows[0]) : null;
}

async function createReturn(
  input: NewHandymanMaterialReturn,
  executor: Executor,
): Promise<HandymanMaterialReturnRecord> {
  const result = await executor.query<ReturnRow>(
    `INSERT INTO handyman_material_returns
       (id, client_id, building_id, handyman_material_controlled_issue_id,
        handyman_material_demand_id, handyman_job_id, work_order_id,
        warehouse_id, item_id, uom_id, inventory_stock_movement_id, quantity,
        returned_by_user_id, returned_at, reference, notes, idempotency_key,
        idempotency_fingerprint)
     VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14,
             $15, $16, $17, $18)
     RETURNING ${RETURN_SELECT}`,
    [
      input.id,
      input.clientId,
      input.buildingId,
      input.handymanMaterialControlledIssueId,
      input.handymanMaterialDemandId,
      input.handymanJobId,
      input.workOrderId,
      input.warehouseId,
      input.itemId,
      input.uomId,
      input.inventoryStockMovementId,
      input.quantity,
      input.returnedByUserId,
      input.returnedAt,
      input.reference,
      input.notes,
      input.idempotencyKey,
      input.idempotencyFingerprint,
    ],
  );
  return mapReturn(result.rows[0]);
}

async function findReturnByIdempotencyKey(
  clientId: string,
  idempotencyKey: string,
  executor: Executor = getPool(),
): Promise<HandymanMaterialReturnRecord | null> {
  const result = await executor.query<ReturnRow>(
    `SELECT ${RETURN_SELECT}
     FROM handyman_material_returns
     WHERE client_id = $1 AND idempotency_key = $2`,
    [clientId, idempotencyKey],
  );
  return result.rows[0] ? mapReturn(result.rows[0]) : null;
}

/** Read only after `lockControlledIssueById`; the lock makes sums stable. */
async function getIssueUseReturnSnapshot(
  executor: Executor,
  handymanMaterialControlledIssueId: string,
): Promise<{ issuedQuantity: number; usedQuantity: number; returnedQuantity: number }> {
  const result = await executor.query<{
    issuedQuantity: string | number;
    usedQuantity: string | number;
    returnedQuantity: string | number;
  }>(
    `SELECT
       i.quantity AS "issuedQuantity",
       COALESCE((
         SELECT SUM(u.quantity)
         FROM handyman_material_actual_usages u
         WHERE u.handyman_material_controlled_issue_id = i.id
       ), 0)::numeric AS "usedQuantity",
       COALESCE((
         SELECT SUM(r.quantity)
         FROM handyman_material_returns r
         WHERE r.handyman_material_controlled_issue_id = i.id
       ), 0)::numeric AS "returnedQuantity"
     FROM handyman_material_controlled_issues i
     WHERE i.id = $1`,
    [handymanMaterialControlledIssueId],
  );
  const row = result.rows[0];
  if (!row) throw new Error('Controlled issue snapshot was not found.');
  return {
    issuedQuantity: numberValue(row.issuedQuantity),
    usedQuantity: numberValue(row.usedQuantity),
    returnedQuantity: numberValue(row.returnedQuantity),
  };
}

/** Read only after the customer-supplied demand lock. */
async function getCustomerActualUsageQuantity(
  executor: Executor,
  handymanMaterialDemandId: string,
): Promise<number> {
  const result = await executor.query<{ quantity: string | number }>(
    `SELECT COALESCE(SUM(quantity), 0)::numeric AS quantity
     FROM handyman_material_actual_usages
     WHERE handyman_material_demand_id = $1
       AND handyman_material_controlled_issue_id IS NULL`,
    [handymanMaterialDemandId],
  );
  return numberValue(result.rows[0]?.quantity ?? 0);
}

export const handymanMaterialInventoryRepository = {
  createActualUsage,
  createControlledIssue,
  createReturn,
  findActualUsageByIdempotencyKey,
  findControlledIssueById,
  findControlledIssueByIdempotencyKey,
  findReturnByIdempotencyKey,
  getCustomerActualUsageQuantity,
  getIssueUseReturnSnapshot,
  lockControlledIssueById,
};
