import type{PoolClient}from'pg';import{AppError}from'../../shared/errors';import{recordOperationalEvent}from'../operational-events';import{isHandymanSlaSubjectType}from'../sla-definitions/handyman-sla-subjects';import{materializeEscalationActions}from'../sla-escalation-actions';import type{WorkOrderRecord}from'../work-orders';import{appliedSlaRepository}from'./applied-sla.repository';import type{AppliedSlaRecord,PublicAppliedSla,SlaClockRecord,SlaSubjectBinding}from'./applied-sla.types';
async function clock(x:SlaClockRecord){const a=await appliedSlaRepository.pauseAccounting(x.id);return{...x,startedAt:x.startedAt.toISOString(),satisfiedAt:x.satisfiedAt?.toISOString()??null,terminatedAt:x.terminatedAt?.toISOString()??null,breachedAt:x.breachedAt?.toISOString()??null,createdAt:x.createdAt.toISOString(),updatedAt:x.updatedAt.toISOString(),isPaused:a.intervals.some(p=>p.resumedAt===null),totalPausedMilliseconds:a.totalPausedMilliseconds,effectiveElapsedMilliseconds:a.effectiveElapsedMilliseconds,pauseIntervals:a.intervals.map(p=>({...p,pausedAt:p.pausedAt.toISOString(),resumedAt:p.resumedAt?.toISOString()??null,createdAt:p.createdAt.toISOString(),updatedAt:p.updatedAt.toISOString()}))}}
async function publicRecord(a:AppliedSlaRecord):Promise<PublicAppliedSla>{const clocks=[];for(const c of await appliedSlaRepository.listClocks(a.id))clocks.push(await clock(c));return{...a,definitionEffectiveFrom:a.definitionEffectiveFrom.toISOString(),definitionEffectiveTo:a.definitionEffectiveTo?.toISOString()??null,appliedAt:a.appliedAt.toISOString(),createdAt:a.createdAt.toISOString(),clocks}}
export async function applyToNewWorkOrder(w:WorkOrderRecord,tx:PoolClient):Promise<AppliedSlaRecord|null>{const matches=await appliedSlaRepository.selectApplicable(w.clientId,w.buildingId,'WORK_ORDER',w.workType,w.priority,w.createdAt,tx);if(!matches.length)return null;const top=matches[0];if(matches[1]?.specificity===top.specificity)throw new AppError({code:'BAD_REQUEST',message:'Applicable SLA definitions are ambiguous.',statusCode:409});const applied=await appliedSlaRepository.createApplied(top,w,tx);const clocks:SlaClockRecord[]=[];if(top.responseTargetMinutes)clocks.push(await appliedSlaRepository.createClock(applied.id,'RESPONSE',top.responseTargetMinutes,w.createdAt,tx));if(top.resolutionTargetMinutes)clocks.push(await appliedSlaRepository.createClock(applied.id,'RESOLUTION',top.resolutionTargetMinutes,w.createdAt,tx));await recordOperationalEvent({clientId:w.clientId,buildingId:w.buildingId,entityType:'WORK_ORDER',entityId:w.id,eventType:'SLA_APPLIED',summary:`SLA ${top.code} applied to work order`,metadata:{appliedSlaId:applied.id,slaDefinitionId:top.id}},tx);for(const c of clocks)await recordOperationalEvent({clientId:w.clientId,buildingId:w.buildingId,entityType:'WORK_ORDER',entityId:w.id,eventType:'SLA_CLOCK_CREATED',summary:`${c.clockType} SLA clock created`,metadata:{appliedSlaId:applied.id,clockId:c.id,clockType:c.clockType}},tx);return applied}
/**
 * CR-HM-16 PART 01 — Handyman subject binding over the shared SLA engine
 * (governance `CR-HM-16_START_GOVERNANCE.md` §4/§9 PART 01). This is the SAME
 * snapshot + clock creation + SLA_APPLIED/SLA_CLOCK_CREATED event chain as the
 * Work Order path — one engine, one clock authority, one breach writer — bound
 * to a Handyman subject (`subjectType` must be from the closed Handyman
 * vocabulary; Work Orders keep using `applyToNewWorkOrder`). Clocks start at
 * the subject's authoritative creation instant, exactly like Work Orders.
 */
export async function applyToNewSubject(s:SlaSubjectBinding,tx:PoolClient):Promise<AppliedSlaRecord|null>{if(!isHandymanSlaSubjectType(s.subjectType))throw AppError.validation('Request validation failed.',[{field:'subjectType',message:'subjectType must be a Handyman SLA subject type.'}]);const matches=await appliedSlaRepository.selectApplicable(s.clientId,s.buildingId,s.subjectType,s.workType??null,s.priority??null,s.createdAt,tx);if(!matches.length)return null;const top=matches[0];if(matches[1]?.specificity===top.specificity)throw new AppError({code:'BAD_REQUEST',message:'Applicable SLA definitions are ambiguous.',statusCode:409});const applied=await appliedSlaRepository.createApplied(top,{id:s.subjectId,clientId:s.clientId,buildingId:s.buildingId,workType:s.workType??null,priority:s.priority??null,createdAt:s.createdAt},tx);const clocks:SlaClockRecord[]=[];if(top.responseTargetMinutes)clocks.push(await appliedSlaRepository.createClock(applied.id,'RESPONSE',top.responseTargetMinutes,s.createdAt,tx));if(top.resolutionTargetMinutes)clocks.push(await appliedSlaRepository.createClock(applied.id,'RESOLUTION',top.resolutionTargetMinutes,s.createdAt,tx));await recordOperationalEvent({clientId:s.clientId,buildingId:s.buildingId,entityType:s.subjectType,entityId:s.subjectId,eventType:'SLA_APPLIED',summary:`SLA ${top.code} applied to ${s.subjectType}`,metadata:{appliedSlaId:applied.id,slaDefinitionId:top.id}},tx);for(const c of clocks)await recordOperationalEvent({clientId:s.clientId,buildingId:s.buildingId,entityType:s.subjectType,entityId:s.subjectId,eventType:'SLA_CLOCK_CREATED',summary:`${c.clockType} SLA clock created`,metadata:{appliedSlaId:applied.id,clockId:c.id,clockType:c.clockType}},tx);return applied}
/**
 * CR-BE-SLA-01 PART 05 due breach path, made transaction-safe in CR-BE-SLA-02
 * PART 02. Each due clock is handled in its own `withTransaction`, so the
 * breach write, `SLA_CLOCK_BREACHED`, and the escalation ledger materialized
 * from it commit together — identical to the lifecycle path — while one clock's
 * failure cannot roll back the others.
 *
 * CR-HM-16 PART 02: the per-clock context resolves EITHER binding kind of
 * the shared engine — Work Order rows enrich live `work_type`/`priority` from
 * `work_orders` (unchanged), Handyman subject rows fall back to their applied
 * snapshots. Escalation materialization now runs for BOTH binding kinds (the
 * PART 01 Work-Order-only gate is closed by PART 02): Handyman breach facts,
 * `SLA_CLOCK_BREACHED`, and any escalation notification intent share the same
 * first-write-idempotent breach writer and the reused SLA-02 chain.
 */
export async function processDueSlaClocks(at:Date=new Date()):Promise<number>{const {withTransaction}=await import('../../database');const due=await appliedSlaRepository.findDueRunning(at);let count=0;for(const c of due){const scheduled=await withTransaction(async tx=>{const row=(await tx.query<{entityId:string;entityType:string;clientId:string;buildingId:string;workType:string|null;priority:string|null}>(`SELECT COALESCE(w.id,a.subject_id) AS "entityId",a.operational_type AS "entityType",a.client_id AS "clientId",a.building_id AS "buildingId",COALESCE(w.work_type,a.subject_work_type) AS "workType",COALESCE(w.priority,a.subject_priority) AS "priority" FROM applied_slas a LEFT JOIN work_orders w ON w.id=a.work_order_id WHERE a.id=$1`,[c.appliedSlaId])).rows[0];if(!row)return false;const b=await appliedSlaRepository.markBreached(c.id,at,tx);if(!b)return false;await recordOperationalEvent({clientId:row.clientId,buildingId:row.buildingId,entityType:row.entityType,entityId:row.entityId,eventType:'SLA_CLOCK_BREACHED',summary:'SLA clock breached',metadata:{clockId:b.id,clockType:b.clockType,breachedAt:at.toISOString()}},tx);await materializeEscalationActions({appliedSlaId:b.appliedSlaId,slaClockId:b.id,clockType:b.clockType,workOrderId:row.entityType==='WORK_ORDER'?row.entityId:null,subjectId:row.entityType==='WORK_ORDER'?null:row.entityId,subjectType:row.entityType,clientId:row.clientId,buildingId:row.buildingId,workType:row.workType??'',priority:row.priority??'',breachedAt:b.breachedAt??at},tx);return true});if(scheduled)count++}return count}
export async function getByWorkOrder(workOrderId:string):Promise<PublicAppliedSla|null>{const a=await appliedSlaRepository.findByWorkOrder(workOrderId);return a?publicRecord(a):null}
export async function getBySubject(subjectId:string):Promise<PublicAppliedSla|null>{const a=await appliedSlaRepository.findBySubject(subjectId);return a?publicRecord(a):null}
export const appliedSlaService={applyToNewWorkOrder,applyToNewSubject,getByWorkOrder,getBySubject};
