import type{PoolClient}from'pg';import{AppError}from'../../shared/errors';import{recordOperationalEvent}from'../operational-events';import{materializeEscalationActions}from'../sla-escalation-actions';import type{WorkOrderRecord}from'../work-orders';import{appliedSlaRepository}from'./applied-sla.repository';import type{AppliedSlaRecord,PublicAppliedSla,SlaClockRecord}from'./applied-sla.types';
async function clock(x:SlaClockRecord){const a=await appliedSlaRepository.pauseAccounting(x.id);return{...x,startedAt:x.startedAt.toISOString(),satisfiedAt:x.satisfiedAt?.toISOString()??null,terminatedAt:x.terminatedAt?.toISOString()??null,breachedAt:x.breachedAt?.toISOString()??null,createdAt:x.createdAt.toISOString(),updatedAt:x.updatedAt.toISOString(),isPaused:a.intervals.some(p=>p.resumedAt===null),totalPausedMilliseconds:a.totalPausedMilliseconds,effectiveElapsedMilliseconds:a.effectiveElapsedMilliseconds,pauseIntervals:a.intervals.map(p=>({...p,pausedAt:p.pausedAt.toISOString(),resumedAt:p.resumedAt?.toISOString()??null,createdAt:p.createdAt.toISOString(),updatedAt:p.updatedAt.toISOString()}))}}
async function publicRecord(a:AppliedSlaRecord):Promise<PublicAppliedSla>{const clocks=[];for(const c of await appliedSlaRepository.listClocks(a.id))clocks.push(await clock(c));return{...a,definitionEffectiveFrom:a.definitionEffectiveFrom.toISOString(),definitionEffectiveTo:a.definitionEffectiveTo?.toISOString()??null,appliedAt:a.appliedAt.toISOString(),createdAt:a.createdAt.toISOString(),clocks}}
export async function applyToNewWorkOrder(w:WorkOrderRecord,tx:PoolClient):Promise<AppliedSlaRecord|null>{const matches=await appliedSlaRepository.selectApplicable(w.clientId,w.buildingId,w.workType,w.priority,w.createdAt,tx);if(!matches.length)return null;const top=matches[0];if(matches[1]?.specificity===top.specificity)throw new AppError({code:'BAD_REQUEST',message:'Applicable SLA definitions are ambiguous.',statusCode:409});const applied=await appliedSlaRepository.createApplied(top,w,tx);const clocks:SlaClockRecord[]=[];if(top.responseTargetMinutes)clocks.push(await appliedSlaRepository.createClock(applied.id,'RESPONSE',top.responseTargetMinutes,w.createdAt,tx));if(top.resolutionTargetMinutes)clocks.push(await appliedSlaRepository.createClock(applied.id,'RESOLUTION',top.resolutionTargetMinutes,w.createdAt,tx));await recordOperationalEvent({clientId:w.clientId,buildingId:w.buildingId,entityType:'WORK_ORDER',entityId:w.id,eventType:'SLA_APPLIED',summary:`SLA ${top.code} applied to work order`,metadata:{appliedSlaId:applied.id,slaDefinitionId:top.id}},tx);for(const c of clocks)await recordOperationalEvent({clientId:w.clientId,buildingId:w.buildingId,entityType:'WORK_ORDER',entityId:w.id,eventType:'SLA_CLOCK_CREATED',summary:`${c.clockType} SLA clock created`,metadata:{appliedSlaId:applied.id,clockId:c.id,clockType:c.clockType}},tx);return applied}
/**
 * CR-BE-SLA-01 PART 05 due breach path, made transaction-safe in CR-BE-SLA-02
 * PART 02. Each due clock is handled in its own `withTransaction`, so the
 * breach write, `SLA_CLOCK_BREACHED`, and the escalation ledger materialized
 * from it commit together — identical to the lifecycle path — while one clock's
 * failure cannot roll back the others.
 */
export async function processDueSlaClocks(at:Date=new Date()):Promise<number>{const {withTransaction}=await import('../../database');const due=await appliedSlaRepository.findDueRunning(at);let count=0;for(const c of due){const scheduled=await withTransaction(async tx=>{const w=(await tx.query<{id:string;clientId:string;buildingId:string;workType:string;priority:string}>('SELECT w.id,w.client_id AS "clientId",w.building_id AS "buildingId",w.work_type AS "workType",w.priority FROM work_orders w JOIN applied_slas a ON a.work_order_id=w.id WHERE a.id=$1',[c.appliedSlaId])).rows[0];if(!w)return false;const b=await appliedSlaRepository.markBreached(c.id,at,tx);if(!b)return false;await recordOperationalEvent({clientId:w.clientId,buildingId:w.buildingId,entityType:'WORK_ORDER',entityId:w.id,eventType:'SLA_CLOCK_BREACHED',summary:'SLA clock breached',metadata:{clockId:b.id,clockType:b.clockType,breachedAt:at.toISOString()}},tx);await materializeEscalationActions({appliedSlaId:b.appliedSlaId,slaClockId:b.id,clockType:b.clockType,workOrderId:w.id,clientId:w.clientId,buildingId:w.buildingId,workType:w.workType,priority:w.priority,breachedAt:b.breachedAt??at},tx);return true});if(scheduled)count++}return count}
export async function getByWorkOrder(workOrderId:string):Promise<PublicAppliedSla|null>{const a=await appliedSlaRepository.findByWorkOrder(workOrderId);return a?publicRecord(a):null}export const appliedSlaService={applyToNewWorkOrder,getByWorkOrder};
