import{randomUUID}from'node:crypto';import type{Pool,PoolClient}from'pg';import{getPool}from'../../database';import type{AppliedSlaRecord,SlaClockRecord,SlaPauseIntervalRecord}from'./applied-sla.types';type Q=Pick<Pool|PoolClient,'query'>;
const A=`id,sla_definition_id AS "slaDefinitionId",work_order_id AS "workOrderId",client_id AS "clientId",building_id AS "buildingId",definition_code AS "definitionCode",operational_type AS "operationalType",definition_work_type AS "definitionWorkType",definition_priority AS "definitionPriority",work_order_work_type AS "workOrderWorkType",work_order_priority AS "workOrderPriority",response_target_minutes AS "responseTargetMinutes",resolution_target_minutes AS "resolutionTargetMinutes",definition_effective_from AS "definitionEffectiveFrom",definition_effective_to AS "definitionEffectiveTo",applied_at AS "appliedAt",created_at AS "createdAt"`;
const C=`id,applied_sla_id AS "appliedSlaId",clock_type AS "clockType",target_minutes AS "targetMinutes",started_at AS "startedAt",status,satisfied_at AS "satisfiedAt",terminated_at AS "terminatedAt",breached_at AS "breachedAt",created_at AS "createdAt",updated_at AS "updatedAt"`;
export type SelectedDefinition={id:string;clientId:string;buildingId:string|null;code:string;operationalType:'WORK_ORDER';workType:string|null;priority:string|null;responseTargetMinutes:number|null;resolutionTargetMinutes:number|null;effectiveFrom:Date;effectiveTo:Date|null;specificity:number};
async function selectApplicable(clientId:string,buildingId:string,workType:string,priority:string,at:Date,q:Q):Promise<SelectedDefinition[]>{return(await q.query<SelectedDefinition>(`SELECT id,client_id AS "clientId",building_id AS "buildingId",code,operational_type AS "operationalType",work_type AS "workType",priority,response_target_minutes AS "responseTargetMinutes",resolution_target_minutes AS "resolutionTargetMinutes",effective_from AS "effectiveFrom",effective_to AS "effectiveTo",(CASE WHEN building_id IS NOT NULL THEN 4 ELSE 0 END+CASE WHEN work_type IS NOT NULL THEN 2 ELSE 0 END+CASE WHEN priority IS NOT NULL THEN 1 ELSE 0 END)::int AS specificity FROM sla_definitions WHERE client_id=$1 AND (building_id IS NULL OR building_id=$2) AND operational_type='WORK_ORDER' AND status='ACTIVE' AND effective_from<=$5 AND (effective_to IS NULL OR effective_to>$5) AND (work_type IS NULL OR work_type=$3) AND (priority IS NULL OR priority=$4) ORDER BY specificity DESC`,[clientId,buildingId,workType,priority,at])).rows}
async function createApplied(d:SelectedDefinition,w:{id:string;clientId:string;buildingId:string;workType:string;priority:string;createdAt:Date},q:Q){return(await q.query<AppliedSlaRecord>(`INSERT INTO applied_slas(id,sla_definition_id,work_order_id,client_id,building_id,definition_code,operational_type,definition_work_type,definition_priority,work_order_work_type,work_order_priority,response_target_minutes,resolution_target_minutes,definition_effective_from,definition_effective_to,applied_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,NOW()) RETURNING ${A}`,[randomUUID(),d.id,w.id,w.clientId,w.buildingId,d.code,d.operationalType,d.workType,d.priority,w.workType,w.priority,d.responseTargetMinutes,d.resolutionTargetMinutes,d.effectiveFrom,d.effectiveTo])).rows[0]}
async function createClock(appliedId:string,type:'RESPONSE'|'RESOLUTION',target:number,start:Date,q:Q){return(await q.query<SlaClockRecord>(`INSERT INTO sla_clocks(id,applied_sla_id,clock_type,target_minutes,started_at)VALUES($1,$2,$3,$4,$5)RETURNING ${C}`,[randomUUID(),appliedId,type,target,start])).rows[0]}
async function findByWorkOrder(id:string,q:Q=getPool()){return(await q.query<AppliedSlaRecord>(`SELECT ${A} FROM applied_slas WHERE work_order_id=$1`,[id])).rows[0]??null}async function listClocks(id:string,q:Q=getPool()){return(await q.query<SlaClockRecord>(`SELECT ${C} FROM sla_clocks WHERE applied_sla_id=$1 ORDER BY clock_type`,[id])).rows}
const P=`id,sla_clock_id AS "slaClockId",paused_at AS "pausedAt",resumed_at AS "resumedAt",pause_source AS "pauseSource",pause_actor_user_id AS "pauseActorUserId",resume_actor_user_id AS "resumeActorUserId",created_at AS "createdAt",updated_at AS "updatedAt"`;
async function findClockForWorkOrder(workOrderId:string,type:'RESPONSE'|'RESOLUTION',q:Q){return(await q.query<SlaClockRecord>(`SELECT ${C} FROM sla_clocks c WHERE c.clock_type=$2 AND EXISTS(SELECT 1 FROM applied_slas a WHERE a.id=c.applied_sla_id AND a.work_order_id=$1) FOR UPDATE`,[workOrderId,type])).rows[0]??null}
async function openPause(clockId:string,at:Date,actor:string,q:Q){return(await q.query<SlaPauseIntervalRecord>(`INSERT INTO sla_clock_pause_intervals(id,sla_clock_id,paused_at,pause_source,pause_actor_user_id)VALUES($1,$2,$3,'WORK_ORDER_ON_HOLD',$4) ON CONFLICT(sla_clock_id) WHERE resumed_at IS NULL DO NOTHING RETURNING ${P}`,[randomUUID(),clockId,at,actor])).rows[0]??null}
async function closeOpenPause(clockId:string,at:Date,actor:string,q:Q){return(await q.query<SlaPauseIntervalRecord>(`UPDATE sla_clock_pause_intervals SET resumed_at=$2,resume_actor_user_id=$3,updated_at=NOW() WHERE sla_clock_id=$1 AND resumed_at IS NULL RETURNING ${P}`,[clockId,at,actor])).rows[0]??null}
async function closeOpenPauseAtTerminal(clockId:string,at:Date,q:Q){return(await q.query<SlaPauseIntervalRecord>(`UPDATE sla_clock_pause_intervals SET resumed_at=$2,updated_at=NOW() WHERE sla_clock_id=$1 AND resumed_at IS NULL RETURNING ${P}`,[clockId,at])).rows[0]??null}
async function transitionClock(clockId:string,status:'SATISFIED'|'TERMINATED',at:Date,q:Q){const col=status==='SATISFIED'?'satisfied_at':'terminated_at';return(await q.query<SlaClockRecord>(`UPDATE sla_clocks SET status=$2,${col}=$3,updated_at=NOW() WHERE id=$1 AND status='RUNNING' RETURNING ${C}`,[clockId,status,at])).rows[0]??null}
async function pauseAccounting(clockId:string,q:Q=getPool()){const intervals=(await q.query<SlaPauseIntervalRecord>(`SELECT ${P} FROM sla_clock_pause_intervals WHERE sla_clock_id=$1 ORDER BY paused_at,id`,[clockId])).rows;const totals=(await q.query<{totalPausedMilliseconds:string;effectiveElapsedMilliseconds:string}>(`SELECT GREATEST(0,FLOOR(EXTRACT(EPOCH FROM (statement_timestamp()-c.started_at))*1000)-COALESCE(SUM(FLOOR(EXTRACT(EPOCH FROM (COALESCE(p.resumed_at,statement_timestamp())-p.paused_at))*1000)),0))::bigint AS "effectiveElapsedMilliseconds",COALESCE(SUM(FLOOR(EXTRACT(EPOCH FROM (COALESCE(p.resumed_at,statement_timestamp())-p.paused_at))*1000)),0)::bigint AS "totalPausedMilliseconds" FROM sla_clocks c LEFT JOIN sla_clock_pause_intervals p ON p.sla_clock_id=c.id WHERE c.id=$1 GROUP BY c.id,c.started_at`,[clockId])).rows[0]??{totalPausedMilliseconds:'0',effectiveElapsedMilliseconds:'0'};return{intervals,totalPausedMilliseconds:Number(totals.totalPausedMilliseconds),effectiveElapsedMilliseconds:Number(totals.effectiveElapsedMilliseconds)}}
async function markBreached(clockId:string,at:Date,q:Q){return(await q.query<SlaClockRecord>(`UPDATE sla_clocks SET breached_at=COALESCE(breached_at,$2),updated_at=NOW() WHERE id=$1 AND status='RUNNING' AND breached_at IS NULL AND (EXTRACT(EPOCH FROM ($2-started_at))*60000-CASE WHEN clock_type='RESOLUTION' THEN COALESCE((SELECT SUM(EXTRACT(EPOCH FROM (COALESCE(resumed_at,$2)-paused_at))*60000) FROM sla_clock_pause_intervals WHERE sla_clock_id=$1),0) ELSE 0 END)>=target_minutes RETURNING ${C}`,[clockId,at])).rows[0]??null}
async function findDueRunning(at:Date,q:Q=getPool()){return(await q.query<SlaClockRecord>(`SELECT ${C} FROM sla_clocks WHERE status='RUNNING' AND breached_at IS NULL AND (EXTRACT(EPOCH FROM ($1-started_at))*60000-CASE WHEN clock_type='RESOLUTION' THEN COALESCE((SELECT SUM(EXTRACT(EPOCH FROM (COALESCE(resumed_at,$1)-paused_at))*60000) FROM sla_clock_pause_intervals WHERE sla_clock_id=sla_clocks.id),0) ELSE 0 END)>=target_minutes FOR UPDATE SKIP LOCKED`,[at])).rows}
export const appliedSlaRepository={selectApplicable,createApplied,createClock,findByWorkOrder,listClocks,findClockForWorkOrder,openPause,closeOpenPause,closeOpenPauseAtTerminal,transitionClock,pauseAccounting,markBreached,findDueRunning};
