import type{PoolClient}from'pg';import{recordOperationalEvent}from'../operational-events';import{cancelPendingEscalationActions,materializeEscalationActions}from'../sla-escalation-actions';import type{WorkOrderRecord}from'../work-orders';import{appliedSlaRepository}from'./applied-sla.repository';import type{SlaClockRecord,SlaSubjectRef}from'./applied-sla.types';
function refOf(w:WorkOrderRecord):SlaSubjectRef{return{subjectType:'WORK_ORDER',subjectId:w.id,clientId:w.clientId,buildingId:w.buildingId,workType:w.workType,priority:w.priority}}
async function event(ref:SlaSubjectRef,type:string,summary:string,metadata:Record<string,unknown>,tx:PoolClient){await recordOperationalEvent({clientId:ref.clientId,buildingId:ref.buildingId,entityType:ref.subjectType,entityId:ref.subjectId,eventType:type,summary,metadata},tx)}
/**
 * CR-HM-16 PART 01 — generic subject lifecycle over the SAME shared clock,
 * pause and breach authorities (governance `CR-HM-16_START_GOVERNANCE.md`
 * §4/§5/§9 PART 01: "Reuse existing clocks, pause, breach and escalation
 * authority"). One clock state machine (`transitionClock`), one pause ledger
 * (`openPause`/`closeOpenPause`/`closeOpenPauseAtTerminal`), one
 * first-write-idempotent breach writer (`markBreached`). The CR-BE-SLA-01
 * Work Order entry points below delegate here with `refOf` — no second
 * engine, no second breach writer.
 */
export async function evaluateBreachForSubject(ref:SlaSubjectRef,type:'RESPONSE'|'RESOLUTION',at:Date,tx:PoolClient){const c=await appliedSlaRepository.findClockForSubject(ref.subjectId,type,tx);if(!c||c.status!=='RUNNING')return c;const b=await appliedSlaRepository.markBreached(c.id,at,tx);if(b)await event(ref,'SLA_CLOCK_BREACHED','SLA clock breached',{clockId:b.id,clockType:b.clockType,breachedAt:at.toISOString()},tx);if(b&&ref.subjectType==='WORK_ORDER')await materializeEscalationActions({appliedSlaId:b.appliedSlaId,slaClockId:b.id,clockType:b.clockType,workOrderId:ref.subjectId,clientId:ref.clientId,buildingId:ref.buildingId,workType:ref.workType??'',priority:ref.priority??'',breachedAt:b.breachedAt??at},tx);return b??c}
/** CR-BE-SLA-02 PART 02: the first persisted breach also materializes its escalation ledger, in the same transaction. */
export async function materializeBreachEscalation(w:WorkOrderRecord,b:SlaClockRecord,tx:PoolClient){await materializeEscalationActions({appliedSlaId:b.appliedSlaId,slaClockId:b.id,clockType:b.clockType,workOrderId:w.id,clientId:w.clientId,buildingId:w.buildingId,workType:w.workType,priority:w.priority,breachedAt:b.breachedAt??new Date()},tx)}
export async function evaluateBreach(w:WorkOrderRecord,type:'RESPONSE'|'RESOLUTION',at:Date,tx:PoolClient){return evaluateBreachForSubject(refOf(w),type,at,tx)}
export async function satisfyClockForSubject(ref:SlaSubjectRef,type:'RESPONSE'|'RESOLUTION',at:Date,tx:PoolClient,evaluateBreachFirst=true){if(evaluateBreachFirst)await evaluateBreachForSubject(ref,type,at,tx);const c=await appliedSlaRepository.findClockForSubject(ref.subjectId,type,tx);if(!c||c.status!=='RUNNING')return;if(type==='RESOLUTION')await appliedSlaRepository.closeOpenPauseAtTerminal(c.id,at,tx);await appliedSlaRepository.transitionClock(c.id,'SATISFIED',at,tx);await cancelPendingEscalationActions(c.id,'CLOCK_SATISFIED',at,tx)}
export async function satisfyClock(w:WorkOrderRecord,type:'RESPONSE'|'RESOLUTION',at:Date,tx:PoolClient){await evaluateBreach(w,type,at,tx);await satisfyClockForSubject(refOf(w),type,at,tx,false)}
export async function terminateClocksForSubject(ref:SlaSubjectRef,at:Date,tx:PoolClient){for(const type of ['RESPONSE','RESOLUTION']as const){await evaluateBreachForSubject(ref,type,at,tx);const c=await appliedSlaRepository.findClockForSubject(ref.subjectId,type,tx);if(!c||c.status!=='RUNNING')continue;if(type==='RESOLUTION')await appliedSlaRepository.closeOpenPauseAtTerminal(c.id,at,tx);await appliedSlaRepository.transitionClock(c.id,'TERMINATED',at,tx);await cancelPendingEscalationActions(c.id,'CLOCK_TERMINATED',at,tx)}}
export async function terminateClocks(w:WorkOrderRecord,at:Date,tx:PoolClient){await terminateClocksForSubject(refOf(w),at,tx)}
export async function pauseResolutionClockForSubject(ref:SlaSubjectRef,at:Date,actor:string,tx:PoolClient){const c=await appliedSlaRepository.findClockForSubject(ref.subjectId,'RESOLUTION',tx);if(!c||c.status!=='RUNNING')return;const p=await appliedSlaRepository.openPause(c.id,at,actor,tx,ref.subjectType==='WORK_ORDER'?'WORK_ORDER_ON_HOLD':'SUBJECT_ON_HOLD');if(p)await event(ref,'SLA_RESOLUTION_CLOCK_PAUSED','SLA resolution clock paused',{clockId:c.id,pauseIntervalId:p.id},tx)}
export async function pauseResolutionClock(w:WorkOrderRecord,at:Date,actor:string,tx:PoolClient){await pauseResolutionClockForSubject(refOf(w),at,actor,tx)}
export async function resumeResolutionClockForSubject(ref:SlaSubjectRef,at:Date,actor:string,tx:PoolClient){const c=await appliedSlaRepository.findClockForSubject(ref.subjectId,'RESOLUTION',tx);if(!c||c.status!=='RUNNING')return;const p=await appliedSlaRepository.closeOpenPause(c.id,at,actor,tx);if(p)await event(ref,'SLA_RESOLUTION_CLOCK_RESUMED','SLA resolution clock resumed',{clockId:c.id,pauseIntervalId:p.id},tx)}
export async function resumeResolutionClock(w:WorkOrderRecord,at:Date,actor:string,tx:PoolClient){await resumeResolutionClockForSubject(refOf(w),at,actor,tx)}
