import type{PoolClient}from'pg';import{recordOperationalEvent}from'../operational-events';import{cancelPendingEscalationActions,materializeEscalationActions}from'../sla-escalation-actions';import type{WorkOrderRecord}from'../work-orders';import{appliedSlaRepository}from'./applied-sla.repository';import type{SlaClockRecord}from'./applied-sla.types';
async function event(w:WorkOrderRecord,type:string,summary:string,metadata:Record<string,unknown>,tx:PoolClient){await recordOperationalEvent({clientId:w.clientId,buildingId:w.buildingId,entityType:'WORK_ORDER',entityId:w.id,eventType:type,summary,metadata},tx)}
export async function pauseResolutionClock(w:WorkOrderRecord,at:Date,actor:string,tx:PoolClient){const c=await appliedSlaRepository.findClockForWorkOrder(w.id,'RESOLUTION',tx);if(!c||c.status!=='RUNNING')return;const p=await appliedSlaRepository.openPause(c.id,at,actor,tx);if(p)await event(w,'SLA_RESOLUTION_CLOCK_PAUSED','SLA resolution clock paused',{clockId:c.id,pauseIntervalId:p.id},tx)}
export async function resumeResolutionClock(w:WorkOrderRecord,at:Date,actor:string,tx:PoolClient){const c=await appliedSlaRepository.findClockForWorkOrder(w.id,'RESOLUTION',tx);if(!c||c.status!=='RUNNING')return;const p=await appliedSlaRepository.closeOpenPause(c.id,at,actor,tx);if(p)await event(w,'SLA_RESOLUTION_CLOCK_RESUMED','SLA resolution clock resumed',{clockId:c.id,pauseIntervalId:p.id},tx)}
/** CR-BE-SLA-02 PART 02: the first persisted breach also materializes its escalation ledger, in the same transaction. */
export async function materializeBreachEscalation(w:WorkOrderRecord,b:SlaClockRecord,tx:PoolClient){await materializeEscalationActions({appliedSlaId:b.appliedSlaId,slaClockId:b.id,clockType:b.clockType,workOrderId:w.id,clientId:w.clientId,buildingId:w.buildingId,workType:w.workType,priority:w.priority,breachedAt:b.breachedAt??new Date()},tx)}
export async function evaluateBreach(w:WorkOrderRecord,type:'RESPONSE'|'RESOLUTION',at:Date,tx:PoolClient){const c=await appliedSlaRepository.findClockForWorkOrder(w.id,type,tx);if(!c||c.status!=='RUNNING')return c;const b=await appliedSlaRepository.markBreached(c.id,at,tx);if(b)await event(w,'SLA_CLOCK_BREACHED','SLA clock breached',{clockId:b.id,clockType:b.clockType,breachedAt:at.toISOString()},tx);if(b)await materializeBreachEscalation(w,b,tx);return b??c}
export async function satisfyClock(w:WorkOrderRecord,type:'RESPONSE'|'RESOLUTION',at:Date,tx:PoolClient){await evaluateBreach(w,type,at,tx);const c=await appliedSlaRepository.findClockForWorkOrder(w.id,type,tx);if(!c||c.status!=='RUNNING')return;if(type==='RESOLUTION')await appliedSlaRepository.closeOpenPauseAtTerminal(c.id,at,tx);await appliedSlaRepository.transitionClock(c.id,'SATISFIED',at,tx);await cancelPendingEscalationActions(c.id,'CLOCK_SATISFIED',at,tx)}
export async function terminateClocks(w:WorkOrderRecord,at:Date,tx:PoolClient){for(const type of ['RESPONSE','RESOLUTION']as const){await evaluateBreach(w,type,at,tx);const c=await appliedSlaRepository.findClockForWorkOrder(w.id,type,tx);if(!c||c.status!=='RUNNING')continue;if(type==='RESOLUTION')await appliedSlaRepository.closeOpenPauseAtTerminal(c.id,at,tx);await appliedSlaRepository.transitionClock(c.id,'TERMINATED',at,tx);await cancelPendingEscalationActions(c.id,'CLOCK_TERMINATED',at,tx)}}
